// import mods.jei.JEI.removeAndHide as h;
// 
// h(item('enderutilities:nullifier:0'));
// h(item('enderutilities:pickupmanager'));
// h(item('enderutilities:quickstacker'));
// h(item('enderutilities:portalscaler:0'));
// h(item('enderutilities:ruler:0'));
// h(item('enderutilities:syringe:3'));
// h(item('enderutilities:syringe:2'));
// h(item('enderutilities:syringe:1'));
// h(item('enderutilities:syringe:0'));
// h(item('enderutilities:void_pickaxe:0'));
// h(item('enderutilities:portal_panel:0'));
// h(item('enderutilities:frame'));
// h(item('enderutilities:sound_block:0'));
// h(item('enderutilities:machine_1:0'));
// h(item('enderutilities:machine_0:0'));
// h(item('enderutilities:machine_1:1'));
// h(item('enderutilities:machine_1:2'));
// h(item('enderutilities:molecular_exciter:0'));
// h(item('enderutilities:endertool:1'));
// h(item('enderutilities:endertool:2'));
// h(item('enderutilities:endertool:3'));
// h(item('enderutilities:icemelter:0'));
// h(item('enderutilities:icemelter:1'));
// h(item('enderutilities:enderpart:40'));
// h(item('enderutilities:enderpart:30'));
// h(item('enderutilities:enderpart:45'));
// h(item('enderutilities:enderpart:50'));
// h(item('enderutilities:msu:0'));
// h(item('enderutilities:msu:1'));
// h(item('enderutilities:energy_bridge:2'));
// h(item('enderutilities:energy_bridge:0'));
// h(item('enderutilities:nullifier:0'));
// h(item('enderutilities:endersword:0'));
// h(item('enderutilities:endertool'));
// h(item('enderutilities:enderporter:1'));
// h(item('enderutilities:energy_bridge:1'));
// h(item('enderutilities:mobharness:0'));
// h(item('enderutilities:builderswand:0'));
// h(item('enderutilities:dolly:0'));
// h(item('enderutilities:enderarrow:0'));
// h(item('enderutilities:enderbow'));
// h(item('enderutilities:endercapacitor:3').withTag({EnderChargeAmount: 1000000000}));
// h(item('enderutilities:endercapacitor:3'));
// h(item('enderutilities:endercapacitor:2').withTag({EnderChargeAmount: 500000}));
// h(item('enderutilities:endercapacitor:2'));
// h(item('enderutilities:endercapacitor:1').withTag({EnderChargeAmount: 100000}));
// h(item('enderutilities:endercapacitor:1'));
// h(item('enderutilities:endercapacitor:0').withTag({EnderChargeAmount: 10000}));
// h(item('enderutilities:endercapacitor:0'));
// h(item('enderutilities:linkcrystal:2'));
// h(item('enderutilities:enderpearlreusable:1'));
// h(item('enderutilities:enderporter:0'));
// h(item('enderutilities:enderbag:0'));
// h(item('enderutilities:enderbucket:0'));
// h(item('enderutilities:chairwand:0'));
// h(item('enderutilities:linkcrystal:0'));
// h(item('enderutilities:linkcrystal:1'));
// h(item('enderutilities:livingmanipulator:0'));
// h(item('enderutilities:inventoryswapper'));
// h(item('enderutilities:draw_bridge:1'));
// h(item('enderutilities:draw_bridge:0'));
// h(item('enderutilities:inserter:1'));
// h(item('enderutilities:inserter:0'));
// h(item('enderutilities:machine_1:3'));
// h(item('enderutilities:enderpart:81'));
// h(item('enderutilities:enderlasso:0'));
// h(item('enderutilities:enderpart:21'));
// h(item('enderutilities:enderpart:20'));
// h(item('enderutilities:floor:0'));
// h(item('enderutilities:floor:1'));
// h(item('enderutilities:phasing:0'));
// h(item('enderutilities:phasing:1'));
// h(item('enderutilities:enderpart:0'));
// h(item('enderutilities:enderpart:1'));
// h(item('enderutilities:enderpart:2'));
// h(item('enderutilities:enderpart:10'));
// h(item('enderutilities:enderpart:11'));
// h(item('enderutilities:enderpart:12'));
// h(item('enderutilities:enderpart:15'));
// h(item('enderutilities:enderpart:16'));
// h(item('enderutilities:enderpart:17'));
// h(item('enderutilities:ender_elevator:0'));
// h(item('enderutilities:ender_elevator_slab:0'));
// h(item('enderutilities:ender_elevator_layer:0'));
// crafting.removeByOutput(item('enderutilities:handybag:0'));
// crafting.removeByOutput(item('enderutilities:handybag:1'));
// crafting.removeByOutput(item('enderutilities:pet_contract:0'));
// crafting.removeByOutput(item('enderutilities:handybag:0'));
// crafting.removeByOutput(item('enderutilities:handybag:1'));
// crafting.removeByOutput(item('enderutilities:pet_contract:0'));
// crafting.removeByOutput(item('enderutilities:enderpart:51'));
// crafting.removeByOutput(item('enderutilities:enderpart:52'));
// crafting.removeByOutput(item('enderutilities:enderpart:53'));
// crafting.removeByOutput(item('enderutilities:enderpart:54'));
// crafting.removeByOutput(item('enderutilities:barrel:0'));
// crafting.removeByOutput(item('enderutilities:asu:0'));
// crafting.removeByOutput(item('enderutilities:enderpart:73'));
// crafting.removeByOutput(item('enderutilities:enderpart:72'));
// h(item('enderutilities:enderpart:71'));
// crafting.removeByOutput(item('enderutilities:enderpart:70'));
// crafting.removeByOutput(item('enderutilities:enderpart:80'));
// crafting.removeByOutput(item('enderutilities:storage_0:0'));
// crafting.removeByOutput(item('enderutilities:storage_0:1'));
// crafting.removeByOutput(item('enderutilities:storage_0:2'));
// crafting.removeByOutput(item('enderutilities:storage_0:3'));
// crafting.removeByOutput(item('enderutilities:storage_0:4'));
// crafting.removeByOutput(item('enderutilities:storage_0:5'));
// crafting.removeByOutput(item('enderutilities:storage_0:6'));
// crafting.addShaped(item('enderutilities:pet_contract:0'), [[null, ore('dyeBlack'), ore('dyeBlack')],[ore('paper,paperEmpty,platePaper'), ore('paper,paperEmpty,platePaper'), ore('dyeBlack')], [ore('paper,paperEmpty,platePaper'), ore('paper,paperEmpty,platePaper'), null]]);
// crafting.addShaped(item('enderutilities:enderpart:54'), [[null, null, null],[ore('ingotPulsatingIron'), ore('circuitUltimate'), ore('ingotPulsatingIron')], [ore('ingotPulsatingIron'), item('gregtech:mte:1561'), ore('ingotPulsatingIron')]]);
// crafting.addShaped(item('enderutilities:enderpart:53'), [[null, null, null],[ore('ingotPulsatingIron'), ore('circuitElite'), ore('ingotPulsatingIron')], [ore('ingotPulsatingIron'), item('gregtech:machine:806'), ore('ingotPulsatingIron')]]);
// crafting.addShaped(item('enderutilities:enderpart:52'), [[null, null, null],[ore('ingotPulsatingIron'), ore('circuitExtreme'), ore('ingotPulsatingIron')], [ore('ingotPulsatingIron'), item('gregtech:machine:805'), ore('ingotPulsatingIron')]]);
// crafting.addShaped(item('enderutilities:enderpart:51'), [[null, null, null],[ore('ingotPulsatingIron'), ore('circuitAdvanced'), ore('ingotPulsatingIron')], [ore('ingotPulsatingIron'), item('gregtech:machine:804'), ore('ingotPulsatingIron')]]);
// crafting.addShaped(item('enderutilities:storage_0:6'), [[null, ore('circuitUltimate'), null],[null, item('enderutilities:storage_0:5'), null], [null, ore('circuitUltimate'), null]]);
// crafting.addShaped(item('enderutilities:storage_0:5'), [[null, ore('circuitElite'), null],[null, item('enderutilities:storage_0:4'), null], [null, ore('circuitElite'), null]]);
// crafting.addShaped(item('enderutilities:storage_0:4'), [[null, ore('circuitExtreme'), null],[null, item('enderutilities:storage_0:3'), null], [null, ore('circuitExtreme'), null]]);
// crafting.addShaped(item('enderutilities:storage_0:3'), [[null, ore('circuitAdvanced'), null],[null, item('gregtech:machine:804'), null], [null, ore('circuitAdvanced'), null]]);
// crafting.addShaped(item('enderutilities:storage_0:2'), [[null, ore('circuitElite'), null],[null, item('enderutilities:storage_0:1'), null], [null, item('enderutilities:storage_0:1'), null]]);
// crafting.addShaped(item('enderutilities:storage_0:1'), [[null, ore('circuitExtreme'), null],[null, item('enderutilities:storage_0:0'), null], [null, null, null]]);
// crafting.addShaped(item('enderutilities:storage_0:0'), [[null, ore('circuitAdvanced'), null],[null, item('gregtech:machine:804'), null], [null, null, null]]);
// crafting.addShaped(item('enderutilities:handybag:1'), [[ore('ingotPulsatingIron'), item('enderutilities:handybag:0'), ore('ingotPulsatingIron')],[item('enderutilities:handybag:0'), ore('circuitExtreme'), item('enderutilities:handybag:0')], [ore('ingotPulsatingIron'), item('enderutilities:handybag:0'), ore('ingotPulsatingIron')]]);
// crafting.addShaped(item('enderutilities:handybag:0'), [[ore('ingotPulsatingIron'), item('ironbackpacks:backpack:0').withTag({packInfo: {upgrade: [], type: "ironbackpacks:diamond", spec: "STORAGE"}}), ore('ingotPulsatingIron')],[item('ironbackpacks:backpack:0').withTag({packInfo: {upgrade: [], type: "ironbackpacks:diamond", spec: "STORAGE"}}), ore('circuitAdvanced'), item('ironbackpacks:backpack:0').withTag({packInfo: {upgrade: [], type: "ironbackpacks:diamond", spec: "STORAGE"}})], [ore('ingotPulsatingIron'), item('ironbackpacks:backpack:0').withTag({packInfo: {upgrade: [], type: "ironbackpacks:diamond", spec: "STORAGE"}}), ore('ingotPulsatingIron')]]);
// crafting.addShaped(item('enderutilities:barrel:0'), [[ore('ingotPulsatingIron'), item('actuallyadditions:block_giant_chest:0'), ore('ingotPulsatingIron')],[item('actuallyadditions:block_giant_chest:0'), ore('chest,chestWood'), item('actuallyadditions:block_giant_chest:0')], [ore('ingotPulsatingIron'), item('actuallyadditions:block_giant_chest:0'), ore('ingotPulsatingIron')]]);
// crafting.addShaped(item('enderutilities:asu:0'), [[ore('ingotPulsatingIron'), item('minecraft:comparator:0'), ore('ingotPulsatingIron')],[ore('ingotPulsatingIron'), item('actuallyadditions:block_giant_chest:0'), ore('ingotPulsatingIron')], [ore('ingotPulsatingIron'), item('minecraft:comparator:0'), ore('ingotPulsatingIron')]]);
// crafting.addShaped(item('enderutilities:enderpart:80'), [[ore('ingotPulsatingIron'), ore('ingotPulsatingIron'), null],[ore('ingotPulsatingIron'), ore('nuggetPulsatingIron'), null], [null, ore('nuggetPulsatingIron'), null]]);
// crafting.addShaped(item('enderutilities:enderpart:70'), [[ore('stickWood'), ore('stickWood'), ore('stickWood')],[ore('stickWood'), ore('ingotPulsatingIron'), ore('stickWood')], [ore('stickWood'), ore('stickWood'), ore('stickWood')]]);
// crafting.addShaped(item('enderutilities:enderpart:72'), [[ore('ingotPulsatingIron'), item('actuallyadditions:block_giant_chest:0'), ore('ingotPulsatingIron')],[item('actuallyadditions:block_giant_chest:0'), item('enderutilities:barrel:0'), item('actuallyadditions:block_giant_chest:0')], [ore('ingotPulsatingIron'), item('actuallyadditions:block_giant_chest:0'), ore('ingotPulsatingIron')]]);
// crafting.addShaped(item('enderutilities:enderpart:73') * 2, [[item('minecraft:obsidian'), item('minecraft:obsidian'), item('minecraft:obsidian')],[item('minecraft:obsidian'), item('storagedrawers:upgrade_void:0'), item('minecraft:obsidian')], [item('minecraft:obsidian'), item('minecraft:obsidian'), item('minecraft:obsidian')]]);