// import mods.jei.JEI.removeAndHide as h;
// 
// h(item('enderutilities:nullifier'));
// h(item('enderutilities:pickupmanager'));
// h(item('enderutilities:quickstacker'));
// h(item('enderutilities:portalscaler'));
// h(item('enderutilities:ruler'));
// h(item('enderutilities:syringe', 3));
// h(item('enderutilities:syringe', 2));
// h(item('enderutilities:syringe', 1));
// h(item('enderutilities:syringe'));
// h(item('enderutilities:void_pickaxe'));
// h(item('enderutilities:portal_panel'));
// h(item('enderutilities:frame'));
// h(item('enderutilities:sound_block'));
// h(item('enderutilities:machine_1'));
// h(item('enderutilities:machine_0'));
// h(item('enderutilities:machine_1', 1));
// h(item('enderutilities:machine_1', 2));
// h(item('enderutilities:molecular_exciter'));
// h(item('enderutilities:endertool', 1));
// h(item('enderutilities:endertool', 2));
// h(item('enderutilities:endertool', 3));
// h(item('enderutilities:icemelter'));
// h(item('enderutilities:icemelter', 1));
// h(item('enderutilities:enderpart', 40));
// h(item('enderutilities:enderpart', 30));
// h(item('enderutilities:enderpart', 45));
// h(item('enderutilities:enderpart', 50));
// h(item('enderutilities:msu'));
// h(item('enderutilities:msu', 1));
// h(item('enderutilities:energy_bridge', 2));
// h(item('enderutilities:energy_bridge'));
// h(item('enderutilities:nullifier'));
// h(item('enderutilities:endersword'));
// h(item('enderutilities:endertool'));
// h(item('enderutilities:enderporter', 1));
// h(item('enderutilities:energy_bridge', 1));
// h(item('enderutilities:mobharness'));
// h(item('enderutilities:builderswand'));
// h(item('enderutilities:dolly'));
// h(item('enderutilities:enderarrow'));
// h(item('enderutilities:enderbow'));
// h(item('enderutilities:endercapacitor', 3).withTag({EnderChargeAmount: 1000000000}));
// h(item('enderutilities:endercapacitor', 3));
// h(item('enderutilities:endercapacitor', 2).withTag({EnderChargeAmount: 500000}));
// h(item('enderutilities:endercapacitor', 2));
// h(item('enderutilities:endercapacitor', 1).withTag({EnderChargeAmount: 100000}));
// h(item('enderutilities:endercapacitor', 1));
// h(item('enderutilities:endercapacitor').withTag({EnderChargeAmount: 10000}));
// h(item('enderutilities:endercapacitor'));
// h(item('enderutilities:linkcrystal', 2));
// h(item('enderutilities:enderpearlreusable', 1));
// h(item('enderutilities:enderporter'));
// h(item('enderutilities:enderbag'));
// h(item('enderutilities:enderbucket'));
// h(item('enderutilities:chairwand'));
// h(item('enderutilities:linkcrystal'));
// h(item('enderutilities:linkcrystal', 1));
// h(item('enderutilities:livingmanipulator'));
// h(item('enderutilities:inventoryswapper'));
// h(item('enderutilities:draw_bridge', 1));
// h(item('enderutilities:draw_bridge'));
// h(item('enderutilities:inserter', 1));
// h(item('enderutilities:inserter'));
// h(item('enderutilities:machine_1', 3));
// h(item('enderutilities:enderpart', 81));
// h(item('enderutilities:enderlasso'));
// h(item('enderutilities:enderpart', 21));
// h(item('enderutilities:enderpart', 20));
// h(item('enderutilities:floor'));
// h(item('enderutilities:floor', 1));
// h(item('enderutilities:phasing'));
// h(item('enderutilities:phasing', 1));
// h(item('enderutilities:enderpart'));
// h(item('enderutilities:enderpart', 1));
// h(item('enderutilities:enderpart', 2));
// h(item('enderutilities:enderpart', 10));
// h(item('enderutilities:enderpart', 11));
// h(item('enderutilities:enderpart', 12));
// h(item('enderutilities:enderpart', 15));
// h(item('enderutilities:enderpart', 16));
// h(item('enderutilities:enderpart', 17));
// h(item('enderutilities:ender_elevator'));
// h(item('enderutilities:ender_elevator_slab'));
// h(item('enderutilities:ender_elevator_layer'));
// crafting.removeByOutput(item('enderutilities:handybag'));
// crafting.removeByOutput(item('enderutilities:handybag', 1));
// crafting.removeByOutput(item('enderutilities:pet_contract'));
// crafting.removeByOutput(item('enderutilities:handybag'));
// crafting.removeByOutput(item('enderutilities:handybag', 1));
// crafting.removeByOutput(item('enderutilities:pet_contract'));
// crafting.removeByOutput(item('enderutilities:enderpart', 51));
// crafting.removeByOutput(item('enderutilities:enderpart', 52));
// crafting.removeByOutput(item('enderutilities:enderpart', 53));
// crafting.removeByOutput(item('enderutilities:enderpart', 54));
// crafting.removeByOutput(item('enderutilities:barrel'));
// crafting.removeByOutput(item('enderutilities:asu'));
// crafting.removeByOutput(item('enderutilities:enderpart', 73));
// crafting.removeByOutput(item('enderutilities:enderpart', 72));
// h(item('enderutilities:enderpart', 71));
// crafting.removeByOutput(item('enderutilities:enderpart', 70));
// crafting.removeByOutput(item('enderutilities:enderpart', 80));
// crafting.removeByOutput(item('enderutilities:storage_0'));
// crafting.removeByOutput(item('enderutilities:storage_0', 1));
// crafting.removeByOutput(item('enderutilities:storage_0', 2));
// crafting.removeByOutput(item('enderutilities:storage_0', 3));
// crafting.removeByOutput(item('enderutilities:storage_0', 4));
// crafting.removeByOutput(item('enderutilities:storage_0', 5));
// crafting.removeByOutput(item('enderutilities:storage_0', 6));
// crafting.addShaped(item('enderutilities:pet_contract'), [[null, ore('dyeBlack'), ore('dyeBlack')],[ore('paper,paperEmpty,platePaper'), ore('paper,paperEmpty,platePaper'), ore('dyeBlack')], [ore('paper,paperEmpty,platePaper'), ore('paper,paperEmpty,platePaper'), null]]);
// crafting.addShaped(item('enderutilities:enderpart', 54), [[null, null, null],[ore('ingotPulsatingIron'), ore('circuitUltimate'), ore('ingotPulsatingIron')], [ore('ingotPulsatingIron'), item('gregtech:mte:1561'), ore('ingotPulsatingIron')]]);
// crafting.addShaped(item('enderutilities:enderpart', 53), [[null, null, null],[ore('ingotPulsatingIron'), ore('circuitElite'), ore('ingotPulsatingIron')], [ore('ingotPulsatingIron'), item('gregtech:machine', 806), ore('ingotPulsatingIron')]]);
// crafting.addShaped(item('enderutilities:enderpart', 52), [[null, null, null],[ore('ingotPulsatingIron'), ore('circuitExtreme'), ore('ingotPulsatingIron')], [ore('ingotPulsatingIron'), item('gregtech:machine', 805), ore('ingotPulsatingIron')]]);
// crafting.addShaped(item('enderutilities:enderpart', 51), [[null, null, null],[ore('ingotPulsatingIron'), ore('circuitAdvanced'), ore('ingotPulsatingIron')], [ore('ingotPulsatingIron'), item('gregtech:machine', 804), ore('ingotPulsatingIron')]]);
// crafting.addShaped(item('enderutilities:storage_0', 6), [[null, ore('circuitUltimate'), null],[null, item('enderutilities:storage_0', 5), null], [null, ore('circuitUltimate'), null]]);
// crafting.addShaped(item('enderutilities:storage_0', 5), [[null, ore('circuitElite'), null],[null, item('enderutilities:storage_0', 4), null], [null, ore('circuitElite'), null]]);
// crafting.addShaped(item('enderutilities:storage_0', 4), [[null, ore('circuitExtreme'), null],[null, item('enderutilities:storage_0', 3), null], [null, ore('circuitExtreme'), null]]);
// crafting.addShaped(item('enderutilities:storage_0', 3), [[null, ore('circuitAdvanced'), null],[null, item('gregtech:machine', 804), null], [null, ore('circuitAdvanced'), null]]);
// crafting.addShaped(item('enderutilities:storage_0', 2), [[null, ore('circuitElite'), null],[null, item('enderutilities:storage_0', 1), null], [null, item('enderutilities:storage_0', 1), null]]);
// crafting.addShaped(item('enderutilities:storage_0', 1), [[null, ore('circuitExtreme'), null],[null, item('enderutilities:storage_0'), null], [null, null, null]]);
// crafting.addShaped(item('enderutilities:storage_0'), [[null, ore('circuitAdvanced'), null],[null, item('gregtech:machine', 804), null], [null, null, null]]);
// crafting.addShaped(item('enderutilities:handybag', 1), [[ore('ingotPulsatingIron'), item('enderutilities:handybag'), ore('ingotPulsatingIron')],[item('enderutilities:handybag'), ore('circuitExtreme'), item('enderutilities:handybag')], [ore('ingotPulsatingIron'), item('enderutilities:handybag'), ore('ingotPulsatingIron')]]);
// crafting.addShaped(item('enderutilities:handybag'), [[ore('ingotPulsatingIron'), item('ironbackpacks:backpack').withTag({packInfo: {upgrade: [], type: "ironbackpacks:diamond", spec: "STORAGE"}}), ore('ingotPulsatingIron')],[item('ironbackpacks:backpack').withTag({packInfo: {upgrade: [], type: "ironbackpacks:diamond", spec: "STORAGE"}}), ore('circuitAdvanced'), item('ironbackpacks:backpack').withTag({packInfo: {upgrade: [], type: "ironbackpacks:diamond", spec: "STORAGE"}})], [ore('ingotPulsatingIron'), item('ironbackpacks:backpack').withTag({packInfo: {upgrade: [], type: "ironbackpacks:diamond", spec: "STORAGE"}}), ore('ingotPulsatingIron')]]);
// crafting.addShaped(item('enderutilities:barrel'), [[ore('ingotPulsatingIron'), item('actuallyadditions:block_giant_chest'), ore('ingotPulsatingIron')],[item('actuallyadditions:block_giant_chest'), ore('chest,chestWood'), item('actuallyadditions:block_giant_chest')], [ore('ingotPulsatingIron'), item('actuallyadditions:block_giant_chest'), ore('ingotPulsatingIron')]]);
// crafting.addShaped(item('enderutilities:asu'), [[ore('ingotPulsatingIron'), item('minecraft:comparator'), ore('ingotPulsatingIron')],[ore('ingotPulsatingIron'), item('actuallyadditions:block_giant_chest'), ore('ingotPulsatingIron')], [ore('ingotPulsatingIron'), item('minecraft:comparator'), ore('ingotPulsatingIron')]]);
// crafting.addShaped(item('enderutilities:enderpart', 80), [[ore('ingotPulsatingIron'), ore('ingotPulsatingIron'), null],[ore('ingotPulsatingIron'), ore('nuggetPulsatingIron'), null], [null, ore('nuggetPulsatingIron'), null]]);
// crafting.addShaped(item('enderutilities:enderpart', 70), [[ore('stickWood'), ore('stickWood'), ore('stickWood')],[ore('stickWood'), ore('ingotPulsatingIron'), ore('stickWood')], [ore('stickWood'), ore('stickWood'), ore('stickWood')]]);
// crafting.addShaped(item('enderutilities:enderpart', 72), [[ore('ingotPulsatingIron'), item('actuallyadditions:block_giant_chest'), ore('ingotPulsatingIron')],[item('actuallyadditions:block_giant_chest'), item('enderutilities:barrel'), item('actuallyadditions:block_giant_chest')], [ore('ingotPulsatingIron'), item('actuallyadditions:block_giant_chest'), ore('ingotPulsatingIron')]]);
// crafting.addShaped(item('enderutilities:enderpart', 73) * 2, [[item('minecraft:obsidian'), item('minecraft:obsidian'), item('minecraft:obsidian')],[item('minecraft:obsidian'), item('storagedrawers:upgrade_void'), item('minecraft:obsidian')], [item('minecraft:obsidian'), item('minecraft:obsidian'), item('minecraft:obsidian')]]);