// no_run


// crafting.removeByOutput(item('gregtech:machine:4212'))
// crafting.addShaped(item('gregtech:machine:4212'), [[item('gregtech:fluid_pipe:2095'), item('gregtech:fluid_pipe:2095'), item('gregtech:fluid_pipe:2095')], [item('contenttweaker:steampiston'), item('gregtech:steam_casing'), item('contenttweaker:steampiston')], [ore('rotorBronze'), item('gregtech:fluid_pipe:2095'), ore('rotorBronze')]])

// crafting.addShaped(ore('componentResistor') * 2, [[item('gregtech:meta_item_1', 438), ore('wireGtSingleCopper'), item('gregtech:meta_item_1', 438)], [ore('wireGtSingleCopper'), ore('dustCharcoal'), ore('wireGtSingleCopper')], [null, ore('wireGtSingleCopper'), null]])
// crafting.addShaped(ore('componentResistor') * 2, [[item('gregtech:meta_item_1', 438), ore('wireGtSingleCopper'), item('gregtech:meta_item_1', 438)], [ore('wireGtSingleCopper'), ore('dustCoal'), ore('wireGtSingleCopper')], [null, ore('wireGtSingleCopper'), null]])
// crafting.removeByOutput(item('apotheosis:hellshelf'))
// crafting.addShaped(item('apotheosis:hellshelf'), [[item('minecraft:nether_brick'), ore('logWood'), item('minecraft:nether_brick')], [ore('bookEmpty,craftingBook'), ore('bookEmpty,craftingBook'), ore('bookEmpty,craftingBook')], [item('minecraft:nether_brick'), ore('logWood'), item('minecraft:nether_brick')]])
// crafting.addShaped(item('apotheosis:hellshelf'), [[item('minecraft:nether_brick'), item('minecraft:nether_brick'), item('minecraft:nether_brick')], [null, item('minecraft:bookshelf'), null], [item('minecraft:nether_brick'), item('minecraft:nether_brick'), item('minecraft:nether_brick')]])
// crafting.addShapeless(item('gregtech:mte', 560), [item('actuallyadditions:block_atomic_reconstructor')])
// crafting.addShaped(ore('bookEnchanted,craftingBook').withNbt({ StoredEnchantments:
// [{ lvl:
// 1 as short ,
//      id:
//      45 as short }] }), [[item('minecraft:red_nether_brick'), item('minecraft:netherrack'), item('minecraft:red_nether_brick')], [item('minecraft:netherrack'), ore('bookEmpty,craftingBook'), item('minecraft:netherrack')], [item('minecraft:nether_brick'), item('minecraft:netherrack'), item('minecraft:nether_brick')]])

// // coke oven and primitve alloy
// crafting.addShaped(item('gregtech:machine:1002'), [[item('gregtech:metal_casing', 1), metaitem('tjceu:steam.motor.ulv'), item('gregtech:metal_casing', 1)], [metaitem('tjceu:steam.motor.ulv'), null, item('contenttweaker:steampiston')], [item('gregtech:metal_casing', 1), item('contenttweaker:steampiston'), item('gregtech:metal_casing', 1)]])
// crafting.addShaped(item('gregtech:mte:1017'), [[item('gregtech:metal_casing', 8), ore('plateDoubleBronze'), item('gregtech:metal_casing', 8)], [ore('plateDoubleBronze'), null, ore('plateDoubleBronze')], [item('gregtech:metal_casing', 8), ore('plateDoubleBronze'), item('gregtech:metal_casing', 8)]])

// /*
// Utils.removeRecipeByOutput(mixer, [], [fluid('nitro_fuel') * 750], true)

// MIXER.recipeBuilder()
// .fluidInputs([fluid('bio_diesel') * 1000 ,fluid('tetranitromethane') * 20])
// .fluidOutputs([fluid('nitro_fuel') * 1000])
// .EUt(480)
// .duration(20)
// .buildAndRegister()

// Utils.removeRecipeByOutput(largeMix, [], [fluid('nitro_fuel') * 750], true)
// LARGE_MIXER.recipeBuilder()
// .fluidInputs([fluid('bio_diesel') * 1000, fluid('tetranitromethane') * 20])
// .fluidOutputs([fluid('nitro_fuel') * 1000])
// .circuit(2)
// .EUt(480)
// .duration(20)
// .buildAndRegister()

// */

// Utils.removeRecipeByOutput(mixer, [], [fluid('nitro_fuel') * 1000], true)

// MIXER.recipeBuilder()
//         .fluidInputs([fluid('fuel') * 2000, fluid('tetranitromethane') * 20])
//         .fluidOutputs([fluid('nitro_fuel') * 2000])
//         .EUt(480)
//         .duration(20)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(largeMix, [], [fluid('nitro_fuel') * 1000], true)

// LARGE_MIXER.recipeBuilder()
//         .fluidInputs([fluid('fuel') * 2000, fluid('tetranitromethane') * 20])
//         .fluidOutputs([fluid('nitro_fuel') * 2000])
//         .circuitMeta(2)
//         .EUt(480)
//         .duration(20)
//         .buildAndRegister()


// //Nitro Benzeene

// Utils.removeRecipeByOutput(chemreactor, [], [fluid('nitro_benzene') * 1000], true)

// CHEMICAL_REACTOR.recipeBuilder()
//         .fluidInputs(fluid('nitration_mixture') * 2000, fluid('benzene') * 5000, fluid('distilled_water') * 2000)
//         .fluidOutputs(fluid('nitro_benzene') * 8000, fluid('diluted_sulfuric_acid') * 1000)
//         .EUt(320)
//         .duration(120)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(large_chem, [], [fluid('nitro_benzene') * 1000], true)

// LCR.recipeBuilder()
//         .fluidInputs(fluid('nitration_mixture') * 2000, fluid('benzene') * 5000, fluid('distilled_water') * 2000)
//         .fluidOutputs(fluid('nitro_benzene') * 8000, fluid('diluted_sulfuric_acid') * 1000)
//         .EUt(320)
//         .duration(120)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(assembler, [item('gregtech:machine:4239')], [], true)

// ASSEMBLER.recipeBuilder()
//         .inputs(item('gregtech:meta_item_1:32600') * 4, metaitem('electric.pump.lv') * 4, item('gregtech:mte', 986), item('gregtech:meta_block_frame_20', 4), item('gregtech:meta_item_2:26017') * 2, ore('circuitBasic'))
//         .circuitMeta(2)
//         .outputs(item('gregtech:machine:4239'))
//         .EUt(30)
//         .duration(400)
//         .buildAndRegister()

// //start of weirdness
// distillery.findRecipe(100, [item('gregtech:meta_item_1:32766').withNbt({ Configuration: 0 })], [fluid('biomass') * 2000]).remove()

// DISTILLERY.recipeBuilder()
//         .fluidInputs(fluid('biomass') * 1000)
//         .fluidOutputs(fluid('ethanol') * 600)
//         .circuitMeta(0)
//         .EUt(16)
//         .duration(80)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(centrifuge, [], [fluid('oil') * 100], true)
// Utils.removeRecipeByOutput(large_centrifuge, [], [fluid('oil') * 100], true)

// crafting.addShaped(item('variegated:defiled_ground') * 4, [[ore('itemSkull'), item('minecraft:soul_sand'), ore('itemSkull')], [item('minecraft:soul_sand'), ore('ingotSoularium'), item('minecraft:soul_sand')], [ore('itemSkull'), item('minecraft:soul_sand'), ore('itemSkull')]])
// crafting.removeByOutput(item('variegated:defiled_ground'))

// //concrete recipes

// MIXER.recipeBuilder()
//         .inputs(item('minecraft:concrete_powder') * 64)
//         .fluidInputs(fluid('water') * 100)
//         .outputs(item('minecraft:concrete') * 64)
//         .duration(100)
//         .EUt(16)
//         .buildAndRegister()

// val i = 0
// for
// i in 1 to 16 {
//     MIXER.recipeBuilder()

//             .inputs(itemUtils.getItem("minecraft:concrete_powder", i) * 64)
//             .fluidInputs(fluid('water') * 1000)
//             .outputs(itemUtils.getItem("minecraft:concrete", i) * 64)
//             .duration(100)
//             .EUt(16)
//             .buildAndRegister()
// }
// //Large concrete recipes

// LARGE_MIXER.recipeBuilder()
//         .inputs(item('minecraft:concrete_powder') * 64)
//         .fluidInputs(fluid('water') * 100)
//         .outputs(item('minecraft:concrete') * 64)
//         .duration(100)
//         .EUt(16)
//         .buildAndRegister()

// val f = 0
// for
// f in 1 to 16 {
//     LARGE_MIXER.recipeBuilder()
//             .inputs(itemUtils.getItem("minecraft:concrete_powder", f) * 64)
//             .fluidInputs(fluid('water') * 1000)
//             .outputs(itemUtils.getItem("minecraft:concrete", f) * 64)
//             .duration(100)
//             .EUt(16)
//             .buildAndRegister()
// }

// crafting.removeByOutput(item('gregtech:machine:4024'))
// crafting.addShaped(item('gregtech:machine:4024'), [[item('minecraft:glass'), item('minecraft:glass'), item('minecraft:glass')], [ore('plateSteel'), item('gregtech:mte', 986), ore('plateSteel')], [ore('cableGtSingleTin'), ore('toolHeadDrillSteel'), ore('cableGtSingleTin')]])
// crafting.removeByOutput(item('draconicevolution:diss_enchanter'))
// crafting.addShaped(item('draconicevolution:diss_enchanter'), [[ore('gemEmerald'), ore('plateDoubleAluminium'), ore('gemEmerald')], [ore('plateDoubleAluminium'), item('minecraft:enchanting_table'), ore('plateDoubleAluminium')], [item('minecraft:bookshelf'), item('minecraft:bookshelf'), item('minecraft:bookshelf')]])
// //MOB stuff
// crafting.removeByOutput(item('mob_grinding_utils:fan'))
// crafting.addShaped(item('mob_grinding_utils:fan'), [[ore('plateAluminium'), ore('dustRedstone'), ore('cableGtSingleTin')], [ore('dustRedstone'), item('gregtech:mte', 986), ore('rotorSteel')], [ore('plateAluminium'), ore('dustRedstone'), ore('cableGtSingleTin')]])
// crafting.removeByOutput(item('mob_grinding_utils:spikes'))
// crafting.addShaped(item('mob_grinding_utils:spikes'), [[null, item('gregtech:meta_item_2', 33), null], [item('gregtech:meta_item_2', 33), item('gregtech:mte', 986), item('gregtech:meta_item_2', 33)], [item('gtadditions:ga_meta_item:1033'), item('gtadditions:ga_meta_item:1033'), item('gtadditions:ga_meta_item:1033')]])
// crafting.removeByOutput(item('mob_grinding_utils:saw'))
// crafting.addShaped(item('mob_grinding_utils:saw'), [[ore('plateStainlessSteel'), item('gregtech:meta_item_2', 183), ore('plateStainlessSteel')], [ore('gemExquisiteDiamond'), item('mob_grinding_utils:spikes'), ore('gemExquisiteDiamond')], [ore('plateStainlessSteel'), ore('plateStainlessSteel'), ore('plateStainlessSteel')]])
// crafting.removeByOutput(item('mob_grinding_utils:fan_upgrade', 1))
// crafting.removeByOutput(item('mob_grinding_utils:fan_upgrade'))
// crafting.addShaped(item('mob_grinding_utils:fan_upgrade', 1), [[ore('plateIron'), ore('craftingFeather,feather'), ore('plateIron')], [null, ore('rotorSteel'), null], [ore('plateIron'), ore('craftingFeather,feather'), ore('plateIron')]])
// crafting.addShaped(item('mob_grinding_utils:fan_upgrade'), [[ore('plateIron'), null, ore('plateIron')], [ore('craftingFeather,feather'), ore('rotorSteel'), ore('craftingFeather,feather')], [ore('plateIron'), null, ore('plateIron')]])
// crafting.addShaped(item('mob_grinding_utils:fan_upgrade', 2), [[ore('plateIron'), ore('craftingFeather,feather'), ore('plateIron')], [ore('craftingFeather,feather'), ore('rotorSteel'), ore('craftingFeather,feather')], [ore('plateIron'), ore('craftingFeather,feather'), ore('plateIron')]])
// crafting.removeByOutput(item('mob_grinding_utils:saw_upgrade', 4))
// crafting.removeByOutput(item('mob_grinding_utils:saw_upgrade', 3))
// crafting.removeByOutput(item('mob_grinding_utils:saw_upgrade'))
// crafting.removeByOutput(item('mob_grinding_utils:fan_upgrade', 2))
// crafting.removeByOutput(item('mob_grinding_utils:saw_upgrade', 2))
// crafting.addShaped(item('mob_grinding_utils:saw_upgrade', 4), [[ore('plateGold'), item('minecraft:spider_eye'), ore('plateGold')], [item('minecraft:spider_eye'), ore('plateRedstone'), item('minecraft:spider_eye')], [ore('plateGold'), item('minecraft:spider_eye'), ore('plateGold')]])
// crafting.addShaped(item('mob_grinding_utils:saw_upgrade', 3), [[ore('plateGold'), item('minecraft:rotten_flesh'), ore('plateGold')], [item('minecraft:rotten_flesh'), ore('plateRedstone'), item('minecraft:rotten_flesh')], [ore('plateGold'), item('minecraft:rotten_flesh'), ore('plateGold')]])
// crafting.addShaped(item('mob_grinding_utils:saw_upgrade', 2), [[ore('plateGold'), ore('dustBlaze,itemBlazePowder'), ore('plateGold')], [ore('dustBlaze,itemBlazePowder'), ore('plateRedstone'), ore('dustBlaze,itemBlazePowder')], [ore('plateGold'), ore('dustBlaze,itemBlazePowder'), ore('plateGold')]])
// crafting.addShaped(item('mob_grinding_utils:saw_upgrade'), [[ore('plateGold'), item('gregtech:meta_item_2', 33), ore('plateGold')], [item('gregtech:meta_item_2', 33), ore('plateRedstone'), item('gregtech:meta_item_2', 33)], [ore('plateGold'), item('gregtech:meta_item_2', 33), ore('plateGold')]])
// //break two

// LATHE.recipeBuilder()
//         .inputs(ore('screwIron'))
//         .outputs(item('appliedenergistics2:part', 120) * 10)
//         .duration(100)
//         .EUt(16)
//         .buildAndRegister()

// furnace.removeByOutput(ore('ingotSignalum'))
// furnace.removeByOutput(ore('ingotLumium'))
// crafting.addShaped(ore('dustAerotheum'), [[null, ore('dustSulfur'), null], [ore('dustSulfur'), ore('dustBlaze,itemBlazePowder'), ore('dustSulfur')], [null, ore('dustSulfur'), null]])

// /*
// crafting.addShapeless(item('gregtech:metal_casing_grisium'),[item('gtadditions:ga_metal_casing_1', 8)])
// Utils.removeRecipeByOutput(assembler, [item('gregtech:machine:15000')], [], false)

// ASSEMBLER.recipeBuilder()
// .inputs(ore('circuitEv') *2,item('appliedenergistics2:material', 42),item('ae2wtlib:infinity_booster_card'),metaitem('hull.ev'),item('gtadditions:ga_metal_casing_1', 8))
// .outputs(item('gregtech:machine:15000'))
// .EUt(30)
// .duration(2048)
// .buildAndRegister()
// */

// Utils.removeRecipeByOutput(fusion, [], [fluid('rutherfordium')], false)
// Utils.removeRecipeByOutput(fusion, [], [fluid('duranium')], false)
// Utils.removeRecipeByOutput(fusion, [], [fluid('tritanium')], false)
// Utils.removeRecipeByOutput(fusion, [], [fluid('plasma.radon')], false)
// Utils.removeRecipeByOutput(fusion, [], [fluid('dubnium')], false)

// FUSION_REACTOR.recipeBuilder()
//         .fluidInputs(fluid('neon') * 144, fluid('plutonium') * 144)
//         .fluidOutputs(fluid('rutherfordium') * 144)
//         .EUToStart(150000000)
//         .duration(64)
//         .EUt(16384)
//         .buildAndRegister()

// FUSION_REACTOR.recipeBuilder()
//         .fluidInputs(fluid('radon') * 1125, fluid('gallium') * 144)
//         .fluidOutputs(fluid('duranium') * 144)
//         .EUToStart(180000000)
//         .duration(64)
//         .EUt(24576)
//         .buildAndRegister()

// FUSION_REACTOR.recipeBuilder()
//         .fluidInputs(fluid('duranium') * 288, fluid('titanium') * 432)
//         .fluidOutputs(fluid('tritanium') * 144)
//         .EUToStart(200000000)
//         .duration(64)
//         .EUt(32768)
//         .buildAndRegister()

// FUSION_REACTOR.recipeBuilder()
//         .fluidInputs(fluid('mercury') * 64, fluid('gold') * 64)
//         .fluidOutputs(fluid('plasma.radon') * 500)
//         .EUToStart(200000000)
//         .duration(64)
//         .EUt(32768)
//         .buildAndRegister()

// FUSION_REACTOR.recipeBuilder()
//         .fluidInputs(fluid('neon') * 288, fluid('americium') * 288)
//         .fluidOutputs(fluid('dubnium') * 288)
//         .EUToStart(200000000)
//         .duration(64)
//         .EUt(131072)
//         .buildAndRegister()

// FUSION_REACTOR.recipeBuilder()
//         .fluidInputs(fluid('neon') * 288, fluid('americium243') * 288)
//         .fluidOutputs(fluid('dubnium') * 288)
//         .EUToStart(200000000)
//         .duration(64)
//         .EUt(131072)
//         .buildAndRegister()


// //grappling hooks

// crafting.removeByOutput(item('hooked:microcrafting', 2))

// LATHE.recipeBuilder()
//         .inputs(ore('stickIron'))
//         .outputs(item('hooked:microcrafting', 2) * 2)
//         .duration(64)
//         .EUt(30)
//         .buildAndRegister()

// LATHE.recipeBuilder()
//         .inputs(ore('stickSteel'))
//         .outputs(item('hooked:microcrafting', 2) * 4)
//         .duration(64)
//         .EUt(30)
//         .buildAndRegister()

// crafting.removeByOutput(item('hooked:hook', 3))
// crafting.removeByOutput(item('hooked:hook', 2))
// crafting.removeByOutput(item('hooked:hook', 1))
// crafting.addShaped(item('hooked:hook', 3), [[ore('plateRedstone'), ore('plateRedstone'), item('actuallyadditions:block_crystal')], [null, item('hooked:hook', 2), ore('plateRedstone')], [ore('plateRedstone'), null, ore('plateRedstone')]])
// crafting.addShaped(item('hooked:hook', 2), [[null, ore('plateDiamond'), ore('plateDiamond')], [null, item('hooked:hook', 1), ore('plateDiamond')], [ore('plateDiamond'), null, null]])
// crafting.addShaped(item('hooked:hook', 1), [[item('gtadditions:ga_meta_item:1033'), item('gtadditions:ga_meta_item:1033'), item('gregtech:meta_item_2:1033')], [null, item('hooked:microcrafting', 3), item('gtadditions:ga_meta_item:1033')], [item('hooked:microcrafting', 3), null, item('gtadditions:ga_meta_item:1033')]])


// crafting.removeByOutput(item('enderio:item_advanced_item_filter'))
// crafting.addShaped(item('enderio:item_advanced_item_filter'), [[ore('plateRedstone'), ore('plateDiamond'), ore('plateRedstone')], [ore('plateDiamond'), item('enderio:item_basic_item_filter'), ore('plateDiamond')], [ore('plateRedstone'), ore('plateDiamond'), ore('plateRedstone')]])

// EXTRACTOR.recipeBuilder()
//         .inputs(item('actuallyadditions:item_solidified_experience') * 64)
//         .fluidOutputs(fluid('xpjuice') * 10240)
//         .duration(100)
//         .EUt(30)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(item('minecraft:apple') * 8)
//         .outputs(metaitem('plant_ball'))
//         .duration(300)
//         .EUt(2)
//         .buildAndRegister()

// FORGE_HAMMER.recipeBuilder()
//         .inputs(item('advancedrocketry:charcoallog'))
//         .outputs(ore('charcoal,gemCharcoal,itemCharcoal') * 4)
//         .duration(100)
//         .EUt(30)
//         .buildAndRegister()
// crafting.removeByOutput(item('enderio:item_capacitor_stellar'))
// crafting.addShaped(item('enderio:item_capacitor_stellar'), [[ore('plateSterlingSilver'), ore('dustSilverChloride'), ore('plateSterlingSilver')], [item('enderio:item_basic_capacitor', 2), item('minecraft:lapis_block'), item('enderio:item_basic_capacitor', 2)], [ore('plateSterlingSilver'), ore('dustSilverChloride'), ore('plateSterlingSilver')]])

// Utils.removeRecipeByOutput(forming, [item('gcyl:gcyl_meta_item', 230)], [], false)
// crafting.removeByOutput(item('minecraft:end_crystal'))
// recipes.removeShaped(item('minecraft:end_crystal'), [[ore('paneGlassColorless'), ore('paneGlassColorless'), ore('paneGlassColorless')], [ore('paneGlassColorless'), item('gregtech:meta_item_1:32725'), ore('paneGlassColorless')], [ore('paneGlassColorless'), item('gregtech:meta_item_1:32672'), ore('paneGlassColorless')]])

// Utils.removeRecipeByOutput(tower, [], [fluid('argon')], false)

// DISTILLATION_TOWER.recipeBuilder()
//         .fluidInputs(fluid('liquid_air') * 100000)
//         .fluidOutputs(fluid('nitrogen') * 78000, fluid('oxygen') * 20000, fluid('argon') * 1000, fluid('carbon_dioxide') * 500, fluid('neon') * 100, fluid('helium') * 50, fluid('methane') * 20, fluid('krypton') * 10, fluid('hydrogen') * 5, fluid('xenon'))
//         .duration(600)
//         .EUt(510)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(blast_furnace, [ore('ingotHotVanadium')], [], false)

// EBF.recipeBuilder()
//         .inputs(ore('dustVanadium'))
//         .circuitMeta(1)
//         .outputs(ore('ingotHotVanadium'))
//         .blastFurnaceTemp(2183) //this is a minimal temperature at which the item will be smelted
//         .duration(2226)
//         .EUt(120)
//         .buildAndRegister()


// FORMING_PRESS.recipeBuilder()
//         .inputs(ore('ingotSoularium') * 2, ore('itemSkull'), ore('dustSilicon') * 2, ore('ingotVibrantAlloy'))
//         .outputs(ore('skullEnderResonator'))
//         .EUt(16)
//         .duration(150)
//         .buildAndRegister()
// //remove upcraft recipes
// /*
// Utils.removeRecipeByOutput(assembler, [ore('componentDiode') * 16], [], true)
// Utils.removeRecipeByOutput(assembler, [ore('componentCapacitor') * 8], [], true)
// Utils.removeRecipeByOutput(assembler, [ore('componentResistor') * 12], [], true)
// Utils.removeRecipeByOutput(assembler, [ore('componentTransistor') * 16], [], true)
// Utils.removeRecipeByOutput(assembler, [item('gcyl:gcyl_meta_item', 240) * 16], [], true)
// Utils.removeRecipeByOutput(assembler, [item('gcyl:gcyl_meta_item', 241) * 12], [], true)
// Utils.removeRecipeByOutput(assembler, [item('gcyl:gcyl_meta_item', 242) * 8], [], true)
// Utils.removeRecipeByOutput(assembler, [item('gcyl:gcyl_meta_item', 243) * 16], [], true)
// Utils.removeRecipeByOutput(assembler, [item('gcyl:gcyl_meta_item', 244) * 16], [], true)
// Utils.removeRecipeByOutput(assembler, [item('gcyl:gcyl_meta_item', 245) * 12], [], true)
// Utils.removeRecipeByOutput(assembler, [item('gcyl:gcyl_meta_item', 246) * 8], [], true)
// Utils.removeRecipeByOutput(assembler, [item('gcyl:gcyl_meta_item', 247) * 16], [], true)
// Utils.removeRecipeByOutput(assembler, [item('gcyl:gcyl_meta_item', 248) * 16], [], true)
// Utils.removeRecipeByOutput(assembler, [item('gcyl:gcyl_meta_item', 249) * 8], [], true)
// Utils.removeRecipeByOutput(assembler, [item('gcyl:gcyl_meta_item', 250) * 12], [], true)
// Utils.removeRecipeByOutput(assembler, [item('gcyl:gcyl_meta_item', 251) * 16], [], true)
// Utils.removeRecipeByOutput(assembler, [item('gcyl:gcyl_meta_item', 252) * 16], [], true)
// Utils.removeRecipeByOutput(assembler, [item('gcyl:gcyl_meta_item', 253) * 8], [], true)
// Utils.removeRecipeByOutput(assembler, [item('gcyl:gcyl_meta_item', 254) * 12], [], true)
// Utils.removeRecipeByOutput(assembler, [item('gcyl:gcyl_meta_item', 255) * 16], [], true)
// */

// //Fix blood ratio
// Utils.removeRecipeByOutput(centrifuge, [], [fluid('blood') * 250], true)
// Utils.removeRecipeByOutput(large_centrifuge, [], [fluid('blood') * 250], true)

// IMPLOSION_COMPRESSOR.recipeBuilder()
//         .inputs(item('gregtech:meta_item_2:32434'))
//         .explosives(item('gregtech:itnt') * 4)
//         .outputs(item('gregtech:meta_item_2:32435'))
//         .duration(20)
//         .EUt(30)
//         .buildAndRegister()

// IMPLOSION_COMPRESSOR.recipeBuilder()
//         .inputs(ore('dustDiamond') * 4)
//         .explosives(item('gregtech:itnt') * 24)
//         .outputs(ore('gemDiamond') * 3)
//         .duration(20)
//         .EUt(30)
//         .buildAndRegister()


// ELECTROLYZER.findRecipe(30, [item('minecraft:snowball') * 3], null).remove()

// ELECTROLYZER.recipeBuilder()
//         .inputs(item('minecraft:snowball') * 4)
//         .fluidOutputs([fluid('hydrogen') * 2000, fluid('oxygen') * 1000])
//         .duration(1244)
//         .EUt(30)
//         .buildAndRegister()

// crafting.removeByOutput(item('randomthings:spectreenergyinjector'))
// crafting.addShaped(item('randomthings:spectreenergyinjector'), [[item('minecraft:obsidian'), item('randomthings:spectrelens'), item('minecraft:obsidian')], [item('randomthings:ingredient', 12), item('randomthings:spectrecharger'), item('randomthings:ingredient', 12)], [item('minecraft:obsidian'), item('randomthings:ingredient', 12), item('minecraft:obsidian')]])


//  TODO: Nuclear stuff
// //naq

// nuclear_reactor.recipeBuilder()
//         .inputs(ore('stickNaquadah') * 2)
//         .blastFurnaceTemp(1000)
//         .circuitMeta(0)
//         .outputs(ore('stickPlatinum') * 2)
//         .outputs(item('gtadditions:ga_meta_item:32312') * 16)
//         .duration(500)
//         .EUt(30)
//         .buildAndRegister()

// nuclear_breeder.recipeBuilder()
//         .inputs(ore('stickNaquadah') * 2)
//         .inputs(item('gtadditions:ga_meta_item:17075') * 10)
//         .blastFurnaceTemp(1000)
//         .circuitMeta(0)
//         .outputs(ore('stickPlatinum') * 2)
//         .outputs(item('gtadditions:ga_meta_item:32312') * 8)
//         .outputs(item('gtadditions:ga_meta_item:9815') * 10)
//         .outputs(item('gtadditions:ga_meta_item:9819') * 10)
//         .duration(500)
//         .EUt(30)
//         .buildAndRegister()

// //enriched naq

// nuclear_reactor.recipeBuilder()
//         .inputs(ore('stickNaquadahEnriched') * 2)
//         .blastFurnaceTemp(1000)
//         .circuitMeta(0)
//         .outputs(ore('stickNaquadah') * 2)
//         .outputs(item('gtadditions:ga_meta_item:32312') * 16)
//         .duration(500)
//         .EUt(30)
//         .buildAndRegister()

// nuclear_breeder.recipeBuilder()
//         .inputs(ore('stickNaquadahEnriched') * 2)
//         .inputs(item('gtadditions:ga_meta_item:16053') * 10)
//         .blastFurnaceTemp(1000)
//         .circuitMeta(0)
//         .outputs(ore('stickNaquadah') * 2)
//         .outputs(item('gtadditions:ga_meta_item:32312') * 8)
//         .outputs(item('gtadditions:ga_meta_item:11809') * 10)
//         .outputs(item('gtadditions:ga_meta_item:11053') * 10)
//         .duration(500)
//         .EUt(30)
//         .buildAndRegister()

// //naqudria

// nuclear_reactor.recipeBuilder()
//         .inputs(ore('stickNaquadria') * 2)
//         .blastFurnaceTemp(1000)
//         .circuitMeta(0)
//         .outputs(ore('stickNaquadahEnriched') * 2)
//         .outputs(item('gtadditions:ga_meta_item:32312') * 16)
//         .duration(500)
//         .EUt(30)
//         .buildAndRegister()

// nuclear_breeder.recipeBuilder()
//         .inputs(ore('stickNaquadria') * 2)
//         .inputs(item('gtadditions:ga_meta_item:16809') * 10)
//         .blastFurnaceTemp(1000)
//         .circuitMeta(0)
//         .outputs(ore('stickNaquadahEnriched') * 2)
//         .outputs(item('gtadditions:ga_meta_item:32312') * 8)
//         .outputs(item('gtadditions:ga_meta_item:11799') * 10)
//         .outputs(item('gtadditions:ga_meta_item:9804') * 10)
//         .duration(500)
//         .EUt(30)
//         .buildAndRegister()

// //awaken draconium

// nuclear_reactor.recipeBuilder()
//         .inputs(ore('stickAwakenDraconium') * 2)
//         .blastFurnaceTemp(1000)
//         .circuitMeta(0)
//         .outputs(ore('stickDraconium') * 2)
//         .outputs(item('gtadditions:ga_meta_item:32312') * 30)
//         .duration(500)
//         .EUt(30)
//         .buildAndRegister()

// nuclear_breeder.recipeBuilder()
//         .inputs(ore('stickAwakenDraconium') * 2)
//         .inputs(item('gtadditions:ga_meta_item:17795') * 10)
//         .blastFurnaceTemp(1000)
//         .circuitMeta(0)
//         .outputs(ore('stickDraconium') * 2)
//         .outputs(item('gtadditions:ga_meta_item:32312') * 16)
//         .outputs(item('gtadditions:ga_meta_item:11789') * 10)
//         .outputs(item('gtadditions:ga_meta_item:9793') * 10)
//         .duration(500)
//         .EUt(30)
//         .buildAndRegister()

// //refined chaos

// nuclear_reactor.recipeBuilder()
//         .inputs(item('gregtech:meta_item_1:14520') * 2)
//         .blastFurnaceTemp(1000)
//         .circuitMeta(0)
//         .outputs(ore('stickAwakenDraconium') * 2)
//         .outputs(item('gtadditions:ga_meta_item:32312') * 32)
//         .duration(500)
//         .EUt(30)
//         .buildAndRegister()

// nuclear_breeder.recipeBuilder()
//         .inputs(item('gregtech:meta_item_1:14520') * 2)
//         .inputs(item('gtadditions:ga_meta_item:17784') * 10)
//         .blastFurnaceTemp(1000)
//         .circuitMeta(0)
//         .outputs(ore('stickAwakenDraconium') * 2)
//         .outputs(item('gtadditions:ga_meta_item:32312') * 16)
//         .outputs(item('gtadditions:ga_meta_item:11778') * 10)
//         .outputs(item('gtadditions:ga_meta_item:11783') * 10)
//         .duration(500)
//         .EUt(30)
//         .buildAndRegister()


// crafting.removeByOutput(item('gregtech:machine', 793))
// crafting.removeByOutput(item('gregtech:machine', 792))
// crafting.removeByOutput(item('gregtech:machine', 791))
// crafting.removeByOutput(item('gregtech:machine', 790))
// //crafting.removeByOutput(item('gregtech:machine', 819))

// crafting.addShaped(item('gregtech:machine', 793), [[null, null, null], [null, item('gregtech:mte', 994), null], [null, item('minecraft:glass'), null]])
// crafting.addShaped(item('gregtech:machine', 792), [[null, item('minecraft:glass'), null], [null, item('gregtech:mte', 994), null], [null, null, null]])
// crafting.addShaped(item('gregtech:machine', 791), [[null, null, null], [null, item('gregtech:mte', 994), null], [null, ore('chest,chestWood'), null]])
// crafting.addShaped(item('gregtech:machine', 790), [[null, ore('chest,chestWood'), null], [null, item('gregtech:mte', 994), null], [null, null, null]])
// //crafting.addShaped(item('gregtech:machine', 819), [[ore('wireGtHexDuranium'), item('gregtech:mte', 994), ore('wireGtHexDuranium')],[ore('wireGtHexDuranium'), ore('gearHsss'), ore('wireGtHexDuranium')], [ore('wireGtHexDuranium'), ore('wireGtHexDuranium'), ore('wireGtHexDuranium')]])


// ADV_FUSION.recipeBuilder()
//         .fluidInputs(fluid('sodium') * 144, fluid('curium250') * 144)
//         .fluidOutputs(fluid('bohrium') * 288)
//         .EUToStart(1000000000)
//         .AdvCoilTier(1)
//         .EUReturn(40)
//         .duration(50)
//         .EUt(1000000)
//         .buildAndRegister()

// crafting.addShaped(ore('darkFusedQuartz') * 8, [[ore('blockGlassHardened'), ore('blockGlassHardened'), ore('blockGlassHardened')], [ore('blockGlassHardened'), ore('dyeBlack'), ore('blockGlassHardened')], [ore('blockGlassHardened'), ore('blockGlassHardened'), ore('blockGlassHardened')]])
// crafting.addShaped(ore('notHolyEnlightenedFusedQuartz') * 8, [[ore('blockGlassHardened'), ore('blockGlassHardened'), ore('blockGlassHardened')], [ore('blockGlassHardened'), item('astralsorcery:itemusabledust'), ore('blockGlassHardened')], [ore('blockGlassHardened'), ore('blockGlassHardened'), ore('blockGlassHardened')]])
// crafting.addShaped(ore('darkFusedQuartz') * 8, [[ore('blockGlassHardened'), ore('blockGlassHardened'), ore('blockGlassHardened')], [ore('blockGlassHardened'), item('astralsorcery:itemusabledust', 1), ore('blockGlassHardened')], [ore('blockGlassHardened'), ore('blockGlassHardened'), ore('blockGlassHardened')]])
// crafting.addShaped(ore('notHolyEnlightenedFusedQuartz') * 8, [[ore('blockGlassHardened'), ore('blockGlassHardened'), ore('blockGlassHardened')], [ore('blockGlassHardened'), ore('dustGlowstone'), ore('blockGlassHardened')], [ore('blockGlassHardened'), ore('blockGlassHardened'), ore('blockGlassHardened')]])
// crafting.addShaped(ore('dustWheat').withNbt({ entityId: "minecraft:pig" }), [[ore('dustSoularium'), ore('dyeSoulMachine'), ore('dustSoularium')], [ore('dyeSoulMachine'), ore('itemSoulMachineChassi'), ore('dyeSoulMachine')], [ore('dustSoularium'), ore('dyeSoulMachine'), ore('dustSoularium')]])

// Utils.removeRecipeByOutput(mixer, [ore('dustSterlingSilver')], [], false)

// MIXER.recipeBuilder()
//         .inputs(ore('dustCopper'))
//         .inputs(ore('dustSilver') * 4)
//         .circuitMeta(2)
//         .outputs(ore('dustSterlingSilver') * 5)
//         .duration(20)
//         .EUt(8)
//         .buildAndRegister()

// extruder.recipeBuilder()
//         .inputs(ore('ingotSignalum') * 4)
//         .notConsumable(item('gregtech:meta_item_1', 52))
//         .outputs(ore('gearSignalum'))
//         .duration(380)
//         .EUt(30)
//         .buildAndRegister()

// furnace.removeByOutput(item('gregtech:meta_item_1:2518'))

// Utils.removeRecipeByOutput(fluid_extractor, [], [fluid('pyrotheum') * 250], true)

// EXTRACTOR.recipeBuilder()
//         .inputs(ore('dustPyrotheum'))
//         .fluidOutputs(fluid('pyrotheum') * 1000)
//         .EUt(24)
//         .duration(35)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(fluid_extractor, [], [fluid('cryotheum') * 250], true)

// EXTRACTOR.recipeBuilder()
//         .inputs(ore('dustCryotheum'))
//         .fluidOutputs(fluid('cryotheum') * 1000)
//         .EUt(24)
//         .duration(35)
//         .buildAndRegister()

// ELECTROLYZER.recipeBuilder()
//         .inputs(ore('dustDiamond'))
//         .outputs(ore('dustCarbon,dyeBlack') * 64)
//         .duration(608)
//         .EUt(30)
//         .buildAndRegister()

// //Diamond upcraft
// engraver.recipeBuilder()
//         .inputs(ore('gemDiamond') * 4)
//         .notConsumable(ore('craftingLensWhite'))
//         .outputs(ore('gemFlawlessDiamond'))
//         .duration(2400)
//         .EUt(2000)
//         .buildAndRegister()

// engraver.recipeBuilder()
//         .inputs(ore('gemFlawlessDiamond') * 4)
//         .notConsumable(ore('craftingLensWhite'))
//         .outputs(ore('gemExquisiteDiamond'))
//         .duration(2400)
//         .EUt(2000)
//         .buildAndRegister()

// large_engrav.recipeBuilder()
//         .inputs(ore('gemDiamond') * 4)
//         .notConsumable(ore('craftingLensWhite'))
//         .outputs(ore('gemFlawlessDiamond'))
//         .duration(2400)
//         .EUt(2000)
//         .buildAndRegister()

// large_engrav.recipeBuilder()
//         .inputs(ore('gemFlawlessDiamond') * 4)
//         .notConsumable(ore('craftingLensWhite'))
//         .outputs(ore('gemExquisiteDiamond'))
//         .duration(2400)
//         .EUt(2000)
//         .buildAndRegister()


// furnace.removeByOutput(ore('ingotDuranium'))
// furnace.removeByOutput(ore('ingotRutherfordium'))
// furnace.removeByOutput(ore('ingotTritanium'))


// EBF.recipeBuilder()
//         .inputs(ore('dustRutherfordium'))
//         .outputs(ore('ingotRutherfordium'))
//         .blastFurnaceTemp(5400) //this is a minimal temperature at which the item will be smelted
//         .duration(16560)
//         .EUt(120)
//         .buildAndRegister()

// EBF.recipeBuilder()
//         .inputs(ore('dustTritanium'))
//         .outputs(ore('ingotTritanium'))
//         .blastFurnaceTemp(11000) //this is a minimal temperature at which the item will be smelted
//         .duration(16560)
//         .EUt(120)
//         .buildAndRegister()


// EBF.recipeBuilder()
//         .inputs(ore('dustDuranium'))
//         .outputs(ore('ingotDuranium'))
//         .blastFurnaceTemp(6000) //this is a minimal temperature at which the item will be smelted
//         .duration(16560)
//         .EUt(120)
//         .buildAndRegister()

// furnace.removeByOutput(item('gregtech:meta_item_1:10518'))
// furnace.removeByOutput(ore('ingotNaquadria'))

// crafting.removeByOutput(item('gregtech:machine:3208'))
// crafting.removeByOutput(item('gregtech:machine:3209'))
// crafting.removeByOutput(item('gregtech:machine:3210'))
// crafting.removeByOutput(item('gregtech:machine', 817))
// crafting.removeByOutput(item('gregtech:machine', 818))
// crafting.removeByOutput(item('gregtech:machine', 819))

// crafting.addShaped(item('gregtech:machine', 819), [[item('gregtech:meta_item_2:17850'), ore('gearHsss'), item('gregtech:meta_item_2:17850')], [ore('gearHsss'), item('gregtech:mte', 994), ore('gearHsss')], [item('gregtech:meta_item_2:17850'), ore('gearHsss'), item('gregtech:meta_item_2:17850')]])
// crafting.addShaped(item('gregtech:machine:3210'), [[item('gregtech:meta_item_2:17850'), ore('gearSeaborgium'), item('gregtech:meta_item_2:17850')], [ore('gearSeaborgium'), item('gregtech:mte', 994), ore('gearSeaborgium')], [item('gregtech:meta_item_2:17850'), ore('gearSeaborgium'), item('gregtech:meta_item_2:17850')]])
// crafting.addShaped(item('gregtech:machine', 818), [[ore('gearSmallTungstenSteel'), item('gregtech:meta_item_2:26016'), ore('gearSmallTungstenSteel')], [item('gregtech:meta_item_2:26016'), item('gregtech:mte', 991), item('gregtech:meta_item_2:26016')], [ore('gearSmallTungstenSteel'), item('gregtech:meta_item_2:26016'), ore('gearSmallTungstenSteel')]])
// crafting.addShaped(item('gregtech:machine:3209'), [[ore('gearSmallTungstenSteel'), ore('gearRhodiumPlatedPalladium'), ore('gearSmallTungstenSteel')], [ore('gearRhodiumPlatedPalladium'), item('gregtech:mte', 991), ore('gearRhodiumPlatedPalladium')], [ore('gearSmallTungstenSteel'), ore('gearRhodiumPlatedPalladium'), ore('gearSmallTungstenSteel')]])
// crafting.addShaped(item('gregtech:machine', 817), [[ore('gearSmallAluminium'), ore('gearStainlessSteel'), ore('gearSmallAluminium')], [ore('gearStainlessSteel'), metaitem('hull.hv'), ore('gearStainlessSteel')], [ore('gearSmallAluminium'), ore('gearStainlessSteel'), ore('gearSmallAluminium')]])
// crafting.addShaped(item('gregtech:machine:3208'), [[ore('gearSmallAluminium'), ore('gearBlackSteel'), ore('gearSmallAluminium')], [ore('gearBlackSteel'), metaitem('hull.hv'), ore('gearBlackSteel')], [ore('gearSmallAluminium'), ore('gearBlackSteel'), ore('gearSmallAluminium')]])

// crafting.removeByOutput(item('enderio:item_big_item_filter'))
// crafting.addShaped(item('enderio:item_big_item_filter'), [[ore('plateAluminium'), ore('plateRedstone'), ore('plateAluminium')], [ore('plateRedstone'), item('enderio:item_basic_item_filter'), ore('plateRedstone')], [ore('plateAluminium'), ore('plateRedstone'), ore('plateAluminium')]])

// crafting.addShaped(item('draconicevolution:grinder'), [[ore('plateNaquadahAlloy'), item('gregtech:meta_item_2', 47), ore('plateNaquadahAlloy')], [item('gregtech:meta_item_2', 47), item('gregtech:mte', 990), item('gregtech:meta_item_1', 206)], [ore('plateNaquadahAlloy'), item('gregtech:meta_item_2', 47), ore('plateNaquadahAlloy')]])

// Utils.removeRecipeByOutput(mixer, [ore('dustNichrome') * 5], [], true)

// MIXER.recipeBuilder()
//         .inputs(ore('dustNickel') * 4)
//         .inputs(ore('dustChrome'))
//         .outputs(ore('dustNichrome') * 5)
//         .circuitMeta(11)
//         .duration(280)
//         .EUt(30)
//         .buildAndRegister()


// Utils.removeRecipeByOutput(arc, [ore('ingotQcdConfinedMatter')], [], false)
// Utils.removeRecipeByOutput(parc, [ore('ingotQcdConfinedMatter')], [], false)
// Utils.removeRecipeByOutput(fluid_extractor, [], [fluid('qcd_confined_matter')], false)
// Utils.removeRecipeByOutput(assembler, [item('gcyl:gcyl_meta_item', 566)], [], true)

// ASSEMBLER.recipeBuilder()
//         .inputs(ore('plateCosmicNeutronium') * 3)
//         .inputs(ore('plateFullerenePolymerMatrix') * 3)
//         .inputs(item('gregtech:meta_item_1:12520') * 3)
//         .outputs(item('gcyl:gcyl_meta_item', 566))
//         .fluidInputs(fluid('neutronium_doped_nanotubes') * 2000)
//         .duration(280)
//         .EUt(536870000)
//         .buildAndRegister()


// crafting.addShaped("clay1", ore('blockClay').firstItem * 8, [[ore('sand'), ore('sand'), ore('sand')], [ore('sand'), fluid('water') * 1000, ore('sand')], [ore('sand'), ore('sand'), ore('sand')]])


// MIXER.recipeBuilder()
//         .inputs(ore('sand') * 8)
//         .circuitMeta(0)
//         .outputs(ore('blockClay,oreClay') * 8)
//         .fluidInputs(fluid('water') * 1000)
//         .duration(100)
//         .EUt(30)
//         .buildAndRegister()

// LARGE_MIXER.recipeBuilder()
//         .inputs(ore('sand') * 8)
//         .circuitMeta(0)
//         .outputs(ore('blockClay,oreClay') * 8)
//         .fluidInputs(fluid('water') * 1000)
//         .duration(100)
//         .EUt(30)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(assembly_line, [item('gcyl:gcyl_meta_item', 500) * 6], [], true)


// assembly_line.recipeBuilder()
//         .inputs(ore('plateProtoAdamantium') * 4)
//         .inputs(item('gcyl:gcyl_meta_item', 495) * 2)
//         .inputs(item('gcyl:gcyl_meta_item', 496) * 2)
//         .inputs(item('gcyl:gcyl_meta_item', 497) * 2)
//         .inputs(item('gcyl:gcyl_meta_item', 494) * 2)
//         .inputs(ore('foilPolyetheretherketone') * 2)
//         .inputs(item('gcyl:gcyl_meta_item', 491) * 2)
//         .inputs(item('gcyl:gcyl_meta_item', 438) * 2)
//         .inputs(item('gcyl:gcyl_meta_item', 488))
//         .inputs(item('gcyl:gcyl_meta_item', 487))
//         .inputs(item('gcyl:gcyl_meta_item', 486))
//         .inputs(item('gcyl:gcyl_meta_item', 499))
//         .inputs(item('gcyl:gcyl_meta_item', 459))
//         .outputs(item('gcyl:gcyl_meta_item', 500) * 6)
//         .fluidInputs(fluid('polytetrafluoroethylene') * 864, fluid('enriched_naquadah_alloy') * 432, fluid('soldering_alloy') * 1296, fluid('fullerene_doped_nanotubes') * 144)
//         .duration(100)
//         .EUt(1474560)
//         .buildAndRegister()

// crafting.addShaped(item('contenttweaker:steampiston'), [[ore('gearSmallIron'), ore('stickWood'), ore('stickWood')], [ore('gearSmallIron'), metaitem('tjceu:steam.motor.ulv'), ore('plateBronze')], [ore('plateIron'), ore('plateIron'), ore('plateIron')]])

// var MAXcompblocks = [item('gtadditions:ga_conveyor_casing', 13), item('gtadditions:ga_field_gen_casing', 13), item('gtadditions:ga_motor_casing', 13), item('gtadditions:ga_piston_casing', 13), item('gtadditions:ga_pump_casing', 13), item('gtadditions:ga_robot_arm_casing', 13), item('gtadditions:ga_sensor_casing', 13), item('gtadditions:ga_emitter_casing', 13)] as IItemStack[]
// var Maxcomp = [item('gcyl:gcyl_meta_item', 353), item('gcyl:gcyl_meta_item', 383), item('gcyl:gcyl_meta_item', 359), item('gcyl:gcyl_meta_item', 365), item('gcyl:gcyl_meta_item', 371), item('gcyl:gcyl_meta_item', 389), item('gcyl:gcyl_meta_item', 395), item('gcyl:gcyl_meta_item', 377)] as IItemStack[]

// for
// i in 0 to 8 {

//     Utils.removeRecipeByOutput(assembler, [MAXcompblocks[i]], [], true)

//     ASSEMBLER.recipeBuilder()
//             .inputs([ore('cableGtSingleCosmicNeutronium') * 8, item('gregtech:machine', 509), Maxcomp[i] * 2])
//             .outputs(MAXcompblocks[i])
//             .fluidInputs(fluid('soldering_alloy') * 288)
//             .duration(100)
//             .EUt(536870900)
//             .buildAndRegister()
// }


// assembly_line.recipeBuilder()
//         .inputs(item('gregtech:cable:2354') * 64)
//         .inputs(item('gtadditions:ga_dust', 55) * 64)
//         .inputs(item('gtadditions:ga_cell_casing', 11))
//         .inputs(ore('boltCosmicNeutronium') * 16)
//         .inputs(ore('plateDenseChaosalloy') * 8)
//         .inputs(ore('circuitMax'))
//         .inputs(item('gcyl:gcyl_meta_item', 377))
//         .inputs(item('gcyl:gcyl_meta_item', 395))
//         .outputs(item('gregtech:meta_item_2:32715'))
//         .fluidInputs(fluid('cosmic_mesh_plasma') * 1000, fluid('quantum') * 1296)
//         .duration(100)
//         .property("qubit", 16)
//         .EUt(983040000)
//         .buildAndRegister()


// ASSEMBLER.recipeBuilder()
//         .inputs(item('gtadditions:ga_cell_casing', 10))
//         .inputs(item('gtadditions:ga_meta_item:1521') * 4)
//         .outputs(item('gtadditions:ga_cell_casing', 11))
//         .fluidInputs(fluid('qcd_confined_matter') * 4000)
//         .duration(1200)
//         .EUt(536870900)
//         .buildAndRegister()

// ASSEMBLER.recipeBuilder()
//         .inputs(item('gtadditions:ga_cell_casing', 9))
//         .inputs(ore('plateDenseHeavyQuarkDegenerateMatter') * 4)
//         .outputs(item('gtadditions:ga_cell_casing', 10))
//         .fluidInputs(fluid('degenerate_rhenium_plasma') * 4000)
//         .duration(1200)
//         .EUt(536870900)
//         .buildAndRegister()

// //max componets
// //motor
// assembly_line.recipeBuilder()
//         .inputs(ore('stickLongNaquadriaticTaranium') * 64)
//         .inputs(ore('stickLongNaquadriaticTaranium') * 64)
//         .inputs(ore('wireFineHeavyQuarkDegenerateMatter') * 64)
//         .inputs(ore('wireFineHeavyQuarkDegenerateMatter') * 64)
//         .inputs(ore('wireFineHeavyQuarkDegenerateMatter') * 64)
//         .inputs(ore('wireFineHeavyQuarkDegenerateMatter') * 64)
//         .inputs(ore('stickLongCosmicNeutronium') * 2)
//         .inputs(ore('ringCosmicNeutronium') * 4)
//         .inputs(ore('roundCosmicNeutronium') * 16)
//         .inputs(ore('cableGtHexCosmicNeutronium') * 2)
//         .inputs(metaitem('gcyl:cosmic.fabric') * 8)
//         .notConsumable(item('gcyl:gcyl_meta_item', 518))
//         .outputs(item('gcyl:gcyl_meta_item', 359))
//         .fluidInputs(fluid('lubricant') * 3000, fluid('soldering_alloy') * 1728)
//         .duration(600)
//         .EUt(536870900)
//         .buildAndRegister()
// //pistin
// assembly_line.recipeBuilder()
//         .inputs(ore('plateQcdConfinedMatter') * 8)
//         .inputs(ore('gearSmallCosmicNeutronium') * 8)
//         .inputs(ore('stickQcdConfinedMatter') * 4)
//         .inputs(ore('ingotCosmicNeutronium') * 2)
//         .inputs(item('gcyl:gcyl_meta_item', 359))
//         .inputs(ore('cableGtQuadrupleCosmicNeutronium') * 2)
//         .notConsumable(item('gcyl:gcyl_meta_item', 518))
//         .outputs(item('gcyl:gcyl_meta_item', 365))
//         .fluidInputs(fluid('lubricant') * 2000, fluid('soldering_alloy') * 576)
//         .duration(600)
//         .EUt(536870900)
//         .buildAndRegister()
// //convar
// assembly_line.recipeBuilder()
//         .inputs(ore('cableGtQuadrupleCosmicNeutronium') * 2)
//         .inputs(item('gcyl:gcyl_meta_item', 359) * 2)
//         .inputs(ore('gearCosmicNeutronium') * 4)
//         .inputs(ore('stickQcdConfinedMatter') * 4)
//         .inputs(ore('plateQcdConfinedMatter') * 8)
//         .inputs(ore('ingotQcdConfinedMatter'))
//         .notConsumable(item('gcyl:gcyl_meta_item', 518))
//         .outputs(item('gcyl:gcyl_meta_item', 353))
//         .fluidInputs(fluid('lubricant') * 5000, fluid('zylon') * 1440)
//         .duration(600)
//         .EUt(536870900)
//         .buildAndRegister()
// //pump
// assembly_line.recipeBuilder()
//         .inputs(item('gcyl:gcyl_meta_item', 359))
//         .inputs(ore('cableGtQuadrupleCosmicNeutronium') * 2)
//         .inputs(ore('ringSiliconeRubber') * 16)
//         .inputs(ore('screwCosmicNeutronium') * 8)
//         .inputs(ore('rotorCosmicNeutronium') * 2)
//         .notConsumable(item('gcyl:gcyl_meta_item', 518))
//         .outputs(item('gcyl:gcyl_meta_item', 371))
//         .fluidInputs(fluid('lubricant') * 2000, fluid('soldering_alloy') * 576)
//         .duration(600)
//         .EUt(536870900)
//         .buildAndRegister()
// //emitter
// assembly_line.recipeBuilder()
//         .inputs(ore('circuitMax') * 2)
//         .inputs(item('gtadditions:ga_dust', 384) * 64)
//         .inputs(item('gcyl:gcyl_meta_item', 555))
//         .inputs(item('gcyl:gcyl_meta_item', 516))
//         .inputs(ore('stickLongMendelevium') * 64)
//         .inputs(item('gcyl:gcyl_meta_item', 561) * 2)
//         .inputs(ore('cableGtSingleCosmicNeutronium') * 8)
//         .inputs(item('gregtech:meta_item_1:19520') * 64)
//         .inputs(ore('frameGtCosmicNeutronium'))
//         .outputs(item('gcyl:gcyl_meta_item', 377))
//         .fluidInputs(fluid('soldering_alloy') * 864)
//         .duration(600)
//         .EUt(536870900)
//         .buildAndRegister()

// //field generator
// assembly_line.recipeBuilder()
//         .inputs(item('gregtech:meta_item_2:16520') * 64)
//         .inputs(item('gregtech:meta_item_2:16520') * 64)
//         .inputs(ore('cableGtSingleCosmicNeutronium') * 4)
//         .inputs(ore('frameGtChaos'))
//         .inputs(item('gcyl:gcyl_meta_item', 519))
//         .inputs(ore('boltChaosalloy') * 16)
//         .inputs(metaitem('gcyl:cosmic.mesh') * 4)
//         .inputs(metaitem('gcyl:qcd.protective.plating') * 4)
//         .inputs(item('gregtech:cable', 354) * 4)
//         .inputs(ore('circuitMax'))
//         .outputs(item('gcyl:gcyl_meta_item', 383))
//         .fluidInputs(fluid('soldering_alloy') * 864)
//         .duration(600)
//         .EUt(536870900)
//         .buildAndRegister()
// //arm
// assembly_line.recipeBuilder()
//         .inputs(ore('cableGtDoubleCosmicNeutronium') * 16)
//         .inputs(ore('circuitUxv') * 8)
//         .inputs(item('gcyl:gcyl_meta_item', 359) * 2)
//         .inputs(item('gcyl:gcyl_meta_item', 365))
//         .inputs(ore('ingotCosmicNeutronium'))
//         .inputs(ore('stickQcdConfinedMatter') * 8)
//         .inputs(ore('screwCosmicNeutronium') * 16)
//         .outputs(item('gcyl:gcyl_meta_item', 389))
//         .fluidInputs(fluid('soldering_alloy') * 864, fluid('lubricant') * 864)
//         .duration(600)
//         .EUt(536870900)
//         .buildAndRegister()
// //sensor
// assembly_line.recipeBuilder()
//         .inputs(metaitem('gcyl:cosmic.fabric') * 4)
//         .inputs(ore('circuitMax') * 2)
//         .inputs(ore('cableGtSingleCosmicNeutronium') * 4)
//         .inputs(item('gregtech:meta_item_1:19520') * 64)
//         .inputs(ore('foilFullerenePolymerMatrix') * 64)
//         .inputs(item('gcyl:gcyl_meta_item', 459) * 32)
//         .inputs(item('gcyl:gcyl_meta_item', 516))
//         .inputs(ore('frameGtCosmicNeutronium'))
//         .outputs(item('gcyl:gcyl_meta_item', 395))
//         .fluidInputs(fluid('high_energy_qgp') * 2000)
//         .duration(600)
//         .EUt(536870900)
//         .buildAndRegister()
// //OpV componets


// assembly_line.recipeBuilder()
//         .inputs(ore('stickLongNaquadriaticTaranium') * 2)
//         .inputs(ore('stickLongNaquadriaticTaranium') * 2)
//         .inputs(ore('wireFineMetastableOganesson') * 64)
//         .inputs(ore('wireFineMetastableOganesson') * 64)
//         .inputs(ore('wireFineMetastableOganesson') * 64)
//         .inputs(ore('wireFineMetastableOganesson') * 64)
//         .inputs(ore('roundNeutronium') * 16)
//         .inputs(ore('ringNeutronium') * 4)
//         .inputs(ore('stickLongNeutronium') * 2)
//         .inputs(ore('cableGtQuadrupleNeutronium') * 2)
//         .outputs(item('gregtech:meta_item_1', 138))
//         .fluidInputs(fluid('lubricant') * 3000, fluid('soldering_alloy') * 1728)
//         .duration(600)
//         .EUt(536870900)
//         .buildAndRegister()

// assembly_line.recipeBuilder()
//         .inputs(item('gregtech:meta_item_1', 138))
//         .inputs(ore('ingotNeutronium') * 2)
//         .inputs(ore('stickNeutronium') * 4)
//         .inputs(ore('gearSmallNeutronium') * 8)
//         .inputs(ore('plateNeutronium') * 8)
//         .inputs(ore('cableGtSingleNeutronium') * 2)
//         .outputs(item('gregtech:meta_item_1', 183))
//         .fluidInputs(fluid('lubricant') * 2000, fluid('soldering_alloy') * 576)
//         .duration(600)
//         .EUt(536870900)
//         .buildAndRegister()

// assembly_line.recipeBuilder()
//         .inputs(item('gregtech:meta_item_1', 138) * 2)
//         .inputs(ore('gearNeutronium') * 4)
//         .inputs(ore('stickNeutronium') * 4)
//         .inputs(ore('plateNeutronium') * 8)
//         .inputs(ore('ingotNeutronium') * 2)
//         .inputs(ore('cableGtSingleNeutronium') * 2)
//         .outputs(item('gregtech:meta_item_1', 168))
//         .fluidInputs(fluid('lubricant') * 5000, fluid('zylon') * 1440)
//         .duration(600)
//         .EUt(536870900)
//         .buildAndRegister()


// assembly_line.recipeBuilder()
//         .inputs(item('gregtech:meta_item_1', 138))
//         .inputs(ore('rotorNeutronium') * 2)
//         .inputs(ore('screwNeutronium') * 8)
//         .inputs(ore('ringSiliconeRubber') * 16)
//         .inputs(ore('cableGtSingleNeutronium') * 2)
//         .inputs(item('gregtech:fluid_pipe:3993') * 16)
//         .outputs(item('gregtech:meta_item_1', 153))
//         .fluidInputs(fluid('lubricant') * 2000, fluid('soldering_alloy') * 576)
//         .duration(600)
//         .EUt(536870900)
//         .buildAndRegister()

// assembly_line.recipeBuilder()
//         .inputs(item('gtadditions:ga_dust', 380) * 64)
//         .inputs(ore('circuitOpv') * 2)
//         .inputs(ore('frameGtNeutronium'))
//         .inputs(ore('gemExquisiteJasper') * 2)
//         .inputs(item('gcyl:gcyl_meta_item', 533))
//         .inputs(item('gcyl:gcyl_meta_item', 524) * 4)
//         .inputs(ore('cableGtSingleNeutronium') * 8)
//         .inputs(ore('foilBohrium') * 64)
//         .outputs(item('gregtech:meta_item_1', 228))
//         .fluidInputs(fluid('lubricant') * 2000, fluid('soldering_alloy') * 576)
//         .duration(600)
//         .EUt(536870900)
//         .buildAndRegister()

// assembly_line.recipeBuilder()
//         .inputs(item('gcyl:gcyl_meta_item', 597))
//         .inputs(item('gtadditions:ga_meta_item2', 10))
//         .inputs(ore('wireGtSingleOpvSuperconductor') * 4)
//         .inputs(ore('circuitOpv') * 2)
//         .inputs(item('gcyl:gcyl_meta_item', 511))
//         .inputs(ore('frameGtVibranium'))
//         .inputs(ore('cableGtSingleNeutronium') * 4)
//         .inputs(ore('wireFineVibranium') * 64)
//         .inputs(ore('wireFineVibranium') * 64)
//         .outputs(metaitem('field.generator.opv'))
//         .fluidInputs(fluid('soldering_alloy') * 864)
//         .duration(600)
//         .EUt(536870900)
//         .buildAndRegister()

// assembly_line.recipeBuilder()
//         .inputs(ore('cableGtDoubleNeutronium') * 16)
//         .inputs(ore('circuitUiv') * 8)
//         .inputs(ore('screwNeutronium') * 16)
//         .inputs(ore('stickNeutronium') * 16)
//         .inputs(ore('ingotNeutronium'))
//         .inputs(item('gregtech:meta_item_1', 183))
//         .inputs(item('gregtech:meta_item_1', 138) * 2)
//         .outputs(item('gregtech:meta_item_1', 198))
//         .fluidInputs(fluid('soldering_alloy') * 864, fluid('lubricant') * 864)
//         .duration(600)
//         .EUt(536870900)
//         .buildAndRegister()

// assembly_line.recipeBuilder()
//         .inputs(ore('circuitOpv') * 2)
//         .inputs(ore('cableGtSingleNeutronium') * 8)
//         .inputs(ore('frameGtNeutronium'))
//         .inputs(ore('gemExquisiteJasper') * 2)
//         .inputs(item('gcyl:gcyl_meta_item', 459) * 16)
//         .inputs(ore('foilMetastableOganesson') * 64)
//         .inputs(ore('foilFullerenePolymerMatrix') * 64)
//         .outputs(item('gregtech:meta_item_1', 243))
//         .fluidInputs(fluid('quark_gluon_plasma') * 2000)
//         .duration(600)
//         .EUt(536870900)
//         .buildAndRegister()

// furnace.removeByOutput(ore('ingotBrightSteel'))


// EBF.recipeBuilder()
//         .inputs(ore('dustBrightSteel'))
//         .outputs(ore('ingotBrightSteel'))
//         .blastFurnaceTemp(2900) //this is a minimal temperature at which the item will be smelted
//         .duration(1200)
//         .EUt(120)
//         .buildAndRegister()

// //solar panels
// crafting.removeByOutput(item('gregtech:meta_item_1:32752'))
// crafting.addShaped(item('gregtech:meta_item_2:32714'), [[item('gregtech:meta_item_1', 242), ore('gemExquisiteLeadZirconateTitanate'), item('gregtech:meta_item_1', 242)], [ore('circuitUiv'), item('gregtech:mte', 996), ore('circuitUiv')], [ore('cableGtSingleBlackTitanium'), item('gtadditions:ga_meta_item2', 7), ore('cableGtSingleBlackTitanium')]])
// crafting.addShaped(item('gregtech:meta_item_2:32713'), [[item('gregtech:meta_item_1', 241), ore('gemExquisiteCubicZirconia'), item('gregtech:meta_item_1', 241)], [ore('circuitUev'), item('gregtech:mte', 995), ore('circuitUev')], [ore('cableGtSingleTitanSteel'), item('gtadditions:ga_meta_item2', 4), ore('cableGtSingleTitanSteel')]])
// crafting.addShaped(item('gregtech:meta_item_2:32712'), [[item('gregtech:meta_item_1', 240), ore('gemExquisiteRhodiumSalt'), item('gregtech:meta_item_1', 240)], [ore('circuitInfinite'), item('gregtech:mte', 994), ore('circuitInfinite')], [ore('cableGtSingleAbyssalAlloy'), item('gregtech:meta_item_1:32598'), ore('cableGtSingleAbyssalAlloy')]])
// crafting.addShaped(item('gregtech:meta_item_2:32712'), [[item('gregtech:meta_item_1', 240), ore('gemExquisiteRhodiumSalt'), item('gregtech:meta_item_1', 240)], [ore('circuitInfinite'), item('gregtech:mte', 994), ore('circuitInfinite')], [ore('cableGtSingleAbyssalAlloy'), item('gtadditions:ga_meta_item2', 6), ore('cableGtSingleAbyssalAlloy')]])
// crafting.addShaped(item('gregtech:meta_item_2:32711'), [[item('gregtech:meta_item_1:32697'), ore('gemExquisiteBlueTopaz'), item('gregtech:meta_item_1:32697')], [ore('circuitUv'), item('gregtech:mte', 993), ore('circuitUv')], [ore('cableGtSingleDuranium'), item('gregtech:meta_item_1:32597'), ore('cableGtSingleDuranium')]])
// crafting.addShaped(item('gregtech:meta_item_2:32711'), [[item('gregtech:meta_item_1:32697'), ore('gemExquisiteBlueTopaz'), item('gregtech:meta_item_1:32697')], [ore('circuitUv'), item('gregtech:mte', 993), ore('circuitUv')], [ore('cableGtSingleDuranium'), item('gtadditions:ga_meta_item2', 3), ore('cableGtSingleDuranium')]])
// crafting.addShaped(item('gregtech:meta_item_2:32710'), [[item('gregtech:meta_item_1:32696'), ore('gemExquisiteEmerald'), item('gregtech:meta_item_1:32696')], [ore('circuitZpm'), item('gregtech:mte', 992), ore('circuitZpm')], [ore('cableGtSingleNaquadah'), item('gtadditions:ga_meta_item2', 1), ore('cableGtSingleNaquadah')]])
// crafting.addShaped(item('gregtech:meta_item_2:32710'), [[item('gregtech:meta_item_1:32696'), ore('gemExquisiteEmerald'), item('gregtech:meta_item_1:32696')], [ore('circuitZpm'), item('gregtech:mte', 992), ore('circuitZpm')], [ore('cableGtSingleNaquadah'), ore('lampGtWhite'), ore('cableGtSingleNaquadah')]])
// crafting.addShaped(item('gregtech:meta_item_2:32709'), [[item('gregtech:meta_item_1:32695'), ore('gemExquisiteRuby'), item('gregtech:meta_item_1:32695')], [ore('circuitMaster'), item('gregtech:mte', 991), ore('circuitMaster')], [ore('cableGtSingleYttriumBariumCuprate'), item('gregtech:meta_item_2:32212'), ore('cableGtSingleYttriumBariumCuprate')]])
// crafting.addShaped(item('gregtech:meta_item_2:32709'), [[item('gregtech:meta_item_1:32695'), ore('gemExquisiteRuby'), item('gregtech:meta_item_1:32695')], [ore('circuitMaster'), item('gregtech:mte', 991), ore('circuitMaster')], [ore('cableGtSingleYttriumBariumCuprate'), item('gregtech:meta_item_1:32537'), ore('cableGtSingleYttriumBariumCuprate')]])
// crafting.addShaped(item('gregtech:meta_item_2:32709'), [[item('gregtech:meta_item_1:32695'), ore('gemExquisiteRuby'), item('gregtech:meta_item_1:32695')], [ore('circuitMaster'), item('gregtech:mte', 991), ore('circuitMaster')], [ore('cableGtSingleYttriumBariumCuprate'), item('gregtech:meta_item_1:32539'), ore('cableGtSingleYttriumBariumCuprate')]])
// crafting.addShaped(item('gregtech:meta_item_2:32709'), [[item('gregtech:meta_item_1:32695'), ore('gemExquisiteRuby'), item('gregtech:meta_item_1:32695')], [ore('circuitMaster'), item('gregtech:mte', 991), ore('circuitMaster')], [ore('cableGtSingleYttriumBariumCuprate'), item('gregtech:meta_item_1:32538'), ore('cableGtSingleYttriumBariumCuprate')]])
// crafting.addShaped(item('gregtech:meta_item_2:32708'), [[item('gregtech:meta_item_1', 236), ore('gemExquisiteRuby'), item('gregtech:meta_item_1', 236)], [ore('circuitIv'), item('gregtech:mte', 990), ore('circuitIv')], [ore('cableGtSingleTungsten'), item('gregtech:meta_item_1:32528'), ore('cableGtSingleTungsten')]])
// crafting.addShaped(item('gregtech:meta_item_2:32708'), [[item('gregtech:meta_item_1', 236), ore('gemExquisiteRuby'), item('gregtech:meta_item_1', 236)], [ore('circuitIv'), item('gregtech:mte', 990), ore('circuitIv')], [ore('cableGtSingleTungsten'), item('gregtech:meta_item_1:32527'), ore('cableGtSingleTungsten')]])
// crafting.addShaped(item('gregtech:meta_item_2:32708'), [[item('gregtech:meta_item_1', 236), ore('gemExquisiteRuby'), item('gregtech:meta_item_1', 236)], [ore('circuitIv'), item('gregtech:mte', 990), ore('circuitIv')], [ore('cableGtSingleTungsten'), item('gregtech:meta_item_1:32529'), ore('cableGtSingleTungsten')]])
// crafting.addShaped(item('gregtech:meta_item_1:32752'), [[item('gregtech:meta_item_1:32693'), ore('gemExquisiteDiamond'), item('gregtech:meta_item_1:32693')], [ore('circuitEv'), metaitem('hull.ev'), ore('circuitEv')], [ore('cableGtSingleAluminium'), item('gregtech:meta_item_1:32517'), ore('cableGtSingleAluminium')]])
// crafting.addShaped(item('gregtech:meta_item_1:32752'), [[item('gregtech:meta_item_1:32693'), ore('gemExquisiteDiamond'), item('gregtech:meta_item_1:32693')], [ore('circuitEv'), metaitem('hull.ev'), ore('circuitEv')], [ore('cableGtSingleAluminium'), item('gregtech:meta_item_1:32518'), ore('cableGtSingleAluminium')]])
// crafting.addShaped(item('gregtech:meta_item_1:32752'), [[item('gregtech:meta_item_1:32693'), ore('gemExquisiteDiamond'), item('gregtech:meta_item_1:32693')], [ore('circuitEv'), metaitem('hull.ev'), ore('circuitEv')], [ore('cableGtSingleAluminium'), item('gregtech:meta_item_1:32519'), ore('cableGtSingleAluminium')]])

// //EV/IV motors
// crafting.removeByOutput(item('gregtech:meta_item_1:32604'))
// crafting.removeByOutput(item('gregtech:meta_item_1:32603'))

// crafting.addShaped(item('gregtech:meta_item_1:32604'), [[ore('cableGtSingleTungsten'), ore('wireGtQuadrupleBrightSteel'), ore('stickTungstenSteel')], [ore('wireGtQuadrupleBrightSteel'), ore('stickNeodymiumMagnetic'), ore('wireGtQuadrupleBrightSteel')], [ore('stickTungstenSteel'), ore('wireGtQuadrupleBrightSteel'), ore('cableGtSingleTungsten')]])
// crafting.addShaped(item('gregtech:meta_item_1:32603'), [[ore('cableGtSingleAluminium'), ore('wireGtQuadrupleGold'), ore('stickTitanium')], [ore('wireGtQuadrupleGold'), ore('stickNeodymiumMagnetic'), ore('wireGtQuadrupleGold')], [ore('stickTitanium'), ore('wireGtQuadrupleGold'), ore('cableGtSingleAluminium')]])


// Utils.removeRecipeByOutput(assembler, [item('gregtech:meta_item_1:32603')], [], true)
// Utils.removeRecipeByOutput(assembler, [item('gregtech:meta_item_1:32604')], [], true)

// Utils.removeRecipeByOutput(assembly_line, [item('gregtech:meta_item_1:32603') * 16], [], true)
// Utils.removeRecipeByOutput(assembly_line, [item('gregtech:meta_item_1:32604') * 16], [], true)

// ASSEMBLER.recipeBuilder()
//         .inputs(ore('stickNeodymiumMagnetic'), ore('stickTitanium') * 2, ore('cableGtSingleAluminium') * 2, ore('wireGtQuadrupleGold') * 4)
//         .outputs(item('gregtech:meta_item_1:32603'))
//         .duration(100)
//         .EUt(1920)
//         .buildAndRegister()

// ASSEMBLER.recipeBuilder()
//         .inputs(ore('stickNeodymiumMagnetic'), ore('stickTungstenSteel') * 2, ore('cableGtSingleTungsten') * 2, ore('wireGtQuadrupleBrightSteel') * 4)
//         .outputs(item('gregtech:meta_item_1:32604'))
//         .duration(100)
//         .EUt(7680)
//         .buildAndRegister()

// assembly_line.recipeBuilder()
//         .inputs(item('gtadditions:ga_meta_item:2072') * 16, item('gtadditions:ga_meta_item:2072') * 16, item('gtadditions:ga_meta_item:2072') * 16, item('gtadditions:ga_meta_item:2072') * 16, ore('cableGtSingleAluminium') * 4, ore('cableGtSingleAluminium') * 4, ore('cableGtSingleAluminium') * 4, ore('cableGtSingleAluminium') * 4, ore('stickLongTitanium') * 4, ore('stickLongNeodymiumMagnetic') * 4)
//         .outputs(item('gregtech:meta_item_1:32603') * 16)
//         .fluidInputs(fluid('gold') * 1152)
//         .duration(6000)
//         .EUt(64000)
//         .buildAndRegister()

// assembly_line.recipeBuilder()
//         .inputs(item('gtadditions:ga_meta_item:2235') * 16, item('gtadditions:ga_meta_item:2235') * 16, item('gtadditions:ga_meta_item:2235') * 16, item('gtadditions:ga_meta_item:2235') * 16, ore('cableGtSingleTungsten') * 4, ore('cableGtSingleTungsten') * 4, ore('cableGtSingleTungsten') * 4, ore('cableGtSingleTungsten') * 4, ore('stickLongTungstenSteel') * 4, ore('stickLongNeodymiumMagnetic') * 4)
//         .outputs(item('gregtech:meta_item_1:32604') * 16)
//         .fluidInputs(fluid('bright_steel') * 1152)
//         .duration(6000)
//         .EUt(128000)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(gas_centrifuge, [], [fluid('titanium50_tetrafluoride') * 518, fluid('fluorine') * 9482], true)


// gas_CENTRIFUGE.recipeBuilder()
//         .fluidInputs(fluid('titanium_tetrafluoride') * 10000)
//         .fluidOutputs(fluid('titanium50_tetrafluoride') * 518, fluid('titanium_tetrafluoride') * 9482)
//         .duration(210)
//         .EUt(30720)
//         .buildAndRegister()

// crafting.removeByOutput(item('minecraft:golden_apple', 1))

// MIXER.recipeBuilder()
//         .inputs(ore('dustEuropium'), ore('dustCaesium') * 2, ore('dustSteel') * 4, ore('dustBismuth') * 2)
//         .outputs(ore('dustBrightSteel') * 9)
//         .duration(400)
//         .EUt(16)
//         .buildAndRegister()

// LARGE_MIXER.recipeBuilder()
//         .inputs(ore('dustEuropium'), ore('dustCaesium') * 2, ore('dustSteel') * 4, ore('dustBismuth') * 2)
//         .outputs(ore('dustBrightSteel') * 9)
//         .circuitMeta(4)
//         .duration(400)
//         .EUt(16)
//         .buildAndRegister()

// var removals = [item('gtadditions:ga_machine_casing', 3), item('gregtech:machine_casing', 11)] as IItemStack[]
// for
// i in removals {
//     Utils.removeRecipeByOutput(assembler, [i], [], true)
//     crafting.removeByOutput(i)
// }

// var removals2 = [item('gregtech:mte', 997), item('gregtech:machine:3242'), item('gregtech:mte', 996)] as IItemStack[]
// for
// i in removals2 {
//     crafting.removeByOutput(i)
// }

// Utils.removeRecipeByOutput(assembler, [item('gregtech:machine', 509)], [], true)


// crafting.addShaped(item('gregtech:machine_casing', 14), [[ore('plateNeutronium'), ore('plateNeutronium'), ore('plateNeutronium')], [ore('plateNeutronium'), ore('craftingToolWrench'), ore('plateNeutronium')], [ore('plateNeutronium'), ore('plateNeutronium'), ore('plateNeutronium')]])
// crafting.addShaped(item('gregtech:machine_casing', 12), [[ore('plateHeavyQuarkDegenerateMatter'), ore('plateHeavyQuarkDegenerateMatter'), ore('plateHeavyQuarkDegenerateMatter')], [ore('plateHeavyQuarkDegenerateMatter'), ore('craftingToolWrench'), ore('plateHeavyQuarkDegenerateMatter')], [ore('plateHeavyQuarkDegenerateMatter'), ore('plateHeavyQuarkDegenerateMatter'), ore('plateHeavyQuarkDegenerateMatter')]])
// crafting.addShaped(item('gtadditions:ga_machine_casing', 3), [[ore('plateVibranium'), ore('plateVibranium'), ore('plateVibranium')], [ore('plateVibranium'), ore('craftingToolWrench'), ore('plateVibranium')], [ore('plateVibranium'), ore('plateVibranium'), ore('plateVibranium')]])
// crafting.addShaped(item('gregtech:machine_casing', 11), [[ore('plateAdamantium'), ore('plateAdamantium'), ore('plateAdamantium')], [ore('plateAdamantium'), ore('craftingToolWrench'), ore('plateAdamantium')], [ore('plateAdamantium'), ore('plateAdamantium'), ore('plateAdamantium')]])


// ASSEMBLER.recipeBuilder()
//         .inputs(ore('plateAdamantium') * 8)
//         .circuitMeta(8)
//         .outputs(item('gregtech:machine_casing', 11))
//         .duration(400)
//         .EUt(16)
//         .buildAndRegister()

// ASSEMBLER.recipeBuilder()
//         .inputs(ore('plateVibranium') * 8)
//         .circuitMeta(8)
//         .outputs(item('gtadditions:ga_machine_casing', 3))
//         .duration(400)
//         .EUt(16)
//         .buildAndRegister()

// ASSEMBLER.recipeBuilder()
//         .inputs(ore('plateHeavyQuarkDegenerateMatter') * 8)
//         .circuitMeta(8)
//         .outputs(item('gregtech:machine_casing', 12))
//         .duration(400)
//         .EUt(16)
//         .buildAndRegister()

// ASSEMBLER.recipeBuilder()
//         .inputs(ore('plateNeutronium') * 8)
//         .circuitMeta(8)
//         .outputs(item('gregtech:machine_casing', 14))
//         .duration(400)
//         .EUt(16)
//         .buildAndRegister()

// //OpV
// ASSEMBLER.recipeBuilder()
//         .inputs(item('gregtech:machine_casing', 12), ore('cableGtSingleNeutronium') * 2)
//         .outputs(item('gregtech:mte', 997))
//         .fluidInputs(fluid('fullerene_polymer_matrix') * 288)
//         .duration(400)
//         .EUt(16)
//         .buildAndRegister()
// //MAX
// ASSEMBLER.recipeBuilder()
//         .inputs(item('gregtech:machine_casing', 14), ore('cableGtSingleCosmicNeutronium') * 2)
//         .outputs(item('gregtech:machine', 509))
//         .fluidInputs(fluid('fullerene_polymer_matrix') * 288)
//         .duration(400)
//         .EUt(16)
//         .buildAndRegister()
// //fix cosmic mesh and fabric


// Utils.removeRecipeByOutput(condenser, [metaitem('gcyl:cosmic.fabric')], [], true)
// Utils.removeRecipeByOutput(condenser, [metaitem('gcyl:cosmic.mesh')], [], true)

// //facric
// condenser.recipeBuilder()
//         .inputs(item('gcyl:gcyl_meta_item', 567))
//         .notConsumable(item('gcyl:gcyl_meta_item', 562))
//         .outputs(metaitem('gcyl:cosmic.fabric'), metaitem('gcyl:time.dilation.containment.unit'))
//         .fluidInputs(fluid('xenon') * 500, fluid('superfluid_helium') * 24000)
//         .fluidOutputs(fluid('helium') * 24000)
//         .duration(500)
//         .EUt(10000000)
//         .buildAndRegister()


// //mesh
// condenser.recipeBuilder()
//         .inputs(item('gcyl:gcyl_meta_item', 567))
//         .notConsumable(item('gcyl:gcyl_meta_item', 431))
//         .outputs(metaitem('gcyl:cosmic.mesh'), metaitem('gcyl:time.dilation.containment.unit'))
//         .fluidInputs(fluid('superfluid_helium') * 24000)
//         .fluidOutputs(fluid('helium') * 24000)
//         .duration(500)
//         .EUt(10000000)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(assembler, [item('gcyl:gcyl_meta_item', 552)], [], true)
// Utils.removeRecipeByOutput(assembly_line, [metaitem('gcyl:time.dilation.containment.unit')], [], false)


// ASSEMBLER.recipeBuilder()
//         .inputs(item('gregtech:meta_item_1', 241), metaitem('gcyl:qcd.protective.plating') * 2, item('gcyl:gcyl_meta_item', 511), item('gcyl:gcyl_meta_item', 516))
//         .outputs(item('gcyl:gcyl_meta_item', 552))
//         .fluidInputs(fluid('neutronium') * 144)
//         .duration(600)
//         .EUt(33550000)
//         .buildAndRegister()

// assembly_line.recipeBuilder()
//         .inputs(ore('plateNeutronium') * 4, item('gcyl:gcyl_meta_item', 430) * 4, ore('plateFullerenePolymerMatrix') * 4, ore('plateQuantum') * 4, ore('stickEnrichedNaquadahAlloy') * 3, ore('wireGtSingleUhvSuperconductor') * 2, ore('circuitSuperconductor'))
//         .outputs(metaitem('gcyl:time.dilation.containment.unit') * 4)
//         .fluidInputs(fluid('tritanium') * 144)
//         .duration(100)
//         .EUt(800000)
//         .buildAndRegister()

// item('gregtech:fusion_casing').addTooltip(format.darkRed("blacklisted from working in non-fusion multiblock machines"))
// item('gregtech:fusion_casing', 1).addTooltip(format.darkRed("blacklisted from working in non-fusion multiblock machines"))

// crafting.removeByOutput(item('simplevoidworld:portal'))
// crafting.addShaped(item('simplevoidworld:portal'), [[ore('obsidian'), ore('gemDiamond'), ore('obsidian')], [ore('gemDiamond'), ore('toolPickaxe'), ore('gemDiamond')], [ore('obsidian'), ore('gemDiamond'), ore('obsidian')]])

// ASSEMBLER.recipeBuilder()
//         .inputs(ore('circuitOpv') * 2, ore('gearQcdConfinedMatter') * 4, ore('plateQcdConfinedMatter') * 4, ore('cableGtQuadrupleNeutronium'))
//         .outputs(item('gtadditions:ga_multiblock_casing2', 4))
//         .fluidInputs(fluid('enriched_naquadah_alloy') * 288)
//         .duration(100)
//         .EUt(536870900)
//         .buildAndRegister()

// ASSEMBLER.recipeBuilder()
//         .inputs(ore('circuitMax') * 4, ore('gearNeutronium') * 4, ore('plateNeutronium') * 4, item('gregtech:cable:7521'))
//         .outputs(item('gtadditions:ga_multiblock_casing', 12))
//         .fluidInputs(fluid('chaos') * 288)
//         .duration(100)
//         .EUt(2147483647)
//         .buildAndRegister()

// crafting.removeByOutput(item('ae2stuff:grower'))
// crafting.addShaped(item('ae2stuff:grower'), [[item('minecraft:glass'), ore('rotorTin'), item('minecraft:glass')], [ore('crystalFluix'), item('gregtech:meta_item_1:32600'), ore('crystalFluix')], [ore('cableGtSingleTin'), item('gregtech:mte', 986), ore('cableGtSingleTin')]])

// crafting.removeByOutput(item('gcyl:mte', 17))
// crafting.addShaped(item('gcyl:mte', 17), [[ore('circuitEv'), item('gregtech:fluid_pipe:3235'), ore('circuitEv')], [ore('gearTitanium'), item('gregtech:mte', 188), ore('gearTitanium')], [item('gregtech:meta_item_1:12981'), item('gregtech:meta_item_1:13981'), item('gregtech:meta_item_1:12981')]])


// chemical_bath.recipeBuilder()
//         .inputs(ore('dustRegularBrightSteel') * 2)
//         .outputs(ore('dustAstralStarmetal') * 2)
//         .fluidInputs(fluid('astralsorcery.liquidstarlight') * 1000)
//         .duration(100)
//         .EUt(131072)
//         .buildAndRegister()

// distillery.findRecipe(24, [item('gregtech:meta_item_1:32766').withNbt({ Configuration: 2 })], [fluid('oil_light') * 150]).remove()

// Utils.removeRecipeByOutput(assembler, [item('gregtech:multiblock_casing')], [], false)

// ASSEMBLER.recipeBuilder()
//         .inputs(item('gregtech:metal_casing', 6), ore('rotorTitanium') * 4, item('gregtech:fluid_pipe:2072') * 2)
//         .outputs(item('gregtech:multiblock_casing') * 2)
//         .duration(50)
//         .EUt(16)
//         .buildAndRegister()

// blast_furnace.findRecipe(120, [ore('dustIridium'), ore('dustSalt'), ore('dustSalt')], [fluid('oxygen') * 2000]).remove()


// CHEMICAL_REACTOR.recipeBuilder()
//         .inputs(ore('dustIridium') * 2)
//         .notConsumable(ore('dustSalt'))
//         .outputs(ore('dustBismuthIridiate') * 11)
//         .fluidInputs(fluid('oxygen') * 4000, fluid('hydrogen') * 1000, fluid('bismuth_nitrate_solution') * 2000)
//         .fluidOutputs(fluid('nitrogen_dioxide') * 1000, fluid('nitric_acid') * 5000)
//         .duration(300)
//         .EUt(1920)
//         .buildAndRegister()
// LCR.recipeBuilder()
//         .inputs(ore('dustIridium') * 2)
//         .notConsumable(ore('dustSalt'))
//         .outputs(ore('dustBismuthIridiate') * 11)
//         .fluidInputs(fluid('oxygen') * 4000, fluid('hydrogen') * 1000, fluid('bismuth_nitrate_solution') * 2000)
//         .fluidOutputs(fluid('nitrogen_dioxide') * 1000, fluid('nitric_acid') * 5000)
//         .duration(300)
//         .EUt(1920)
//         .buildAndRegister()

// crafting.removeByOutput(item('randomthings:ingredient', 1))
// crafting.addShaped(item('randomthings:ingredient', 1), [[item('randomthings:stableenderpearl'), ore('foilStainlessSteel'), item('randomthings:stableenderpearl')], [ore('foilStainlessSteel'), ore('itemSkull'), ore('foilStainlessSteel')], [item('randomthings:stableenderpearl'), ore('foilStainlessSteel'), item('randomthings:stableenderpearl')]])

// centrifuge.findRecipe(640, [ore('dustNaquadahEnriched')], []).remove()
// large_centrifuge.findRecipe(640, [ore('dustNaquadahEnriched')], []).remove()

// centrifuge.findRecipe(320, [ore('dustNaquadah')], []).remove()
// large_centrifuge.findRecipe(320, [ore('dustNaquadah')], []).remove()

// Utils.removeRecipeByOutput(blast_furnace, [ore('ingotSilicon')], [], true)
// crafting.addShaped(item('minecraft:name_tag'), [[null, ore('cropFlax,string'), ore('cropFlax,string')], [null, ore('slimeball'), ore('cropFlax,string')], [ore('cropFlax,string'), null, null]])

// ASSEMBLER.recipeBuilder()
//         .inputs(ore('chest,chestWood') * 4)
//         .outputs(item('gregtech:machine', 808) * 4)
//         .circuitMeta(2)
//         .duration(60)
//         .EUt(16)
//         .buildAndRegister()
// crafting.addShaped(item('gregtech:machine:4034'), [[null, null, null], [null, item('gregtech:mte', 997), ore('cableGtSingleNeutronium')], [null, null, null]])
// crafting.addShaped(item('gregtech:machine:4029'), [[null, null, null], [ore('cableGtSingleNeutronium'), item('gregtech:mte', 997), null], [null, null, null]])

// crafting.removeByOutput(item('danknull:dank_null_1'))
// crafting.removeByOutput(item('danknull:dank_null_panel_1'))
// crafting.addShaped(item('danknull:dank_null_1'), [[item('danknull:dank_null_panel_1'), item('danknull:dank_null_panel_1'), item('danknull:dank_null_panel_1')], [item('danknull:dank_null_panel_1'), item('danknull:dank_null_0'), item('danknull:dank_null_panel_1')], [item('danknull:dank_null_panel_1'), item('danknull:dank_null_panel_1'), item('danknull:dank_null_panel_1')]])
// crafting.addShaped(item('danknull:dank_null_panel_1'), [[ore('blockLapis'), ore('blockCoalCoke'), ore('blockLapis')], [ore('blockCoalCoke'), item('gtadditions:ga_transparent_casing', 1), ore('blockCoalCoke')], [ore('blockLapis'), ore('blockCoalCoke'), ore('blockLapis')]])

// LCR.recipeBuilder()
//         .inputs(item('gtadditions:ga_dust', 922) * 4)
//         .fluidInputs(fluid('fuming_nitric_acid') * 2000)
//         .notConsumable(fluid('acetic_anhydride'))
//         .outputs(item('gtadditions:ga_dust', 530))
//         .EUt(1024)
//         .duration(20)
//         .buildAndRegister()


// LCR.recipeBuilder()
//         .inputs(ore('dustTinySodiumHydroxide'))
//         .fluidInputs(fluid('creosote') * 10000, fluid(' ethanol') * 1000)
//         .fluidOutputs(fluid(' bio_diesel') * 10000, fluid(' glycerol') * 1000)
//         .duration(120)
//         .EUt(30)
//         .buildAndRegister()

// LCR.recipeBuilder()
//         .inputs(ore('dustTinySodiumHydroxide'))
//         .fluidInputs(fluid('creosote') * 10000, fluid(' methanol') * 1000)
//         .fluidOutputs(fluid(' bio_diesel') * 10000, fluid(' glycerol') * 1000)
//         .duration(120)
//         .EUt(30)
//         .buildAndRegister()
// //update vacuume tube
// crafting.removeByOutput(ore('circuitUlv'))
// crafting.addShaped(ore('circuitUlv'), [[null, item('gregtech:meta_item_1', 517), null], [null, item('gregtech:meta_item_1:16018'), null], [ore('stickWroughtIron'), null, ore('stickWroughtIron')]])
// crafting.removeByOutput(item('gregtech:meta_item_1', 502))


// CHEMICAL_REACTOR.recipeBuilder()
//         .inputs(ore('wool') * 5)
//         .fluidInputs(fluid('glue') * 144, fluid('plastic') * 144)
//         .outputs(item('gregtech:meta_item_1', 502) * 10)
//         .duration(160)
//         .EUt(14)
//         .buildAndRegister()


// LCR.recipeBuilder()
//         .inputs(ore('wool') * 5)
//         .fluidInputs(fluid('glue') * 144, fluid('plastic') * 144)
//         .outputs(item('gregtech:meta_item_1', 502) * 10)
//         .duration(160)
//         .EUt(14)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(chemreactor, [], [fluid('indium_concentrate')], false)
// Utils.removeRecipeByOutput(large_chem, [], [fluid('indium_concentrate')], false)

// LARGE_MIXER.recipeBuilder()
//         .inputs(ore('sand') * 4)
//         .inputs(ore('gravel') * 4)
//         .circuitMeta(3)
//         .fluidInputs(fluid('water') * 1000)
//         .outputs(ore('itemBinderComposite') * 16)
//         .EUt(500)
//         .duration(80)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(assembler, [item('gregtech:mte', 993)], [], true)

// ASSEMBLER.recipeBuilder()
//         .inputs(ore('cableGtSingleNaquadahAlloy') * 2)
//         .inputs(item('gregtech:machine_casing', 8))
//         .outputs(item('gregtech:mte', 993))
//         .fluidInputs(fluid('polybenzimidazole') * 288)
//         .duration(50)
//         .EUt(16)
//         .buildAndRegister()


// LCR.recipeBuilder()
//         .inputs(item('actuallyadditions:item_misc', 23) * 8)
//         .fluidInputs(fluid('refinedcanolaoil') * 10000)
//         .fluidOutputs(fluid('crystaloil') * 10000)
//         .duration(300)
//         .EUt(16)
//         .buildAndRegister()

// LCR.recipeBuilder()
//         .fluidInputs(fluid('crystaloil') * 5000, fluid(' creosote') * 5000)
//         .fluidOutputs(fluid('empoweredoil') * 10000)
//         .duration(300)
//         .EUt(16)
//         .buildAndRegister()

// LCR.recipeBuilder()
//         .inputs(ore('dustTinySodiumHydroxide'))
//         .fluidInputs(fluid('empoweredoil') * 10000, fluid(' ethanol') * 1000)
//         .fluidOutputs(fluid(' bio_diesel') * 10000, fluid(' glycerol') * 1000)
//         .duration(120)
//         .EUt(30)
//         .buildAndRegister()

// LCR.recipeBuilder()
//         .inputs(ore('dustTinySodiumHydroxide'))
//         .fluidInputs(fluid('empoweredoil') * 10000, fluid(' methanol') * 1000)
//         .fluidOutputs(fluid(' bio_diesel') * 10000, fluid(' glycerol') * 1000)
//         .duration(120)
//         .EUt(30)
//         .buildAndRegister()

// CHEMICAL_REACTOR.recipeBuilder()
//         .inputs(ore('wool') * 5)
//         .fluidInputs(fluid('glue') * 144, fluid('polytetrafluoroethylene') * 144)
//         .outputs(item('gregtech:meta_item_1', 502) * 20)
//         .duration(160)
//         .EUt(116)
//         .buildAndRegister()


// LCR.recipeBuilder()
//         .inputs(ore('wool') * 5)
//         .fluidInputs(fluid('glue') * 144, fluid('polytetrafluoroethylene') * 144)
//         .outputs(item('gregtech:meta_item_1', 502) * 20)
//         .duration(160)
//         .EUt(116)
//         .buildAndRegister()


// CHEMICAL_REACTOR.recipeBuilder()
//         .inputs(ore('wool') * 5)
//         .fluidInputs(fluid('glue') * 144, fluid('polybenzimidazole') * 144)
//         .outputs(item('gregtech:meta_item_1', 502) * 40)
//         .duration(160)
//         .EUt(116)
//         .buildAndRegister()


// LCR.recipeBuilder()
//         .inputs(ore('wool') * 5)
//         .fluidInputs(fluid('glue') * 144, fluid('polybenzimidazole') * 144)
//         .outputs(item('gregtech:meta_item_1', 502) * 40)
//         .duration(160)
//         .EUt(116)
//         .buildAndRegister()

// crafting.addShaped(metaitem('tjceu:blockEternity'), [[metaitem('tjceu:ingotEternity'), metaitem('tjceu:ingotEternity'), metaitem('tjceu:ingotEternity')], [metaitem('tjceu:ingotEternity'), metaitem('tjceu:ingotEternity'), metaitem('tjceu:ingotEternity')], [metaitem('tjceu:ingotEternity'), metaitem('tjceu:ingotEternity'), metaitem('tjceu:ingotEternity')]])
// crafting.addShapeless(metaitem('tjceu:ingotEternity') * 9, [metaitem('tjceu:blockEternity')])

// crafting.addShaped(ore('toolHoe').withNbt({ Unbreakable:
// 1 as long ,
//     RepairCost: 1 ,
//     display:
//     { Name: "Unbreakable Emerald Tipped Diamond Hoe" } }), [[ore('gemEmerald'), ore('gemEmerald'), null], [ore('gemEmerald'), ore('toolHoe'), null], [null, null, null]])
// mods.jei.JEI.addItem(ore('toolHoe').withNbt({ display:
// { Name: "Unbreakable Emerald Tipped Diamond Hoe" } }))

// ABS.recipeBuilder()
//         .inputs(ore('dustSeaborgium') * 4)
//         .inputs(ore('dustBohrium') * 4)
//         .blastFurnaceTemp(11200)
//         .fluidOutputs(fluid('fusion1') * 1152)
//         .duration(160)
//         .EUt(1000000)
//         .buildAndRegister()

// ABS.recipeBuilder()
//         .inputs(ore('dustRutherfordium') * 4)
//         .blastFurnaceTemp(11200)
//         .inputs(ore('dustDubnium') * 4)
//         .fluidOutputs(fluid('fusion2') * 1152)
//         .duration(160)
//         .EUt(1000000)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(blast_alloy, [], [fluid('superheavy_mix') * 4000], false)
// //blast_alloy.findRecipe(25000000, [ore('dustRutherfordium'), ore('dustDubnium'), ore('dustSeaborgium'), ore('dustBohrium'), ])

// ADV_FUSION.recipeBuilder()
//         .fluidInputs(fluid('fusion1') * 288, fluid('fusion2') * 288)//,fluid('lead_bismuth_eutatic') * 7440)
//         .fluidOutputs(fluid('superheavy_mix') * 1000)//, fluid('supercritical_lead_bismuth_eutectic') * 7440)
//         .EUToStart(10000000000)
//         .AdvCoilTier(4)
//         .EUReturn(75)
//         .duration(50)
//         .EUt(4000000)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(assembly_line, [ore('circuitUiv')], [], false)


// assembly_line.recipeBuilder()
//         .inputs(item('gcyl:gcyl_meta_item', 426) * 64)
//         .inputs(item('gcyl:gcyl_meta_item', 603) * 32)
//         .inputs(item('gcyl:gcyl_meta_item', 602) * 32)
//         .inputs(item('gcyl:gcyl_meta_item', 604) * 32)
//         .inputs(item('gcyl:gcyl_meta_item', 601) * 32)
//         .inputs(ore('foilZylon') * 32)
//         .inputs(item('gregtech:meta_item_1', 606) * 32)
//         .inputs(ore('wireGtSingleUevSuperconductor') * 16)
//         .inputs(item('gcyl:gcyl_meta_item', 595) * 8)
//         .inputs(ore('circuitUev') * 4)
//         .inputs(ore('plateAwakenDraconium') * 4)
//         .fluidInputs(fluid('polyetheretherketone') * 2592, fluid('vibranium') * 288, fluid('enriched_naquadah_alloy') * 1296, fluid('trinium_titanium') * 576)
//         .outputs(ore('circuitUiv'))
//         .property("qubit", 2)
//         .duration(300)
//         .EUt(4000000)
//         .buildAndRegister()


// //capacitor recipes
// crafting.addShaped(ore('componentCapacitor') * 4, [[ore('foilAluminium'), ore('foilAluminium'), ore('foilAluminium')], [ore('foilAluminium'), ore('foilAluminium'), ore('foilAluminium')], [ore('wireGtSingleTin'), null, ore('wireGtSingleTin')]])

// Utils.removeRecipeByOutput(assembler, [ore('componentCapacitor') * 2], [], false)

// ASSEMBLER.recipeBuilder()
//         .inputs(ore('foilAluminium') * 4)
//         .inputs(ore('platePlastic'))
//         .outputs(ore('componentCapacitor') * 12)
//         .duration(80)
//         .EUt(16)
//         .buildAndRegister()

// //new electronic circuit recipe
// /*
// Utils.removeRecipeByOutput(CIRCUIT_ASSEMBLER, [item('gregtech:meta_item_2:32488')], [], false)

// CIRCUIT_ASSEMBLER.recipeBuilder()
// .inputs(ore('componentResistor') * 8)
// .inputs(ore('componentCapacitor') * 4)
// .inputs(ore('wireFineCopper') * 4)
// .inputs(item('gtadditions:ga_meta_item:32030'))
// .fluidInputs(fluid('soldering_alloy') * 50)
// .outputs(item('gregtech:meta_item_2:32488'))
// .duration(100)
// .EUt(16)
// .buildAndRegister()

// CIRCUIT_ASSEMBLER.recipeBuilder()
// .inputs(item('gcyl:gcyl_meta_item', 241) * 2)
// .inputs(item('gcyl:gcyl_meta_item', 242) * 2)
// .inputs(ore('wireFineCopper') * 4)
// .inputs(item('gtadditions:ga_meta_item:32030'))
// .fluidInputs(fluid('soldering_alloy') * 50)
// .outputs(item('gregtech:meta_item_2:32488'))
// .duration(100)
// .EUt(16)
// .buildAndRegister()
// */

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotSilver') * 9)
//         .outputs(item('gregtech:meta_block_compressed_3', 14))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotPlatinum') * 9)
//         .outputs(item('gregtech:meta_block_compressed_3', 3))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotEnderium') * 9)
//         .outputs(ore('blockEnderium'))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotLead') * 9)
//         .outputs(item('gregtech:meta_block_compressed_2', 3))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotBronze') * 9)
//         .outputs(ore('lampGtGray'))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotSilicon') * 9)
//         .outputs(ore('blockSilicon'))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotCopper') * 9)
//         .outputs(item('gregtech:meta_block_compressed_1', 2))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotTin') * 9)
//         .outputs(item('gregtech:meta_block_compressed_4', 7))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotNickel') * 9)
//         .outputs(item('gregtech:meta_block_compressed_2', 12))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotInvar') * 9)
//         .outputs(item('gregtech:meta_block_compressed_7', 14))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotElectrum') * 9)
//         .outputs(item('gregtech:meta_block_compressed_7'))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// //block fixes

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotSilver') * 9)
//         .outputs(item('gregtech:meta_block_compressed_3', 14))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotPlatinum') * 9)
//         .outputs(item('gregtech:meta_block_compressed_3', 3))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotEnderium') * 9)
//         .outputs(ore('blockEnderium'))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotLead') * 9)
//         .outputs(item('gregtech:meta_block_compressed_2', 3))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotBronze') * 9)
//         .outputs(ore('lampGtGray'))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotSilicon') * 9)
//         .outputs(ore('blockSilicon'))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotCopper') * 9)
//         .outputs(item('gregtech:meta_block_compressed_1', 2))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotTin') * 9)
//         .outputs(item('gregtech:meta_block_compressed_4', 7))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotNickel') * 9)
//         .outputs(item('gregtech:meta_block_compressed_2', 12))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotInvar') * 9)
//         .outputs(item('gregtech:meta_block_compressed_7', 14))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotElectrum') * 9)
//         .outputs(item('gregtech:meta_block_compressed_7'))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(ADVFusion, [], [fluid('neutronium') * 1296], false)

// Utils.removeRecipeByOutput(assembler, [item('gregtech:meta_item_1:32670')], [], false)
// Utils.removeRecipeByOutput(assembler, [item('gregtech:meta_item_1:32671')], [], false)
// Utils.removeRecipeByOutput(assembler, [item('gregtech:meta_item_1:32672')], [], false)
// Utils.removeRecipeByOutput(assembler, [item('gregtech:meta_item_1:32673')], [], false)
// Utils.removeRecipeByOutput(assembler, [item('gregtech:meta_item_1', 206)], [], false)

// crafting.removeByOutput(item('gregtech:meta_item_1:32670'))
// crafting.removeByOutput(item('gregtech:meta_item_1:32671'))
// crafting.removeByOutput(item('gregtech:meta_item_1:32672'))
// crafting.removeByOutput(item('gregtech:meta_item_1:32673'))
// crafting.removeByOutput(item('gregtech:meta_item_1', 206))


// //lv
// ASSEMBLER.recipeBuilder()
//         .inputs(ore('circuitBasic'))
//         .inputs(ore('dustEnderPearl'))
//         .outputs(item('gregtech:meta_item_1:32670'))
//         .fluidInputs(fluid('lv_superconductor_base') * 288)
//         .duration(100)
//         .EUt(30)
//         .buildAndRegister()
// //mv
// ASSEMBLER.recipeBuilder()
//         .inputs(ore('circuitGood') * 4)
//         .inputs(ore('dustEnderEye'))
//         .outputs(item('gregtech:meta_item_1:32671'))
//         .fluidInputs(fluid('mv_superconductor_base') * 576)
//         .duration(100)
//         .EUt(120)
//         .buildAndRegister()
// //hv
// ASSEMBLER.recipeBuilder()
//         .inputs(ore('circuitHv') * 4)
//         .inputs(item('gregtech:meta_item_1:32724'))
//         .outputs(item('gregtech:meta_item_1:32672'))
//         .fluidInputs(fluid('hv_superconductor_base') * 1152)
//         .duration(100)
//         .EUt(480)
//         .buildAndRegister()
// //EV
// ASSEMBLER.recipeBuilder()
//         .inputs(ore('circuitEv') * 4)
//         .inputs(ore('dustNetherStar'))
//         .outputs(item('gregtech:meta_item_1:32673'))
//         .fluidInputs(fluid('ev_superconductor_base') * 2304)
//         .duration(100)
//         .EUt(1920)
//         .buildAndRegister()
// //IV
// ASSEMBLER.recipeBuilder()
//         .inputs(ore('circuitIv') * 4)
//         .inputs(item('gregtech:meta_item_1:32725'))
//         .outputs(item('gregtech:meta_item_1', 206))
//         .fluidInputs(fluid('iv_superconductor_base') * 4608)
//         .duration(100)
//         .EUt(7680)
//         .buildAndRegister()

// crafting.addShaped(item('gregtech:meta_item_1', 206), [[ore('wireGtHexIvSuperconductorBase'), ore('circuitIv'), ore('wireGtHexIvSuperconductorBase')], [ore('circuitIv'), item('gregtech:meta_item_1:32725'), ore('circuitIv')], [ore('wireGtHexIvSuperconductorBase'), ore('circuitIv'), ore('wireGtHexIvSuperconductorBase')]])
// crafting.addShaped(item('gregtech:meta_item_1:32673'), [[ore('wireGtOctalEvSuperconductorBase'), ore('circuitEv'), ore('wireGtOctalEvSuperconductorBase')], [ore('circuitEv'), ore('gemNetherStar,netherStar'), ore('circuitEv')], [ore('wireGtOctalEvSuperconductorBase'), ore('circuitEv'), ore('wireGtOctalEvSuperconductorBase')]])
// crafting.addShaped(item('gregtech:meta_item_1:32672'), [[ore('wireGtQuadrupleHvSuperconductorBase'), ore('circuitHv'), ore('wireGtQuadrupleHvSuperconductorBase')], [ore('circuitHv'), item('gregtech:meta_item_1:32724'), ore('circuitHv')], [ore('wireGtQuadrupleHvSuperconductorBase'), ore('circuitHv'), ore('wireGtQuadrupleHvSuperconductorBase')]])
// crafting.addShaped(item('gregtech:meta_item_1:32671'), [[ore('wireGtDoubleMvSuperconductorBase'), ore('circuitGood'), ore('wireGtDoubleMvSuperconductorBase')], [ore('circuitGood'), ore('pearlEnderEye'), ore('circuitGood')], [ore('wireGtDoubleMvSuperconductorBase'), ore('circuitGood'), ore('wireGtDoubleMvSuperconductorBase')]])
// crafting.addShaped(item('gregtech:meta_item_1:32670'), [[item('gregtech:cable', 516), ore('circuitBasic'), item('gregtech:cable', 516)], [ore('circuitBasic'), ore('enderpearl'), ore('circuitBasic')], [item('gregtech:cable', 516), ore('circuitBasic'), item('gregtech:cable', 516)]])

// Utils.removeRecipeByOutput(largeMix, [ore('dustNiobiumNitride') * 2], [], true)

// LARGE_MIXER.recipeBuilder()
//         .inputs(ore('dustNiobium'))
//         .outputs(ore('dustNiobiumNitride') * 2)
//         .fluidInputs(fluid('nitrogen') * 1000)
//         .circuitMeta(1)
//         .duration(108)
//         .EUt(30)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(largeMix, [ore('dustNichrome') * 5], [], true)

// LARGE_MIXER.recipeBuilder()
//         .inputs(ore('dustChrome'))
//         .inputs(ore('dustNickel') * 4)
//         .outputs(ore('dustNichrome') * 5)
//         .circuitMeta(11)
//         .duration(280)
//         .EUt(30)
//         .buildAndRegister()

// condenser.recipeBuilder()
//         .fluidInputs(fluid('plasma.helium3') * 1000, fluid('superfluid_helium') * 100)
//         .fluidOutputs(fluid('helium') * 100, fluid('helium3') * 1000)
//         .circuitMeta(1)
//         .duration(40)
//         .EUt(960)
//         .buildAndRegister()

// LARGE_MIXER.recipeBuilder()
//         .inputs(ore('dustCopper') * 3)
//         .inputs(ore('dustSilver'))
//         .fluidInputs(fluid('redstone') * 1000)
//         .outputs(ore('dustSignalum') * 4)
//         .duration(240)
//         .EUt(500)
//         .buildAndRegister()

// //steel
// ASSEMBLER.recipeBuilder()
//         .inputs(ore('plateSteel') * 4)
//         .inputs(ore('frameGtSteel'))
//         .inputs(ore('gearSteel') * 2)
//         .outputs(item('gregtech:turbine_casing', 1))
//         .duration(200)
//         .EUt(30)
//         .buildAndRegister()
// //ti
// ASSEMBLER.recipeBuilder()
//         .inputs(ore('plateSteel') * 4)
//         .inputs(item('gregtech:frame_titanium'))
//         .inputs(ore('gearTitanium') * 2)
//         .outputs(item('gregtech:turbine_casing', 2) * 3)
//         .duration(200)
//         .EUt(30)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(assembly_line, [ore('dustNiobiumNitride') * 2], [], true)
// Utils.removeRecipeByOutput(assembly_line, [item('gregtech:meta_item_1:32670') * 16], [], true)

// assembly_line.recipeBuilder()
//         .inputs(ore('ingotSolderingAlloy') * 2)
//         .inputs(ore('circuitBasic') * 8)
//         .inputs(ore('dustEnderPearl') * 4)
//         .outputs(item('gregtech:meta_item_1:32670') * 16)
//         .circuitMeta(1)
//         .circuitMeta(2)
//         .duration(6000)
//         .EUt(8000)
//         .buildAndRegister()
// ore('gemQuartzBlack').addTooltip("Smelt Quartzite dust twice")
// ore('dustQuartzBlack').addTooltip("Smelt Quartzite dust")

// ore('bookEnchanted,craftingBook').withNbt({ StoredEnchantments:
// [{ lvl:
// 1 as short ,
//      id:
//      13 as short }] }).addTooltip("§4DO NOT STACK THESE IN THE ANVIL IT WILL VOID YOUR BOOKS")


// Utils.removeRecipeByOutput(engraver, [item('gregtech:meta_item_1', 566)], [], true)
// Utils.removeRecipeByOutput(large_engrav, [item('gregtech:meta_item_1', 566)], [], true)

// engraver.recipeBuilder()
//         .inputs(metaitem('wafer.silicon'))
//         .outputs(item('gregtech:meta_item_1', 566))
//         .notConsumable(ore('craftingLensWhite'))
//         .duration(45 * 20)
//         .EUt(18)
//         .buildAndRegister()

// large_engrav.recipeBuilder()
//         .inputs(metaitem('wafer.silicon'))
//         .outputs(item('gregtech:meta_item_1', 566))
//         .notConsumable(ore('craftingLensWhite'))
//         .duration(45 * 20)
//         .EUt(18)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(forming, [item('gregtech:meta_item_2:15518')], [], true)

// ASSEMBLER.recipeBuilder()
//         .inputs(item('minecraft:iron_bars') * 3)
//         .inputs(ore('plateIron') * 6)
//         .outputs(item('advancedrocketry:carbonscrubbercartridge'))
//         .duration(90)
//         .EUt(30)
//         .buildAndRegister()

// crafting.removeByOutput(item('gregtech:machine:2552'))