// no_run


// crafting.addShaped(ore('componentResistor') * 2, [[item('gregtech:meta_item_1', 438), ore('wireGtSingleCopper'), item('gregtech:meta_item_1', 438)], [ore('wireGtSingleCopper'), ore('dustCharcoal'), ore('wireGtSingleCopper')], [null, ore('wireGtSingleCopper'), null]])
// crafting.addShaped(ore('componentResistor') * 2, [[item('gregtech:meta_item_1', 438), ore('wireGtSingleCopper'), item('gregtech:meta_item_1', 438)], [ore('wireGtSingleCopper'), ore('dustCoal'), ore('wireGtSingleCopper')], [null, ore('wireGtSingleCopper'), null]])
// crafting.addShaped(ore('bookEnchanted,craftingBook').withNbt({ StoredEnchantments:
// [{ lvl:
// 1 as short ,
//      id:
//      45 as short }] }), [[item('minecraft:red_nether_brick'), item('minecraft:netherrack'), item('minecraft:red_nether_brick')], [item('minecraft:netherrack'), ore('bookEmpty,craftingBook'), item('minecraft:netherrack')], [item('minecraft:nether_brick'), item('minecraft:netherrack'), item('minecraft:nether_brick')]])




// blast_furnace.findRecipe(120, [ore('dustIridium'), ore('dustSalt'), ore('dustSalt')], [fluid('oxygen') * 2000]).remove()


// CHEMICAL_REACTOR.recipeBuilder()
//         .inputs(ore('dustIridium') * 2)
//         .notConsumable(ore('dustSalt'))
//         .outputs(ore('dustBismuthIridiate') * 11)
//         .fluidInputs(fluid('oxygen') * 4000, fluid('hydrogen') * 1000, fluid('bismuth_nitrate_solution') * 2000)
//         .fluidOutputs(fluid('nitrogen_dioxide') * 1000, fluid('nitric_acid') * 5000)
//         .duration(300)
//         .EUt(1920)
//         .buildAndRegister()
// LCR.recipeBuilder()
//         .inputs(ore('dustIridium') * 2)
//         .notConsumable(ore('dustSalt'))
//         .outputs(ore('dustBismuthIridiate') * 11)
//         .fluidInputs(fluid('oxygen') * 4000, fluid('hydrogen') * 1000, fluid('bismuth_nitrate_solution') * 2000)
//         .fluidOutputs(fluid('nitrogen_dioxide') * 1000, fluid('nitric_acid') * 5000)
//         .duration(300)
//         .EUt(1920)
//         .buildAndRegister()

// crafting.removeByOutput(item('randomthings:ingredient', 1))
// crafting.addShaped(item('randomthings:ingredient', 1), [[item('randomthings:stableenderpearl'), ore('foilStainlessSteel'), item('randomthings:stableenderpearl')], [ore('foilStainlessSteel'), ore('itemSkull'), ore('foilStainlessSteel')], [item('randomthings:stableenderpearl'), ore('foilStainlessSteel'), item('randomthings:stableenderpearl')]])

// centrifuge.findRecipe(640, [ore('dustNaquadahEnriched')], []).remove()
// large_centrifuge.findRecipe(640, [ore('dustNaquadahEnriched')], []).remove()

// centrifuge.findRecipe(320, [ore('dustNaquadah')], []).remove()
// large_centrifuge.findRecipe(320, [ore('dustNaquadah')], []).remove()

// Utils.removeRecipeByOutput(blast_furnace, [ore('ingotSilicon')], [], true)
// crafting.addShaped(item('minecraft:name_tag'), [[null, ore('cropFlax,string'), ore('cropFlax,string')], [null, ore('slimeball'), ore('cropFlax,string')], [ore('cropFlax,string'), null, null]])

// ASSEMBLER.recipeBuilder()
//         .inputs(ore('chest,chestWood') * 4)
//         .outputs(item('gregtech:machine', 808) * 4)
//         .circuitMeta(2)
//         .duration(60)
//         .EUt(16)
//         .buildAndRegister()
// crafting.addShaped(item('gregtech:machine:4034'), [[null, null, null], [null, item('gregtech:mte', 997), ore('cableGtSingleNeutronium')], [null, null, null]])
// crafting.addShaped(item('gregtech:machine:4029'), [[null, null, null], [ore('cableGtSingleNeutronium'), item('gregtech:mte', 997), null], [null, null, null]])

// crafting.removeByOutput(item('danknull:dank_null_1'))
// crafting.removeByOutput(item('danknull:dank_null_panel_1'))
// crafting.addShaped(item('danknull:dank_null_1'), [[item('danknull:dank_null_panel_1'), item('danknull:dank_null_panel_1'), item('danknull:dank_null_panel_1')], [item('danknull:dank_null_panel_1'), item('danknull:dank_null_0'), item('danknull:dank_null_panel_1')], [item('danknull:dank_null_panel_1'), item('danknull:dank_null_panel_1'), item('danknull:dank_null_panel_1')]])
// crafting.addShaped(item('danknull:dank_null_panel_1'), [[ore('blockLapis'), ore('blockCoalCoke'), ore('blockLapis')], [ore('blockCoalCoke'), item('gtadditions:ga_transparent_casing', 1), ore('blockCoalCoke')], [ore('blockLapis'), ore('blockCoalCoke'), ore('blockLapis')]])

// LCR.recipeBuilder()
//         .inputs(item('gtadditions:ga_dust', 922) * 4)
//         .fluidInputs(fluid('fuming_nitric_acid') * 2000)
//         .notConsumable(fluid('acetic_anhydride'))
//         .outputs(item('gtadditions:ga_dust', 530))
//         .EUt(1024)
//         .duration(20)
//         .buildAndRegister()


// LCR.recipeBuilder()
//         .inputs(ore('dustTinySodiumHydroxide'))
//         .fluidInputs(fluid('creosote') * 10000, fluid(' ethanol') * 1000)
//         .fluidOutputs(fluid(' bio_diesel') * 10000, fluid(' glycerol') * 1000)
//         .duration(120)
//         .EUt(30)
//         .buildAndRegister()

// LCR.recipeBuilder()
//         .inputs(ore('dustTinySodiumHydroxide'))
//         .fluidInputs(fluid('creosote') * 10000, fluid(' methanol') * 1000)
//         .fluidOutputs(fluid(' bio_diesel') * 10000, fluid(' glycerol') * 1000)
//         .duration(120)
//         .EUt(30)
//         .buildAndRegister()
// //update vacuume tube
// crafting.removeByOutput(ore('circuitUlv'))
// crafting.addShaped(ore('circuitUlv'), [[null, item('gregtech:meta_item_1', 517), null], [null, item('gregtech:meta_item_1:16018'), null], [ore('stickWroughtIron'), null, ore('stickWroughtIron')]])
// crafting.removeByOutput(item('gregtech:meta_item_1', 502))


// CHEMICAL_REACTOR.recipeBuilder()
//         .inputs(ore('wool') * 5)
//         .fluidInputs(fluid('glue') * 144, fluid('plastic') * 144)
//         .outputs(item('gregtech:meta_item_1', 502) * 10)
//         .duration(160)
//         .EUt(14)
//         .buildAndRegister()


// LCR.recipeBuilder()
//         .inputs(ore('wool') * 5)
//         .fluidInputs(fluid('glue') * 144, fluid('plastic') * 144)
//         .outputs(item('gregtech:meta_item_1', 502) * 10)
//         .duration(160)
//         .EUt(14)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(chemreactor, [], [fluid('indium_concentrate')], false)
// Utils.removeRecipeByOutput(large_chem, [], [fluid('indium_concentrate')], false)

// LARGE_MIXER.recipeBuilder()
//         .inputs(ore('sand') * 4)
//         .inputs(ore('gravel') * 4)
//         .circuitMeta(3)
//         .fluidInputs(fluid('water') * 1000)
//         .outputs(ore('itemBinderComposite') * 16)
//         .EUt(500)
//         .duration(80)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(assembler, [item('gregtech:mte', 993)], [], true)

// ASSEMBLER.recipeBuilder()
//         .inputs(ore('cableGtSingleNaquadahAlloy') * 2)
//         .inputs(item('gregtech:machine_casing', 8))
//         .outputs(item('gregtech:mte', 993))
//         .fluidInputs(fluid('polybenzimidazole') * 288)
//         .duration(50)
//         .EUt(16)
//         .buildAndRegister()


// LCR.recipeBuilder()
//         .inputs(item('actuallyadditions:item_misc', 23) * 8)
//         .fluidInputs(fluid('refinedcanolaoil') * 10000)
//         .fluidOutputs(fluid('crystaloil') * 10000)
//         .duration(300)
//         .EUt(16)
//         .buildAndRegister()

// LCR.recipeBuilder()
//         .fluidInputs(fluid('crystaloil') * 5000, fluid(' creosote') * 5000)
//         .fluidOutputs(fluid('empoweredoil') * 10000)
//         .duration(300)
//         .EUt(16)
//         .buildAndRegister()

// LCR.recipeBuilder()
//         .inputs(ore('dustTinySodiumHydroxide'))
//         .fluidInputs(fluid('empoweredoil') * 10000, fluid(' ethanol') * 1000)
//         .fluidOutputs(fluid(' bio_diesel') * 10000, fluid(' glycerol') * 1000)
//         .duration(120)
//         .EUt(30)
//         .buildAndRegister()

// LCR.recipeBuilder()
//         .inputs(ore('dustTinySodiumHydroxide'))
//         .fluidInputs(fluid('empoweredoil') * 10000, fluid(' methanol') * 1000)
//         .fluidOutputs(fluid(' bio_diesel') * 10000, fluid(' glycerol') * 1000)
//         .duration(120)
//         .EUt(30)
//         .buildAndRegister()

// CHEMICAL_REACTOR.recipeBuilder()
//         .inputs(ore('wool') * 5)
//         .fluidInputs(fluid('glue') * 144, fluid('polytetrafluoroethylene') * 144)
//         .outputs(item('gregtech:meta_item_1', 502) * 20)
//         .duration(160)
//         .EUt(116)
//         .buildAndRegister()


// LCR.recipeBuilder()
//         .inputs(ore('wool') * 5)
//         .fluidInputs(fluid('glue') * 144, fluid('polytetrafluoroethylene') * 144)
//         .outputs(item('gregtech:meta_item_1', 502) * 20)
//         .duration(160)
//         .EUt(116)
//         .buildAndRegister()


// CHEMICAL_REACTOR.recipeBuilder()
//         .inputs(ore('wool') * 5)
//         .fluidInputs(fluid('glue') * 144, fluid('polybenzimidazole') * 144)
//         .outputs(item('gregtech:meta_item_1', 502) * 40)
//         .duration(160)
//         .EUt(116)
//         .buildAndRegister()


// LCR.recipeBuilder()
//         .inputs(ore('wool') * 5)
//         .fluidInputs(fluid('glue') * 144, fluid('polybenzimidazole') * 144)
//         .outputs(item('gregtech:meta_item_1', 502) * 40)
//         .duration(160)
//         .EUt(116)
//         .buildAndRegister()

// crafting.addShaped(metaitem('tjceu:blockEternity'), [[metaitem('tjceu:ingotEternity'), metaitem('tjceu:ingotEternity'), metaitem('tjceu:ingotEternity')], [metaitem('tjceu:ingotEternity'), metaitem('tjceu:ingotEternity'), metaitem('tjceu:ingotEternity')], [metaitem('tjceu:ingotEternity'), metaitem('tjceu:ingotEternity'), metaitem('tjceu:ingotEternity')]])
// crafting.addShapeless(metaitem('tjceu:ingotEternity') * 9, [metaitem('tjceu:blockEternity')])

// crafting.addShaped(ore('toolHoe').withNbt({ Unbreakable:
// 1 as long ,
//     RepairCost: 1 ,
//     display:
//     { Name: "Unbreakable Emerald Tipped Diamond Hoe" } }), [[ore('gemEmerald'), ore('gemEmerald'), null], [ore('gemEmerald'), ore('toolHoe'), null], [null, null, null]])
// mods.jei.JEI.addItem(ore('toolHoe').withNbt({ display:
// { Name: "Unbreakable Emerald Tipped Diamond Hoe" } }))

// ABS.recipeBuilder()
//         .inputs(ore('dustSeaborgium') * 4)
//         .inputs(ore('dustBohrium') * 4)
//         .blastFurnaceTemp(11200)
//         .fluidOutputs(fluid('fusion1') * 1152)
//         .duration(160)
//         .EUt(1000000)
//         .buildAndRegister()

// ABS.recipeBuilder()
//         .inputs(ore('dustRutherfordium') * 4)
//         .blastFurnaceTemp(11200)
//         .inputs(ore('dustDubnium') * 4)
//         .fluidOutputs(fluid('fusion2') * 1152)
//         .duration(160)
//         .EUt(1000000)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(blast_alloy, [], [fluid('superheavy_mix') * 4000], false)
// //blast_alloy.findRecipe(25000000, [ore('dustRutherfordium'), ore('dustDubnium'), ore('dustSeaborgium'), ore('dustBohrium'), ])

// ADV_FUSION.recipeBuilder()
//         .fluidInputs(fluid('fusion1') * 288, fluid('fusion2') * 288)//,fluid('lead_bismuth_eutatic') * 7440)
//         .fluidOutputs(fluid('superheavy_mix') * 1000)//, fluid('supercritical_lead_bismuth_eutectic') * 7440)
//         .EUToStart(10000000000)
//         .AdvCoilTier(4)
//         .EUReturn(75)
//         .duration(50)
//         .EUt(4000000)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(assembly_line, [ore('circuitUiv')], [], false)


// assembly_line.recipeBuilder()
//         .inputs(item('gcyl:gcyl_meta_item', 426) * 64)
//         .inputs(item('gcyl:gcyl_meta_item', 603) * 32)
//         .inputs(item('gcyl:gcyl_meta_item', 602) * 32)
//         .inputs(item('gcyl:gcyl_meta_item', 604) * 32)
//         .inputs(item('gcyl:gcyl_meta_item', 601) * 32)
//         .inputs(ore('foilZylon') * 32)
//         .inputs(item('gregtech:meta_item_1', 606) * 32)
//         .inputs(ore('wireGtSingleUevSuperconductor') * 16)
//         .inputs(item('gcyl:gcyl_meta_item', 595) * 8)
//         .inputs(ore('circuitUev') * 4)
//         .inputs(ore('plateAwakenDraconium') * 4)
//         .fluidInputs(fluid('polyetheretherketone') * 2592, fluid('vibranium') * 288, fluid('enriched_naquadah_alloy') * 1296, fluid('trinium_titanium') * 576)
//         .outputs(ore('circuitUiv'))
//         .property("qubit", 2)
//         .duration(300)
//         .EUt(4000000)
//         .buildAndRegister()


// //capacitor recipes
// crafting.addShaped(ore('componentCapacitor') * 4, [[ore('foilAluminium'), ore('foilAluminium'), ore('foilAluminium')], [ore('foilAluminium'), ore('foilAluminium'), ore('foilAluminium')], [ore('wireGtSingleTin'), null, ore('wireGtSingleTin')]])

// Utils.removeRecipeByOutput(assembler, [ore('componentCapacitor') * 2], [], false)

// ASSEMBLER.recipeBuilder()
//         .inputs(ore('foilAluminium') * 4)
//         .inputs(ore('platePlastic'))
//         .outputs(ore('componentCapacitor') * 12)
//         .duration(80)
//         .EUt(16)
//         .buildAndRegister()

// //new electronic circuit recipe
// /*
// Utils.removeRecipeByOutput(CIRCUIT_ASSEMBLER, [item('gregtech:meta_item_2:32488')], [], false)

// CIRCUIT_ASSEMBLER.recipeBuilder()
// .inputs(ore('componentResistor') * 8)
// .inputs(ore('componentCapacitor') * 4)
// .inputs(ore('wireFineCopper') * 4)
// .inputs(item('gtadditions:ga_meta_item:32030'))
// .fluidInputs(fluid('soldering_alloy') * 50)
// .outputs(item('gregtech:meta_item_2:32488'))
// .duration(100)
// .EUt(16)
// .buildAndRegister()

// CIRCUIT_ASSEMBLER.recipeBuilder()
// .inputs(item('gcyl:gcyl_meta_item', 241) * 2)
// .inputs(item('gcyl:gcyl_meta_item', 242) * 2)
// .inputs(ore('wireFineCopper') * 4)
// .inputs(item('gtadditions:ga_meta_item:32030'))
// .fluidInputs(fluid('soldering_alloy') * 50)
// .outputs(item('gregtech:meta_item_2:32488'))
// .duration(100)
// .EUt(16)
// .buildAndRegister()
// */

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotSilver') * 9)
//         .outputs(item('gregtech:meta_block_compressed_3', 14))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotPlatinum') * 9)
//         .outputs(item('gregtech:meta_block_compressed_3', 3))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotEnderium') * 9)
//         .outputs(ore('blockEnderium'))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotLead') * 9)
//         .outputs(item('gregtech:meta_block_compressed_2', 3))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotBronze') * 9)
//         .outputs(ore('lampGtGray'))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotSilicon') * 9)
//         .outputs(ore('blockSilicon'))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotCopper') * 9)
//         .outputs(item('gregtech:meta_block_compressed_1', 2))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotTin') * 9)
//         .outputs(item('gregtech:meta_block_compressed_4', 7))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotNickel') * 9)
//         .outputs(item('gregtech:meta_block_compressed_2', 12))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotInvar') * 9)
//         .outputs(item('gregtech:meta_block_compressed_7', 14))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotElectrum') * 9)
//         .outputs(item('gregtech:meta_block_compressed_7'))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// //block fixes

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotSilver') * 9)
//         .outputs(item('gregtech:meta_block_compressed_3', 14))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotPlatinum') * 9)
//         .outputs(item('gregtech:meta_block_compressed_3', 3))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotEnderium') * 9)
//         .outputs(ore('blockEnderium'))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotLead') * 9)
//         .outputs(item('gregtech:meta_block_compressed_2', 3))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotBronze') * 9)
//         .outputs(ore('lampGtGray'))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotSilicon') * 9)
//         .outputs(ore('blockSilicon'))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotCopper') * 9)
//         .outputs(item('gregtech:meta_block_compressed_1', 2))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotTin') * 9)
//         .outputs(item('gregtech:meta_block_compressed_4', 7))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotNickel') * 9)
//         .outputs(item('gregtech:meta_block_compressed_2', 12))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotInvar') * 9)
//         .outputs(item('gregtech:meta_block_compressed_7', 14))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// COMPRESSOR.recipeBuilder()
//         .inputs(ore('ingotElectrum') * 9)
//         .outputs(item('gregtech:meta_block_compressed_7'))
//         .duration(400)
//         .EUt(2)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(ADVFusion, [], [fluid('neutronium') * 1296], false)

// Utils.removeRecipeByOutput(assembler, [item('gregtech:meta_item_1:32670')], [], false)
// Utils.removeRecipeByOutput(assembler, [item('gregtech:meta_item_1:32671')], [], false)
// Utils.removeRecipeByOutput(assembler, [item('gregtech:meta_item_1:32672')], [], false)
// Utils.removeRecipeByOutput(assembler, [item('gregtech:meta_item_1:32673')], [], false)
// Utils.removeRecipeByOutput(assembler, [item('gregtech:meta_item_1', 206)], [], false)

// crafting.removeByOutput(item('gregtech:meta_item_1:32670'))
// crafting.removeByOutput(item('gregtech:meta_item_1:32671'))
// crafting.removeByOutput(item('gregtech:meta_item_1:32672'))
// crafting.removeByOutput(item('gregtech:meta_item_1:32673'))
// crafting.removeByOutput(item('gregtech:meta_item_1', 206))


// //lv
// ASSEMBLER.recipeBuilder()
//         .inputs(ore('circuitBasic'))
//         .inputs(ore('dustEnderPearl'))
//         .outputs(item('gregtech:meta_item_1:32670'))
//         .fluidInputs(fluid('lv_superconductor_base') * 288)
//         .duration(100)
//         .EUt(30)
//         .buildAndRegister()
// //mv
// ASSEMBLER.recipeBuilder()
//         .inputs(ore('circuitGood') * 4)
//         .inputs(ore('dustEnderEye'))
//         .outputs(item('gregtech:meta_item_1:32671'))
//         .fluidInputs(fluid('mv_superconductor_base') * 576)
//         .duration(100)
//         .EUt(120)
//         .buildAndRegister()
// //hv
// ASSEMBLER.recipeBuilder()
//         .inputs(ore('circuitHv') * 4)
//         .inputs(item('gregtech:meta_item_1:32724'))
//         .outputs(item('gregtech:meta_item_1:32672'))
//         .fluidInputs(fluid('hv_superconductor_base') * 1152)
//         .duration(100)
//         .EUt(480)
//         .buildAndRegister()
// //EV
// ASSEMBLER.recipeBuilder()
//         .inputs(ore('circuitEv') * 4)
//         .inputs(ore('dustNetherStar'))
//         .outputs(item('gregtech:meta_item_1:32673'))
//         .fluidInputs(fluid('ev_superconductor_base') * 2304)
//         .duration(100)
//         .EUt(1920)
//         .buildAndRegister()
// //IV
// ASSEMBLER.recipeBuilder()
//         .inputs(ore('circuitIv') * 4)
//         .inputs(item('gregtech:meta_item_1:32725'))
//         .outputs(item('gregtech:meta_item_1', 206))
//         .fluidInputs(fluid('iv_superconductor_base') * 4608)
//         .duration(100)
//         .EUt(7680)
//         .buildAndRegister()

// crafting.addShaped(item('gregtech:meta_item_1', 206), [[ore('wireGtHexIvSuperconductorBase'), ore('circuitIv'), ore('wireGtHexIvSuperconductorBase')], [ore('circuitIv'), item('gregtech:meta_item_1:32725'), ore('circuitIv')], [ore('wireGtHexIvSuperconductorBase'), ore('circuitIv'), ore('wireGtHexIvSuperconductorBase')]])
// crafting.addShaped(item('gregtech:meta_item_1:32673'), [[ore('wireGtOctalEvSuperconductorBase'), ore('circuitEv'), ore('wireGtOctalEvSuperconductorBase')], [ore('circuitEv'), ore('gemNetherStar,netherStar'), ore('circuitEv')], [ore('wireGtOctalEvSuperconductorBase'), ore('circuitEv'), ore('wireGtOctalEvSuperconductorBase')]])
// crafting.addShaped(item('gregtech:meta_item_1:32672'), [[ore('wireGtQuadrupleHvSuperconductorBase'), ore('circuitHv'), ore('wireGtQuadrupleHvSuperconductorBase')], [ore('circuitHv'), item('gregtech:meta_item_1:32724'), ore('circuitHv')], [ore('wireGtQuadrupleHvSuperconductorBase'), ore('circuitHv'), ore('wireGtQuadrupleHvSuperconductorBase')]])
// crafting.addShaped(item('gregtech:meta_item_1:32671'), [[ore('wireGtDoubleMvSuperconductorBase'), ore('circuitGood'), ore('wireGtDoubleMvSuperconductorBase')], [ore('circuitGood'), ore('pearlEnderEye'), ore('circuitGood')], [ore('wireGtDoubleMvSuperconductorBase'), ore('circuitGood'), ore('wireGtDoubleMvSuperconductorBase')]])
// crafting.addShaped(item('gregtech:meta_item_1:32670'), [[item('gregtech:cable', 516), ore('circuitBasic'), item('gregtech:cable', 516)], [ore('circuitBasic'), ore('enderpearl'), ore('circuitBasic')], [item('gregtech:cable', 516), ore('circuitBasic'), item('gregtech:cable', 516)]])

// Utils.removeRecipeByOutput(largeMix, [ore('dustNiobiumNitride') * 2], [], true)

// LARGE_MIXER.recipeBuilder()
//         .inputs(ore('dustNiobium'))
//         .outputs(ore('dustNiobiumNitride') * 2)
//         .fluidInputs(fluid('nitrogen') * 1000)
//         .circuitMeta(1)
//         .duration(108)
//         .EUt(30)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(largeMix, [ore('dustNichrome') * 5], [], true)

// LARGE_MIXER.recipeBuilder()
//         .inputs(ore('dustChrome'))
//         .inputs(ore('dustNickel') * 4)
//         .outputs(ore('dustNichrome') * 5)
//         .circuitMeta(11)
//         .duration(280)
//         .EUt(30)
//         .buildAndRegister()

// condenser.recipeBuilder()
//         .fluidInputs(fluid('plasma.helium3') * 1000, fluid('superfluid_helium') * 100)
//         .fluidOutputs(fluid('helium') * 100, fluid('helium3') * 1000)
//         .circuitMeta(1)
//         .duration(40)
//         .EUt(960)
//         .buildAndRegister()

// LARGE_MIXER.recipeBuilder()
//         .inputs(ore('dustCopper') * 3)
//         .inputs(ore('dustSilver'))
//         .fluidInputs(fluid('redstone') * 1000)
//         .outputs(ore('dustSignalum') * 4)
//         .duration(240)
//         .EUt(500)
//         .buildAndRegister()

// //steel
// ASSEMBLER.recipeBuilder()
//         .inputs(ore('plateSteel') * 4)
//         .inputs(ore('frameGtSteel'))
//         .inputs(ore('gearSteel') * 2)
//         .outputs(item('gregtech:turbine_casing', 1))
//         .duration(200)
//         .EUt(30)
//         .buildAndRegister()
// //ti
// ASSEMBLER.recipeBuilder()
//         .inputs(ore('plateSteel') * 4)
//         .inputs(item('gregtech:frame_titanium'))
//         .inputs(ore('gearTitanium') * 2)
//         .outputs(item('gregtech:turbine_casing', 2) * 3)
//         .duration(200)
//         .EUt(30)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(assembly_line, [ore('dustNiobiumNitride') * 2], [], true)
// Utils.removeRecipeByOutput(assembly_line, [item('gregtech:meta_item_1:32670') * 16], [], true)

// assembly_line.recipeBuilder()
//         .inputs(ore('ingotSolderingAlloy') * 2)
//         .inputs(ore('circuitBasic') * 8)
//         .inputs(ore('dustEnderPearl') * 4)
//         .outputs(item('gregtech:meta_item_1:32670') * 16)
//         .circuitMeta(1)
//         .circuitMeta(2)
//         .duration(6000)
//         .EUt(8000)
//         .buildAndRegister()
// ore('gemQuartzBlack').addTooltip("Smelt Quartzite dust twice")
// ore('dustQuartzBlack').addTooltip("Smelt Quartzite dust")

// ore('bookEnchanted,craftingBook').withNbt({ StoredEnchantments:
// [{ lvl:
// 1 as short ,
//      id:
//      13 as short }] }).addTooltip("§4DO NOT STACK THESE IN THE ANVIL IT WILL VOID YOUR BOOKS")


// Utils.removeRecipeByOutput(engraver, [item('gregtech:meta_item_1', 566)], [], true)
// Utils.removeRecipeByOutput(large_engrav, [item('gregtech:meta_item_1', 566)], [], true)

// engraver.recipeBuilder()
//         .inputs(metaitem('wafer.silicon'))
//         .outputs(item('gregtech:meta_item_1', 566))
//         .notConsumable(ore('craftingLensWhite'))
//         .duration(45 * 20)
//         .EUt(18)
//         .buildAndRegister()

// large_engrav.recipeBuilder()
//         .inputs(metaitem('wafer.silicon'))
//         .outputs(item('gregtech:meta_item_1', 566))
//         .notConsumable(ore('craftingLensWhite'))
//         .duration(45 * 20)
//         .EUt(18)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(forming, [item('gregtech:meta_item_2:15518')], [], true)

// ASSEMBLER.recipeBuilder()
//         .inputs(item('minecraft:iron_bars') * 3)
//         .inputs(ore('plateIron') * 6)
//         .outputs(item('advancedrocketry:carbonscrubbercartridge'))
//         .duration(90)
//         .EUt(30)
//         .buildAndRegister()

// crafting.removeByOutput(item('gregtech:machine:2552'))