// import mods.jei.JEI.removeAndHide as rh;
// //This file was created via CT-GUI! Editing it is not advised!
// //Don't touch me!
// //#Remove
// furnace.removeByOutput(ore('gemNetherStar,netherStar'));
// crafting.removeByOutput(item('actuallyadditions:block_misc:7'));
// crafting.removeByOutput(item('actuallyadditions:block_lava_factory_controller:0'));
// crafting.removeByOutput(ore('blockTitanium,blockWarpCoreRim'));
// crafting.removeByOutput(ore('dustLumium') * 4);
// crafting.removeByOutput(ore('dustSignalum') * 4);
// rh(item('actuallyadditions:block_tiny_torch:0'));
// rh(item('actuallyadditions:item_color_lens:0'));
// rh(item('actuallyadditions:item_mining_lens:0'));
// rh(item('actuallyadditions:block_coal_generator:0'));
// rh(item('actuallyadditions:block_firework_box:0'));
// rh(item('actuallyadditions:block_canola_press:0'));
// rh(item('actuallyadditions:block_heat_collector:0'));
// rh(item('actuallyadditions:block_coffee_machine:0'));
// furnace.removeByOutput(ore('ingotTungsten'), ore('dustTungsten'));
// crafting.removeByOutput(item('thermalfoundation:material:128'));
// rh(item('thermalfoundation:material:1024'));
// rh(item('thermalfoundation:material:1025'));
// rh(ore('dustAerotheum'));
// rh(ore('dustPetrotheum'));
// rh(item('actuallyadditions:block_inputter:0'));
// rh(item('actuallyadditions:block_inputter_advanced:0'));
// rh(item('actuallyadditions:block_item_repairer:0'));
// rh(item('actuallyadditions:block_miner:0'));
// rh(item('actuallyadditions:block_leaf_generator:0'));
// rh(item('actuallyadditions:block_bio_reactor:0'));
// rh(item('actuallyadditions:block_oil_generator:0'));
// rh(item('actuallyadditions:block_enervator:0'));
// rh(item('actuallyadditions:block_energizer:0'));
// rh(item('actuallyadditions:block_grinder:0'));
// rh(item('actuallyadditions:block_grinder_double:0'));
// rh(item('actuallyadditions:block_furnace_double:0'));
// crafting.removeByOutput(item('thermalfoundation:material:193') * 9);
// crafting.removeByOutput(item('thermalfoundation:material:129'));
// furnace.removeByOutput(ore('nuggetWroughtIron'), ore('nuggetIron'));
// furnace.removeByOutput(ore('ingotAluminium'));
// crafting.removeByOutput(item('enderio:item_redstone_conduit:0'));
// crafting.removeByOutput(item('appliedenergistics2:part:140'));
// crafting.removeByOutput(item('appliedenergistics2:quartz_glass:0'));
// recipes.removeShapeless(ore('pearlEnderEye'), [ ore('enderpearl'), ore('dustBlaze,itemBlazePowder')]);
// recipes.removeShapeless(item('appliedenergistics2:part:36'), [ item('appliedenergistics2:part:16'), ore('wool')]);
// recipes.removeShapeless(ore('dustClay'), [ ore('blockClay,oreClay')]);
// crafting.removeByOutput(item('enderio:item_power_conduit:1'));
// crafting.removeByOutput(item('enderio:item_power_conduit:0'));
// crafting.removeByOutput(item('enderio:item_power_conduit:2'));
// rh(ore('itemInfinityGoop'));
// rh(item('enderio:item_endergy_conduit:3'));
// rh(item('enderio:item_endergy_conduit:4'));
// rh(item('enderio:item_endergy_conduit:5'));
// rh(item('enderio:item_endergy_conduit:6'));
// rh(item('enderio:item_endergy_conduit:9') * 2);
// crafting.removeByOutput(item('enderio:item_endergy_conduit:2') * 3);
// rh(item('enderio:item_endergy_conduit:1'));
// rh(item('enderio:item_endergy_conduit:0'));
// rh(item('enderio:item_endergy_conduit:10'));
// rh(item('enderio:item_endergy_conduit:7'));
// rh(item('enderio:item_endergy_conduit:8'));
// crafting.removeByOutput(item('enderio:item_endergy_conduit:11'));
// rh(ore('gearEmerald'));
// rh(item('enderio:block_lava_generator:0'));
// crafting.removeByOutput(item('draconicevolution:grinder:0'));
// crafting.removeByOutput(item('draconicevolution:wyvern_core:0'));
// crafting.removeByOutput(item('draconicevolution:draconic_core:0'));
// crafting.removeByOutput(item('gregtech:meta_item_1:350'));
// rh(item('thermalfoundation:geode:0'));
// rh(ore('itemUnsouledMachineChassi'));
// rh(item('enderio:block_enhanced_sag_mill:0'));
// rh(item('enderio:block_simple_sag_mill:0'));
// rh(item('enderio:item_capacitor_crystalline:0'));
// rh(item('enderio:item_capacitor_grainy:0'));
// rh(item('enderio:item_capacitor_vivid:0'));
// rh(item('enderio:item_capacitor_melodic:0'));
// rh(item('enderio:block_stirling_generator:0'));
// rh(item('enderio:block_sag_mill:0'));
// rh(item('enderio:block_combustion_generator:0'));
// rh(item('enderio:block_enhanced_combustion_generator:0'));
// rh(item('enderio:block_simple_stirling_generator:0'));
// rh(item('enderio:block_simple_furnace:0'));
// rh(item('enderio:block_simple_alloy_smelter:0'));
// rh(item('enderio:block_alloy_smelter:0'));
// rh(item('enderio:block_enhanced_alloy_smelter:0'));
// //Don't touch me!
// //#Add
// crafting.addShaped(ore('dustPetrotheum'), [[null, ore('dustObsidian'), null],[ore('dustObsidian'), ore('dustBlaze,itemBlazePowder'), ore('dustObsidian')], [null, ore('dustObsidian'), null]]);
// crafting.addShaped(item('thermalfoundation:material:512'), [[ore('dustRedstone'), null, ore('dustRedstone')],[null, ore('ingotIronMagnetic'), null], [ore('dustRedstone'), null, ore('dustRedstone')]]);
// crafting.addShapeless(ore('ingotAluminium') * 9, [ore('blockAluminium')]);
// crafting.addShapeless(ore('ingotInvar') *9, [item('gregtech:meta_block_compressed_7:14')]);
// crafting.addShaped(ore('ingotSilver') * 9, [[null, null, null],[null, item('gregtech:meta_block_compressed_3:14'), null], [null, null, null]]);
// crafting.addShaped(ore('ingotNickel') * 9, [[null, null, null],[null, item('gregtech:meta_block_compressed_2:12'), null], [null, null, null]]);
// crafting.addShapeless(ore('ingotElectrum') * 9, [item('gregtech:meta_block_compressed_7')]);
// crafting.addShapeless(ore('ingotIridium')* 9, [ore('blockIridium')]);
// crafting.addShapeless(ore('ingotSteel') * 9, [item('gregtech:meta_block_compressed_11:8')]);
// crafting.addShapeless(ore('ingotBronze')* 9, [ore('lampGtGray')]);
// crafting.addShapeless(ore('ingotLead') * 9, [item('gregtech:meta_block_compressed_2:3')]);
// crafting.addShaped(item('gregtech:meta_block_compressed_2:3'), [[ore('ingotLead'), ore('ingotLead'), ore('ingotLead')],[ore('ingotLead'), ore('ingotLead'), ore('ingotLead')], [ore('ingotLead'), ore('ingotLead'), ore('ingotLead')]]);
// crafting.addShaped(ore('blockTitanium'), [[ore('ingotTitanium'), ore('ingotTitanium'), ore('ingotTitanium')],[ore('ingotTitanium'), ore('ingotTitanium'), ore('ingotTitanium')], [ore('ingotTitanium'), ore('ingotTitanium'), ore('ingotTitanium')]]);
// //crafting.addShaped(item('storagedrawers:upgrade_creative:0'), [[item('gregtech:mte:1570'), item('gregtech:mte:1570'), item('gregtech:mte:1570')],[item('gregtech:mte:1570'), item('draconicevolution:draconium_chest:0'), item('gregtech:mte:1570')], [item('gregtech:mte:1570'), item('gregtech:mte:1570'), item('gregtech:mte:1570')]]);
// //crafting.addShaped(item('appliedenergistics2:creative_storage_cell:0'), [[ore('plateDenseNeutronium'), ore('plateDenseNeutronium'), item('draconicevolution:draconium_chest:0')],[ore('plateDenseNeutronium'), item('gtadditions:ga_meta_item:32124').withTag({Charge: 9223372036854775807 as long}), ore('plateDenseNeutronium')], [ore('plateDenseNeutronium'), ore('plateDenseNeutronium'), ore('plateDenseNeutronium')]]);
// crafting.addShaped(item('minecraft:end_rod:0'), [[null, ore('itemBlazeRod,rodBlaze,stickBlaze'), null],[null, ore('endstone,oc:stoneEndstone,stoneEndstone'), null], [ore('endstone,oc:stoneEndstone,stoneEndstone'), ore('ingotTitanium'), ore('endstone,oc:stoneEndstone,stoneEndstone')]]);
// crafting.addShaped(item('gregtech:machine:2534') * 3, [[ore('craftingFurnace'), ore('craftingFurnace'), ore('craftingFurnace')],[ore('circuitMv'), item('gregtech:metal_casing:2'), ore('circuitMv')], [ore('cableGtSingleTin'), ore('circuitMv'), ore('cableGtSingleTin')]]);
// furnace.addRecipe(ore('dustQuartzBlack'), ore('dustQuartzite'), 0.0);
// furnace.addRecipe(ore('ingotSilicon'), ore('dustSilicon'), 0.0);
// furnace.addRecipe(item('thermalfoundation:material:833'),item('gregtech:meta_item_1:438'), 0.0);
// crafting.addShapeless(ore('seedWheat')* 3, [ore('cropWheat,itemWheat')]);
// furnace.addRecipe(ore('ingotWroughtIron'),ore('ingotIron'), 0.0);
// crafting.addShapeless(item('gregtech:meta_item_1:2026'), [ore('dustGold')]);
// crafting.addShaped(item('enderio:item_redstone_conduit:0') * 8, [[ore('itemConduitBinder'), ore('itemConduitBinder'), ore('itemConduitBinder')],[ore('ingotRedAlloy'), ore('ingotRedAlloy'), ore('ingotRedAlloy')], [ore('itemConduitBinder'), ore('itemConduitBinder'), ore('itemConduitBinder')]]);
// crafting.addShaped(ore('skullZombieController'), [[ore('ingotSoularium'), ore('ingotIron'), ore('ingotSoularium')],[ore('dustSilicon'), ore('itemSkull'), ore('dustSilicon')], [ore('dustSilicon'), item('minecraft:redstone_block'), ore('dustSilicon')]]);
// crafting.addShaped(item('appliedenergistics2:quartz_glass:0') * 4, [[item('gregtech:meta_item_1:2202'), ore('blockGlassColorless'), item('gregtech:meta_item_1:2202')],[ore('blockGlassColorless'), null, ore('blockGlassColorless')], [item('gregtech:meta_item_1:2202'), ore('blockGlassColorless'), item('gregtech:meta_item_1:2202')]]);
// crafting.addShaped(item('appliedenergistics2:quartz_glass:0') * 4, [[item('gregtech:meta_item_1:2201'), ore('blockGlassColorless'), item('gregtech:meta_item_1:2201')],[ore('blockGlassColorless'), null, ore('blockGlassColorless')], [item('gregtech:meta_item_1:2201'), ore('blockGlassColorless'), item('gregtech:meta_item_1:2201')]]);
// crafting.addShapeless(item('gregtech:meta_item_1:2202'), [ore('dustCertusQuartz')]);
// crafting.addShapeless(ore('itemBlazeRod,rodBlaze,stickBlaze'), [item('minecraft:brewing_stand:0')]);
// crafting.addShapeless(item('gregtech:meta_item_1:2201'), [ore('dustNetherQuartz,dustQuartz')]);
// crafting.addShapeless(item('minecraft:clay_ball') * 4, [ore('blockClay,oreClay')]);
// crafting.addShapeless(ore('dustCoal'), [ore('dustCoal')]);
// crafting.addShapeless(ore('dustCopper'), [ore('ingotCopper'),item('gregtech:meta_tool:12')]);
// crafting.addShapeless(ore('dustIron'), [ore('ingotIron'),item('gregtech:meta_tool:12')]);
// crafting.addShapeless(ore('dustCoal'),[ore('coal,gemCoal,itemCoal'),item('gregtech:meta_tool:12')]);
// crafting.addShapeless(ore('itemSoulMachineChassi'), [ore('dyeSoulMachine'),ore('itemMachineChassi')]);
// crafting.addShapeless(ore('itemEnhancedMachineChassi'), [ore('ingotDarkSteel'),ore('itemMachineChassi')]);
// crafting.addShaped(item('enderio:item_endergy_conduit:2') * 8, [[ore('itemConduitBinder'), ore('itemConduitBinder'), ore('itemConduitBinder')],[ore('ingotAluminium'), ore('itemConduitBinder'), ore('ingotAluminium')], [ore('itemConduitBinder'), ore('itemConduitBinder'), ore('itemConduitBinder')]]);
// crafting.addShaped(item('enderio:item_power_conduit:0') * 8, [[ore('itemConduitBinder'), ore('itemConduitBinder'), ore('itemConduitBinder')],[ore('ingotStainlessSteel'),item('enderio:item_endergy_conduit:2'), ore('ingotStainlessSteel')], [ore('itemConduitBinder'), ore('itemConduitBinder'), ore('itemConduitBinder')]]);
// crafting.addShaped(item('enderio:item_power_conduit:1') * 8, [[ore('itemConduitBinder'), ore('itemConduitBinder'), ore('itemConduitBinder')],[ore('ingotTitanium'), item('enderio:item_power_conduit:0'), ore('ingotTitanium')], [ore('itemConduitBinder'), ore('itemConduitBinder'), ore('itemConduitBinder')]]);
// crafting.addShaped(item('enderio:item_power_conduit:2') * 8, [[ore('itemConduitBinder'), ore('itemConduitBinder'), ore('itemConduitBinder')],[ore('ingotTungstenSteel'), item('enderio:item_power_conduit:1'), ore('ingotTungstenSteel')], [ore('itemConduitBinder'), ore('itemConduitBinder'), ore('itemConduitBinder')]]);
// crafting.addShaped(item('enderio:item_endergy_conduit:11') * 8, [[ore('itemConduitBinder'), ore('itemConduitBinder'), ore('itemConduitBinder')],[item('gregtech:cable:354'), item('gregtech:cable:354'), item('gregtech:cable:354')], [ore('itemConduitBinder'), ore('itemConduitBinder'), ore('itemConduitBinder')]]);
// //crafting.addShaped(item('draconicevolution:draconic_core:0'), [[ore('ingotDraconium'), ore('ingotTitanium'), ore('ingotDraconium')],[ore('ingotTitanium'), item('gregtech:meta_item_1:32673'), ore('ingotTitanium')], [ore('ingotDraconium'), ore('ingotTitanium'), ore('ingotDraconium')]]);
// //crafting.addShaped(item('draconicevolution:wyvern_core:0'), [[ore('ingotDraconium'), item('draconicevolution:draconic_core:0'), ore('ingotDraconium')],[item('draconicevolution:draconic_core:0'), item('gregtech:meta_item_1:206'), item('draconicevolution:draconic_core:0')], [ore('ingotDraconium'), item('draconicevolution:draconic_core:0'), ore('ingotDraconium')]]);
// crafting.addShaped(item('gregtech:meta_item_1:350') * 4, [[item('minecraft:clay_ball'), item('minecraft:clay_ball'), item('minecraft:clay_ball')],[ore('sand'), item('gregtech:meta_item_1:348'), ore('sand')], [ore('sand'), ore('sand'), ore('sand')]]);
// crafting.addShapeless(ore('itemMachineChassi'),[ore('dyeBlack'),ore('itemSimpleMachineChassi')]);
// //File End