name = "Technological Journey CEu"
author = "Pixdane"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aae0513a12b37defc8eb0676b11617a1927e5a7729997121012924ddaea4d692"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
