name = "Technological Journey"
author = "Technological Journey Dev team"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9759cb4f9af3a5c3ac66d81f6af15dfc953a06c0318ba74dc317aab43f9d1118"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
