package postInit

import classes.utils.TJUtility.Tier

ore_dict.with {
    // itemSilicon
    remove 'itemSilicon', item('appliedenergistics2:material', 5)

    remove 'itemSilicon', item('enderio:item_material', 5)
    remove 'itemSilicon', item('libvulpes:productingot', 3)
    add 'itemSilicon', metaitem('dustSilicon')

    // dustQuartz
    add 'dustQuartz', metaitem('dustNetherQuartz')

    // blockWarpCoreRim
    remove 'blockWarpCoreRim', item('libvulpes:metal0', 7)
    add 'blockWarpCoreRim', metaitem('blockTitanium')

    remove 'oreCopper', item('thermalfoundation:ore')
    remove 'oreTin', item('thermalfoundation:ore', 1)
    remove 'oreSilver', item('thermalfoundation:ore', 2)
    remove 'oreLead', item('thermalfoundation:ore', 3)
    remove 'oreAluminum', item('thermalfoundation:ore', 4)
    remove 'oreNickel', item('thermalfoundation:ore', 5)
    remove 'orePlatinum', item('thermalfoundation:ore', 6)
    remove 'oreIridium', item('thermalfoundation:ore', 7)
    remove 'blockCopper', item('thermalfoundation:storage')
    remove 'blockTin', item('thermalfoundation:storage', 1)
    remove 'blockSilver', item('thermalfoundation:storage', 2)
    remove 'blockLead', item('thermalfoundation:storage', 3)
    remove 'blockAluminum', item('thermalfoundation:storage', 4)
    remove 'blockNickel', item('thermalfoundation:storage', 5)
    remove 'blockPlatinum', item('thermalfoundation:storage', 6)
    remove 'blockIridium', item('thermalfoundation:storage', 7)
    remove 'blockSteel', item('thermalfoundation:storage_alloy')
    remove 'blockElectrum', item('thermalfoundation:storage_alloy', 1)
    remove 'blockInvar', item('thermalfoundation:storage_alloy', 2)
    remove 'blockBronze', item('thermalfoundation:storage_alloy', 3)
    remove 'blockEnderium', item('thermalfoundation:storage_alloy', 7)
    remove 'blockCharcoal', item('thermalfoundation:storage_resource')
    remove 'blockFuelCoke', item('thermalfoundation:storage_resource', 1)

    remove 'ingotCopper', item('thermalfoundation:material', 128)
    remove 'ingotTin', item('thermalfoundation:material', 129)
    remove 'ingotSilver', item('thermalfoundation:material', 130)
    remove 'ingotLead', item('thermalfoundation:material', 131)
    remove 'ingotAluminium', item('thermalfoundation:material', 132)
    remove 'ingotAluminum', item('thermalfoundation:material', 132)
    remove 'ingotNickel', item('thermalfoundation:material', 133)
    remove 'ingotPlatinum', item('thermalfoundation:material', 134)
    remove 'ingotIridium', item('thermalfoundation:material', 135)
    remove 'ingotSteel', item('thermalfoundation:material', 160)
    remove 'ingotElectrum', item('thermalfoundation:material', 161)
    remove 'ingotInvar', item('thermalfoundation:material', 162)
    remove 'ingotBronze', item('thermalfoundation:material', 163)
    remove 'ingotEnderium', item('thermalfoundation:material', 167)

    remove 'dustIron', item('thermalfoundation:material')
    remove 'dustGold', item('thermalfoundation:material', 1)
    remove 'dustCopper', item('thermalfoundation:material', 64)
    remove 'dustTin', item('thermalfoundation:material', 65)
    remove 'dustSilver', item('thermalfoundation:material', 66)
    remove 'dustLead', item('thermalfoundation:material', 67)
    remove 'dustAluminum', item('thermalfoundation:material', 68)
    remove 'dustNickel', item('thermalfoundation:material', 69)
    remove 'dustPlatinum', item('thermalfoundation:material', 70)
    remove 'dustIridium', item('thermalfoundation:material', 71)
    remove 'dustSteel', item('thermalfoundation:material', 96)
    remove 'dustElectrum', item('thermalfoundation:material', 97)
    remove 'dustInvar', item('thermalfoundation:material', 98)
    remove 'dustBronze', item('thermalfoundation:material', 99)
    remove 'dustEnderium', item('thermalfoundation:material', 103)
    remove 'dustCoal', item('thermalfoundation:material', 768)
    remove 'dustCharcoal', item('thermalfoundation:material', 769)
    remove 'dustObsidian', item('thermalfoundation:material', 770)
    remove 'dustSulfur', item('thermalfoundation:material', 771)
    remove 'dustSaltpeter', item('thermalfoundation:material', 772)
    remove 'dustWood', item('thermalfoundation:material', 800)
    remove 'dustWood', item('thermalfoundation:material', 800)

    remove 'nuggetDiamond', item('thermalfoundation:material', 16)
    remove 'nuggetEmerald', item('thermalfoundation:material', 17)
    remove 'nuggetCopper', item('thermalfoundation:material', 192)
    remove 'nuggetTin', item('thermalfoundation:material', 193)
    remove 'nuggetSilver', item('thermalfoundation:material', 194)
    remove 'nuggetLead', item('thermalfoundation:material', 195)
    remove 'nuggetAluminium', item('thermalfoundation:material', 196)
    remove 'nuggetAluminum', item('thermalfoundation:material', 196)
    remove 'nuggetNickel', item('thermalfoundation:material', 197)
    remove 'nuggetPlatinum', item('thermalfoundation:material', 198)
    remove 'nuggetIridium', item('thermalfoundation:material', 199)
    remove 'nuggetSteel', item('thermalfoundation:material', 224)
    remove 'nuggetElectrum', item('thermalfoundation:material', 225)
    remove 'nuggetInvar', item('thermalfoundation:material', 226)
    remove 'nuggetBronze', item('thermalfoundation:material', 227)
    remove 'nuggetEnderium', item('thermalfoundation:material', 231)

    remove 'plateIron', item('thermalfoundation:material', 32)
    remove 'plateGold', item('thermalfoundation:material', 33)
    remove 'plateCopper', item('thermalfoundation:material', 320)
    remove 'plateTin', item('thermalfoundation:material', 321)
    remove 'plateSilver', item('thermalfoundation:material', 322)
    remove 'plateLead', item('thermalfoundation:material', 323)
    remove 'plateAluminum', item('thermalfoundation:material', 324)
    remove 'plateNickel', item('thermalfoundation:material', 325)
    remove 'platePlatinum', item('thermalfoundation:material', 326)
    remove 'plateIridium', item('thermalfoundation:material', 327)
    remove 'plateSteel', item('thermalfoundation:material', 352)
    remove 'plateElectrum', item('thermalfoundation:material', 353)
    remove 'plateInvar', item('thermalfoundation:material', 354)
    remove 'plateBronze', item('thermalfoundation:material', 355)
    remove 'plateEnderium', item('thermalfoundation:material', 359)

    remove 'gearWood', item('thermalfoundation:material', 22)
    remove 'gearStone', item('thermalfoundation:material', 23)
    remove 'gearIron', item('thermalfoundation:material', 24)
    remove 'gearGold', item('thermalfoundation:material', 25)
    remove 'gearDiamond', item('thermalfoundation:material', 26)
    remove 'gearEmerald', item('thermalfoundation:material', 27)
    remove 'gearCopper', item('thermalfoundation:material', 256)
    remove 'gearTin', item('thermalfoundation:material', 257)
    remove 'gearSilver', item('thermalfoundation:material', 258)
    remove 'gearLead', item('thermalfoundation:material', 259)
    remove 'gearAluminum', item('thermalfoundation:material', 260)
    remove 'gearNickel', item('thermalfoundation:material', 261)
    remove 'gearPlatinum', item('thermalfoundation:material', 262)
    remove 'gearIridium', item('thermalfoundation:material', 263)
    remove 'gearSteel', item('thermalfoundation:material', 288)
    remove 'gearElectrum', item('thermalfoundation:material', 289)
    remove 'gearInvar', item('thermalfoundation:material', 290)
    remove 'gearBronze', item('thermalfoundation:material', 291)
    remove 'gearEnderium', item('thermalfoundation:material', 295)

    remove 'oreCopper', item('libvulpes:ore0', 4)
    remove 'oreTin', item('libvulpes:ore0', 5)
    remove 'oreRutile', item('libvulpes:ore0', 8)
    remove 'oreTitanium', item('libvulpes:ore0', 8)
    remove 'oreAluminum', item('libvulpes:ore0', 9)
    remove 'oreIridium', item('libvulpes:ore0', 10)

    remove 'ingotSilicon', item('libvulpes:productingot', 3)
    remove 'ingotCopper', item('libvulpes:productingot', 4)
    remove 'ingotTin', item('libvulpes:productingot', 5)
    remove 'ingotSteel', item('libvulpes:productingot', 6)
    remove 'ingotTitanium', item('libvulpes:productingot', 7)
    remove 'ingotAluminum', item('libvulpes:productingot', 9)
    remove 'ingotIridium', item('libvulpes:productingot', 10)

    remove 'blockCopper', item('libvulpes:metal0', 4)
    remove 'blockTin', item('libvulpes:metal0', 5)
    remove 'blockSteel', item('libvulpes:metal0', 6)
    remove 'blockTitanium', item('libvulpes:metal0', 7)
    remove 'blockAluminum', item('libvulpes:metal0', 9)
    remove 'blockIridium', item('libvulpes:metal0', 10)

    remove 'plateIron', item('libvulpes:productplate', 1)
    remove 'plateGold', item('libvulpes:productplate', 2)
    remove 'plateSilicon', item('libvulpes:productplate', 3)
    remove 'plateCopper', item('libvulpes:productplate', 4)
    remove 'plateTin', item('libvulpes:productplate', 5)
    remove 'plateSteel', item('libvulpes:productplate', 6)
    remove 'plateTitanium', item('libvulpes:productplate', 7)
    remove 'plateAluminum', item('libvulpes:productplate', 9)
    remove 'plateIridium', item('libvulpes:productplate', 10)

    remove 'dustIron', item('libvulpes:productdust', 1)
    remove 'dustGold', item('libvulpes:productdust', 2)
    remove 'dustSilicon', item('libvulpes:productdust', 3)
    remove 'dustCopper', item('libvulpes:productdust', 4)
    remove 'dustTin', item('libvulpes:productdust', 5)
    remove 'dustSteel', item('libvulpes:productdust', 6)
    remove 'dustTitanium', item('libvulpes:productdust', 7)
    remove 'dustAluminum', item('libvulpes:productdust', 9)
    remove 'dustIridium', item('libvulpes:productdust', 10)

    remove 'nuggetSilicon', item('libvulpes:productnugget', 3)
    remove 'nuggetCopper', item('libvulpes:productnugget', 4)
    remove 'nuggetTin', item('libvulpes:productnugget', 5)
    remove 'nuggetSteel', item('libvulpes:productnugget', 6)
    remove 'nuggetTitanium', item('libvulpes:productnugget', 7)
    remove 'nuggetAluminum', item('libvulpes:productnugget', 9)
    remove 'nuggetIridium', item('libvulpes:productnugget', 10)

    remove 'gearSteel', item('libvulpes:productgear', 6)
    remove 'gearTitanium', item('libvulpes:productgear', 7)

    remove 'stickIron', item('libvulpes:productrod', 1)
    remove 'stickCopper', item('libvulpes:productrod', 4)
    remove 'stickSteel', item('libvulpes:productrod', 6)
    remove 'stickTitanium', item('libvulpes:productrod', 7)
    remove 'stickIridium', item('libvulpes:productrod', 10)

    remove 'dustIron', item('actuallyadditions:item_dust')
    remove 'dustGold', item('actuallyadditions:item_dust', 1)
    remove 'dustDiamond', item('actuallyadditions:item_dust', 2)
    remove 'dustEmerald', item('actuallyadditions:item_dust', 3)
    remove 'dustLapis', item('actuallyadditions:item_dust', 4)
    remove 'dustQuartz', item('actuallyadditions:item_dust', 5)
    remove 'dustNetherQuartz', item('actuallyadditions:item_dust', 5)
    remove 'dustCoal', item('actuallyadditions:item_dust', 6)

    Tier.ULV..Tier.UEV.each { tier ->
        remove(
                "circuit.${tier.lc()}".toString(),
                metaitem("gcyl:circuit.resonatic.${tier.lc()}".toString())
        )
    }
}