package postInit

import classes.utils.TJUtility.Tier

// itemSilicon
ore_dict.remove('itemSilicon', item('appliedenergistics2:material', 5))
ore_dict.remove('itemSilicon', item('enderio:item_material', 5))
ore_dict.remove('itemSilicon', item('libvulpes:productingot', 3))
ore_dict.add('itemSilicon', metaitem('dustSilicon'))

// dustQuartz
ore_dict.add('dustQuartz', metaitem('dustNetherQuartz'))

// blockWarpCoreRim
ore_dict.remove('blockWarpCoreRim', item('libvulpes:metal0', 7))
ore_dict.add('blockWarpCoreRim', metaitem('blockTitanium'))

ore_dict.remove('oreCopper', item('thermalfoundation:ore'))
ore_dict.remove('oreTin', item('thermalfoundation:ore', 1))
ore_dict.remove('oreSilver', item('thermalfoundation:ore', 2))
ore_dict.remove('oreLead', item('thermalfoundation:ore', 3))
ore_dict.remove('oreAluminum', item('thermalfoundation:ore', 4))
ore_dict.remove('oreNickel', item('thermalfoundation:ore', 5))
ore_dict.remove('orePlatinum', item('thermalfoundation:ore', 6))
ore_dict.remove('oreIridium', item('thermalfoundation:ore', 7))
ore_dict.remove('blockCopper', item('thermalfoundation:storage'))
ore_dict.remove('blockTin', item('thermalfoundation:storage', 1))
ore_dict.remove('blockSilver', item('thermalfoundation:storage', 2))
ore_dict.remove('blockLead', item('thermalfoundation:storage', 3))
ore_dict.remove('blockAluminum', item('thermalfoundation:storage', 4))
ore_dict.remove('blockNickel', item('thermalfoundation:storage', 5))
ore_dict.remove('blockPlatinum', item('thermalfoundation:storage', 6))
ore_dict.remove('blockIridium', item('thermalfoundation:storage', 7))
ore_dict.remove('blockSteel', item('thermalfoundation:storage_alloy'))
ore_dict.remove('blockElectrum', item('thermalfoundation:storage_alloy', 1))
ore_dict.remove('blockInvar', item('thermalfoundation:storage_alloy', 2))
ore_dict.remove('blockBronze', item('thermalfoundation:storage_alloy', 3))
ore_dict.remove('blockEnderium', item('thermalfoundation:storage_alloy', 7))
ore_dict.remove('blockCharcoal', item('thermalfoundation:storage_resource'))
ore_dict.remove('blockFuelCoke', item('thermalfoundation:storage_resource', 1))

ore_dict.remove('ingotCopper', item('thermalfoundation:material', 128))
ore_dict.remove('ingotTin', item('thermalfoundation:material', 129))
ore_dict.remove('ingotSilver', item('thermalfoundation:material', 130))
ore_dict.remove('ingotLead', item('thermalfoundation:material', 131))
ore_dict.remove('ingotAluminium', item('thermalfoundation:material', 132))
ore_dict.remove('ingotAluminum', item('thermalfoundation:material', 132))
ore_dict.remove('ingotNickel', item('thermalfoundation:material', 133))
ore_dict.remove('ingotPlatinum', item('thermalfoundation:material', 134))
ore_dict.remove('ingotIridium', item('thermalfoundation:material', 135))
ore_dict.remove('ingotSteel', item('thermalfoundation:material', 160))
ore_dict.remove('ingotElectrum', item('thermalfoundation:material', 161))
ore_dict.remove('ingotInvar', item('thermalfoundation:material', 162))
ore_dict.remove('ingotBronze', item('thermalfoundation:material', 163))
ore_dict.remove('ingotEnderium', item('thermalfoundation:material', 167))

ore_dict.remove('dustIron', item('thermalfoundation:material'))
ore_dict.remove('dustGold', item('thermalfoundation:material', 1))
ore_dict.remove('dustCopper', item('thermalfoundation:material', 64))
ore_dict.remove('dustTin', item('thermalfoundation:material', 65))
ore_dict.remove('dustSilver', item('thermalfoundation:material', 66))
ore_dict.remove('dustLead', item('thermalfoundation:material', 67))
ore_dict.remove('dustAluminum', item('thermalfoundation:material', 68))
ore_dict.remove('dustNickel', item('thermalfoundation:material', 69))
ore_dict.remove('dustPlatinum', item('thermalfoundation:material', 70))
ore_dict.remove('dustIridium', item('thermalfoundation:material', 71))
ore_dict.remove('dustSteel', item('thermalfoundation:material', 96))
ore_dict.remove('dustElectrum', item('thermalfoundation:material', 97))
ore_dict.remove('dustInvar', item('thermalfoundation:material', 98))
ore_dict.remove('dustBronze', item('thermalfoundation:material', 99))
ore_dict.remove('dustEnderium', item('thermalfoundation:material', 103))
ore_dict.remove('dustCoal', item('thermalfoundation:material', 768))
ore_dict.remove('dustCharcoal', item('thermalfoundation:material', 769))
ore_dict.remove('dustObsidian', item('thermalfoundation:material', 770))
ore_dict.remove('dustSulfur', item('thermalfoundation:material', 771))
ore_dict.remove('dustSaltpeter', item('thermalfoundation:material', 772))
ore_dict.remove('dustWood', item('thermalfoundation:material', 800))
ore_dict.remove('dustWood', item('thermalfoundation:material', 800))

ore_dict.remove('nuggetDiamond', item('thermalfoundation:material', 16))
ore_dict.remove('nuggetEmerald', item('thermalfoundation:material', 17))
ore_dict.remove('nuggetCopper', item('thermalfoundation:material', 192))
ore_dict.remove('nuggetTin', item('thermalfoundation:material', 193))
ore_dict.remove('nuggetSilver', item('thermalfoundation:material', 194))
ore_dict.remove('nuggetLead', item('thermalfoundation:material', 195))
ore_dict.remove('nuggetAluminium', item('thermalfoundation:material', 196))
ore_dict.remove('nuggetAluminum', item('thermalfoundation:material', 196))
ore_dict.remove('nuggetNickel', item('thermalfoundation:material', 197))
ore_dict.remove('nuggetPlatinum', item('thermalfoundation:material', 198))
ore_dict.remove('nuggetIridium', item('thermalfoundation:material', 199))
ore_dict.remove('nuggetSteel', item('thermalfoundation:material', 224))
ore_dict.remove('nuggetElectrum', item('thermalfoundation:material', 225))
ore_dict.remove('nuggetInvar', item('thermalfoundation:material', 226))
ore_dict.remove('nuggetBronze', item('thermalfoundation:material', 227))
ore_dict.remove('nuggetEnderium', item('thermalfoundation:material', 231))

ore_dict.remove('plateIron', item('thermalfoundation:material', 32))
ore_dict.remove('plateGold', item('thermalfoundation:material', 33))
ore_dict.remove('plateCopper', item('thermalfoundation:material', 320))
ore_dict.remove('plateTin', item('thermalfoundation:material', 321))
ore_dict.remove('plateSilver', item('thermalfoundation:material', 322))
ore_dict.remove('plateLead', item('thermalfoundation:material', 323))
ore_dict.remove('plateAluminum', item('thermalfoundation:material', 324))
ore_dict.remove('plateNickel', item('thermalfoundation:material', 325))
ore_dict.remove('platePlatinum', item('thermalfoundation:material', 326))
ore_dict.remove('plateIridium', item('thermalfoundation:material', 327))
ore_dict.remove('plateSteel', item('thermalfoundation:material', 352))
ore_dict.remove('plateElectrum', item('thermalfoundation:material', 353))
ore_dict.remove('plateInvar', item('thermalfoundation:material', 354))
ore_dict.remove('plateBronze', item('thermalfoundation:material', 355))
ore_dict.remove('plateEnderium', item('thermalfoundation:material', 359))

ore_dict.remove('gearWood', item('thermalfoundation:material', 22))
ore_dict.remove('gearStone', item('thermalfoundation:material', 23))
ore_dict.remove('gearIron', item('thermalfoundation:material', 24))
ore_dict.remove('gearGold', item('thermalfoundation:material', 25))
ore_dict.remove('gearDiamond', item('thermalfoundation:material', 26))
ore_dict.remove('gearEmerald', item('thermalfoundation:material', 27))
ore_dict.remove('gearCopper', item('thermalfoundation:material', 256))
ore_dict.remove('gearTin', item('thermalfoundation:material', 257))
ore_dict.remove('gearSilver', item('thermalfoundation:material', 258))
ore_dict.remove('gearLead', item('thermalfoundation:material', 259))
ore_dict.remove('gearAluminum', item('thermalfoundation:material', 260))
ore_dict.remove('gearNickel', item('thermalfoundation:material', 261))
ore_dict.remove('gearPlatinum', item('thermalfoundation:material', 262))
ore_dict.remove('gearIridium', item('thermalfoundation:material', 263))
ore_dict.remove('gearSteel', item('thermalfoundation:material', 288))
ore_dict.remove('gearElectrum', item('thermalfoundation:material', 289))
ore_dict.remove('gearInvar', item('thermalfoundation:material', 290))
ore_dict.remove('gearBronze', item('thermalfoundation:material', 291))
ore_dict.remove('gearEnderium', item('thermalfoundation:material', 295))

ore_dict.remove('oreCopper', item('libvulpes:ore0', 4))
ore_dict.remove('oreTin', item('libvulpes:ore0', 5))
ore_dict.remove('oreRutile', item('libvulpes:ore0', 8))
ore_dict.remove('oreTitanium', item('libvulpes:ore0', 8))
ore_dict.remove('oreAluminum', item('libvulpes:ore0', 9))
ore_dict.remove('oreIridium', item('libvulpes:ore0', 10))

ore_dict.remove('ingotSilicon', item('libvulpes:productingot', 3))
ore_dict.remove('ingotCopper', item('libvulpes:productingot', 4))
ore_dict.remove('ingotTin', item('libvulpes:productingot', 5))
ore_dict.remove('ingotSteel', item('libvulpes:productingot', 6))
ore_dict.remove('ingotTitanium', item('libvulpes:productingot', 7))
ore_dict.remove('ingotAluminum', item('libvulpes:productingot', 9))
ore_dict.remove('ingotIridium', item('libvulpes:productingot', 10))

ore_dict.remove('blockCopper', item('libvulpes:metal0', 4))
ore_dict.remove('blockTin', item('libvulpes:metal0', 5))
ore_dict.remove('blockSteel', item('libvulpes:metal0', 6))
ore_dict.remove('blockTitanium', item('libvulpes:metal0', 7))
ore_dict.remove('blockAluminum', item('libvulpes:metal0', 9))
ore_dict.remove('blockIridium', item('libvulpes:metal0', 10))

ore_dict.remove('plateIron', item('libvulpes:productplate', 1))
ore_dict.remove('plateGold', item('libvulpes:productplate', 2))
ore_dict.remove('plateSilicon', item('libvulpes:productplate', 3))
ore_dict.remove('plateCopper', item('libvulpes:productplate', 4))
ore_dict.remove('plateTin', item('libvulpes:productplate', 5))
ore_dict.remove('plateSteel', item('libvulpes:productplate', 6))
ore_dict.remove('plateTitanium', item('libvulpes:productplate', 7))
ore_dict.remove('plateAluminum', item('libvulpes:productplate', 9))
ore_dict.remove('plateIridium', item('libvulpes:productplate', 10))

ore_dict.remove('dustIron', item('libvulpes:productdust', 1))
ore_dict.remove('dustGold', item('libvulpes:productdust', 2))
ore_dict.remove('dustSilicon', item('libvulpes:productdust', 3))
ore_dict.remove('dustCopper', item('libvulpes:productdust', 4))
ore_dict.remove('dustTin', item('libvulpes:productdust', 5))
ore_dict.remove('dustSteel', item('libvulpes:productdust', 6))
ore_dict.remove('dustTitanium', item('libvulpes:productdust', 7))
ore_dict.remove('dustAluminum', item('libvulpes:productdust', 9))
ore_dict.remove('dustIridium', item('libvulpes:productdust', 10))

ore_dict.remove('nuggetSilicon', item('libvulpes:productnugget', 3))
ore_dict.remove('nuggetCopper', item('libvulpes:productnugget', 4))
ore_dict.remove('nuggetTin', item('libvulpes:productnugget', 5))
ore_dict.remove('nuggetSteel', item('libvulpes:productnugget', 6))
ore_dict.remove('nuggetTitanium', item('libvulpes:productnugget', 7))
ore_dict.remove('nuggetAluminum', item('libvulpes:productnugget', 9))
ore_dict.remove('nuggetIridium', item('libvulpes:productnugget', 10))

ore_dict.remove('gearSteel', item('libvulpes:productgear', 6))
ore_dict.remove('gearTitanium', item('libvulpes:productgear', 7))

ore_dict.remove('stickIron', item('libvulpes:productrod', 1))
ore_dict.remove('stickCopper', item('libvulpes:productrod', 4))
ore_dict.remove('stickSteel', item('libvulpes:productrod', 6))
ore_dict.remove('stickTitanium', item('libvulpes:productrod', 7))
ore_dict.remove('stickIridium', item('libvulpes:productrod', 10))

ore_dict.remove('dustIron', item('actuallyadditions:item_dust'))
ore_dict.remove('dustGold', item('actuallyadditions:item_dust', 1))
ore_dict.remove('dustDiamond', item('actuallyadditions:item_dust', 2))
ore_dict.remove('dustEmerald', item('actuallyadditions:item_dust', 3))
ore_dict.remove('dustLapis', item('actuallyadditions:item_dust', 4))
ore_dict.remove('dustQuartz', item('actuallyadditions:item_dust', 5))
ore_dict.remove('dustNetherQuartz', item('actuallyadditions:item_dust', 5))
ore_dict.remove('dustCoal', item('actuallyadditions:item_dust', 6))

Tier.ULV..Tier.UEV.each { tier ->
    ore_dict.remove(
            "circuit.${tier.lc()}".toString(),
            metaitem("gcyl:circuit.resonatic.${tier.lc()}".toString())
    )
}