import gregtech.api.metatileentity.multiblock.CleanroomType

BIO_REACTOR = recipemap('bio_reactor')
ASSEMBLER = recipemap('assembler')
EBF = recipemap('electric_blast_furnace')
STELLAR_FORGE = recipemap('stellar_forge')
PLASMA_CONDENSER = recipemap('plasma_condenser')

// TODO: Change Tiny Pile Recipes & Isotopes
// Tiny Pile of Lutetium Dust * 1
mods.gregtech.large_centrifuge.removeByInput(7680, [metaitem('dustNaquadria')], [fluid('nitrogen_dioxide') * 500 * 500, fluid('sulfuric_acid') * 500 * 500])

// Actinium Nitrate Dust * 26
mods.gregtech.large_centrifuge.removeByInput(32700, null, [fluid('actinium_radium_nitrate_solution') * 13000 * 13000, fluid('theonyl_trifluoroacetate') * 500 * 500])

// Stem Cells * 2
mods.gregtech.bio_reactor.removeByInput(480, [metaitem('stem_cells')], [fluid('sterilized_growth_medium') * 1000 * 1000])

BIO_REACTOR.recipeBuilder()
        .inputs(metaitem('stem_cells'))
        .fluidInputs(fluid('sterilized_growth_medium') * 1000)
        .outputs(metaitem('stem_cells') * 2)
        .circuitMeta(1)
        .cleanroom(CleanroomType.STERILE_CLEANROOM)
        .duration(250)
        .EUt(480)
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(ore('wireGtDoubleChaosalloy') * 8)
        .inputs(metaitem('gcyl:highly_insulating_foil') * 16)
        .fluidInputs(fluid('cosmic_neutronium') * 144)
        .outputs(item('gcyl:wire_coil', 6))
        .duration(250)
        .EUt(536870900)
        .buildAndRegister()

EBF.recipeBuilder()
        .inputs(metaitem('tjceu:crystal.refined_chaos'))
        .inputs(ore('boltChaosalloy') * 8)
        .inputs(metaitem('gcyl:recursively.folded.negative.space'))
        .fluidInputs(fluid('light_quarks') * 750)
        .outputs(metaitem('tjceu:crystal.infinity'))
        .blastFurnaceTemp(19302)
        .duration(100)
        .EUt(536870900)
        .buildAndRegister()

EBF.recipeBuilder()
        .inputs(metaitem('gcyl:cosmic.fabric') * 4)
        .inputs(metaitem('gcyl:time.dilation.containment.unit'))
        .inputs(metaitem('gcyl:qcd.protective.plating'))
        .fluidInputs(fluid('taranium') * 4032)
        .outputs(metaitem('tjceu:dustEternityPreparation'))
        .blastFurnaceTemp(23000)
        .duration(50)
        .EUt(536870900)
        .buildAndRegister()

STELLAR_FORGE.recipeBuilder()
        .inputs(item('gcyl:gcyl_explosive', 3))
        .inputs(metaitem('tjceu:dustEternityPreparation') * 4)
        .inputs(metaitem('tjceu:crystal.infinity') * 2)
        .fluidInputs(fluid('gluons') * 8000)
        .fluidOutputs(fluid('plasma.eternity') * 1152)
        .duration(20)
        .EUt(536870900)
        .buildAndRegister()

PLASMA_CONDENSER.recipeBuilder()
        .fluidInputs(fluid('plasma.eternity') * 144)
        .fluidInputs(fluid('microcrystallizinghydrogen') * 5000)
        .notConsumable(metaitem('gcyl:ingot.field.shape'))
        .fluidOutputs(fluid('hydrogen') * 5000)
        .outputs(metaitem('tjceu:ingotEternity'))
        .duration(40)
        .EUt(536870900)
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('tjceu:blockEternity'))
        .inputs(ore('wireGtHexMaxSuperconductor') * 8)
        .inputs(metaitem('gcyl:highly_insulating_foil') * 32)
        .inputs(metaitem('field.generator.opv'))
        .fluidInputs(fluid('chaosalloy') * 288)
        .outputs(item('gcyl:wire_coil', 7))
        .duration(100)
        .EUt(536870900)
        .buildAndRegister()

EBF.recipeBuilder()
        .inputs(metaitem('gcyl:eigenfolded.kerr.manifold'))
        .inputs(metaitem('gcyl:cosmic.fabric') * 8)
        .inputs(metaitem('tjceu:crystal.infinity'))
        .fluidInputs(fluid('high_energy_qgp') * 288)
        .outputs(metaitem('tjceu:crystal.eternity'))
        .blastFurnaceTemp(51237)
        .duration(10000)
        .EUt(536870900)
        .buildAndRegister()

//TODO: from OtherRecipes

// LCR.recipeBuilder()
//         .inputs(ore('dustSodaAsh') * 6)
//         .fluidInputs(fluid('water') * 1000)
//         .circuitMeta(1)
//         .outputs(item('gtadditions:ga_dust', 194) * 6)
//         .outputs(ore('dustSodiumHydroxide') * 3)
//         .duration(140)
//         .EUt(30)
//         .buildAndRegister()

// Sodium Bicarbonate Dust * 6
// TODO: wrong stoichiometry, report to GCYL:CEu
mods.gregtech.large_chemical_reactor.removeByInput(30, [metaitem('circuit.integrated').withNbt(['Configuration': 2]), metaitem('dustSodaAsh')], [fluid('water') * 1000])


// LCR.recipeBuilder()
//         .inputs(ore('dustSodaAsh') * 6)
//         .fluidInputs(fluid('water') * 2000)
//         .fluidInputs(fluid('epichlorhydrin') * 1000)
//         .circuitMeta(2)
//         .outputs(ore('dustSalt') * 2)
//         .outputs(item('gtadditions:ga_dust', 194) * 6)
//         .fluidOutputs([fluid('glycerol') * 1000])
//         .duration(100)
//         .EUt(1024)
//         .buildAndRegister()

// TODO: should TJCEu item recipes be moved to individual files?
// crafting.addShaped(metaitem('tjceu:steam.motor.ulv'), [[ore('stickWood'), ore('plateBronze'), ore('stickIron')], [ore('plateBronze'), ore('stickIron'), ore('plateBronze')], [ore('ingotIron'), ore('plateBronze'), ore('stickWood')]])

// furnace.addRecipe(ore('ingotGold'), ore('blockPreciousMetal'), 0.0)


// extruder.recipeBuilder()
//         .inputs(ore('blockTritanium') * 64)
//         .inputs(ore('blockTritanium') * 64)
//         .outputs(item('contenttweaker:certificate_of_being_a_noob'))
//         .duration(30000000)
//         .EUt(3)
//         .buildAndRegister()

// ASSEMBLER.recipeBuilder()
//         .inputs(item('enderio:block_reservoir') * 4)
//         .inputs(item('gregtech:mte', 987))
//         .outputs(item('gcyl:gcyl_meta_item', 571))
//         .duration(200)
//         .EUt(110)
//         .buildAndRegister()

// ASSEMBLER.recipeBuilder()
//         .inputs(item('enderio:block_reservoir') * 4)
//         .inputs(metaitem('hull.hv'))
//         .outputs(item('gcyl:gcyl_meta_item', 572))
//         .duration(200)
//         .EUt(500)
//         .buildAndRegister()

// ASSEMBLER.recipeBuilder()
//         .inputs(item('enderio:block_reservoir') * 4)
//         .inputs(metaitem('hull.ev'))
//         .outputs(item('gcyl:gcyl_meta_item', 573))
//         .duration(200)
//         .EUt(2048)
//         .buildAndRegister()

// ASSEMBLER.recipeBuilder()
//         .inputs(item('enderio:block_reservoir') * 4)
//         .inputs(item('gregtech:mte', 990))
//         .outputs(item('gcyl:gcyl_meta_item', 574))
//         .duration(200)
//         .EUt(8192)
//         .buildAndRegister()

// ASSEMBLER.recipeBuilder()
//         .inputs(item('enderio:block_reservoir') * 4)
//         .inputs(item('gregtech:mte', 991))
//         .outputs(item('gcyl:gcyl_meta_item', 575))
//         .duration(200)
//         .EUt(32768)
//         .buildAndRegister()


// ASSEMBLER.recipeBuilder()
//         .inputs(item('enderio:block_reservoir') * 4)
//         .inputs(item('gregtech:mte', 992))
//         .outputs(item('gcyl:gcyl_meta_item', 576))
//         .duration(200)
//         .EUt(131072)
//         .buildAndRegister()

// ASSEMBLER.recipeBuilder()
//         .inputs(item('enderio:block_reservoir') * 4)
//         .inputs(item('gregtech:mte', 993))
//         .outputs(item('gcyl:gcyl_meta_item', 577))
//         .duration(200)
//         .EUt(524288)
//         .buildAndRegister()

// //Upgrade recipes

// ASSEMBLER.recipeBuilder()
//         .inputs(item('enderio:block_reservoir') * 4)
//         .inputs(item('gregtech:mte', 987))
//         .outputs(item('gcyl:gcyl_meta_item', 571))
//         .duration(200)
//         .EUt(110)
//         .buildAndRegister()

// ASSEMBLER.recipeBuilder()
//         .inputs(item('enderio:block_reservoir') * 4)
//         .inputs(item('gcyl:gcyl_meta_item', 572))
//         .outputs(item('gcyl:gcyl_meta_item', 573))
//         .duration(200)
//         .EUt(2048)
//         .buildAndRegister()

// ASSEMBLER.recipeBuilder()
//         .inputs(item('enderio:block_reservoir') * 4)
//         .inputs(item('gcyl:gcyl_meta_item', 573))
//         .outputs(item('gcyl:gcyl_meta_item', 574))
//         .duration(200)
//         .EUt(8192)
//         .buildAndRegister()

// ASSEMBLER.recipeBuilder()
//         .inputs(item('enderio:block_reservoir') * 4)
//         .inputs(item('gcyl:gcyl_meta_item', 574))
//         .outputs(item('gcyl:gcyl_meta_item', 575))
//         .duration(200)
//         .EUt(32768)
//         .buildAndRegister()


// ASSEMBLER.recipeBuilder()
//         .inputs(item('enderio:block_reservoir') * 4)
//         .inputs(item('gcyl:gcyl_meta_item', 575))
//         .outputs(item('gcyl:gcyl_meta_item', 576))
//         .duration(200)
//         .EUt(131072)
//         .buildAndRegister()

// ASSEMBLER.recipeBuilder()
//         .inputs(item('enderio:block_reservoir') * 4)
//         .inputs(item('gcyl:gcyl_meta_item', 576))
//         .outputs(item('gcyl:gcyl_meta_item', 577))
//         .duration(200)
//         .EUt(524288)
//         .buildAndRegister()


// Utils.removeRecipeByOutput(assembler, [item('gcyl:gcyl_meta_item', 250) * 24], [], true)

// ASSEMBLER.recipeBuilder()
//         .inputs(ore('plateGraphene'))
//         .inputs(ore('plateRuthenium'))
//         .inputs(ore('wireFineNaquadahAlloy') * 8)
//         .fluidInputs(fluid('soldering_alloy') * 144)
//         .outputs(item('gcyl:gcyl_meta_item', 250) * 24)
//         .duration(80)
//         .EUt(7904)
//         .buildAndRegister()