import gregtech.api.metatileentity.multiblock.CleanroomType

BIO_REACTOR = recipemap('bio_reactor')
ASSEMBLER = recipemap('assembler')
EBF = recipemap('electric_blast_furnace')
STELLAR_FORGE = recipemap('stellar_forge')
PLASMA_CONDENSER = recipemap('plasma_condenser')

// TODO: Change Tiny Pile Recipes & Isotopes
// Tiny Pile of Lutetium Dust * 1
mods.gregtech.large_centrifuge.removeByInput(7680, [metaitem('dustNaquadria')], [fluid('nitrogen_dioxide') * 500 * 500, fluid('sulfuric_acid') * 500 * 500])

// Actinium Nitrate Dust * 26
mods.gregtech.large_centrifuge.removeByInput(32700, null, [fluid('actinium_radium_nitrate_solution') * 13000 * 13000, fluid('theonyl_trifluoroacetate') * 500 * 500])

// Stem Cells * 2
mods.gregtech.bio_reactor.removeByInput(480, [metaitem('stem_cells')], [fluid('sterilized_growth_medium') * 1000 * 1000])

BIO_REACTOR.recipeBuilder()
        .inputs(metaitem('stem_cells'))
        .fluidInputs(fluid('sterilized_growth_medium') * 1000)
        .outputs(metaitem('stem_cells') * 2)
        .circuitMeta(1)
        .cleanroom(CleanroomType.STERILE_CLEANROOM)
        .duration(250)
        .EUt(480)
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(ore('wireGtDoubleChaosalloy') * 8)
        .inputs(metaitem('gcyl:highly_insulating_foil') * 16)
        .fluidInputs(fluid('cosmic_neutronium') * 144)
        .outputs(item('gcyl:wire_coil', 6))
        .duration(250)
        .EUt(536870900)
        .buildAndRegister()

EBF.recipeBuilder()
        .inputs(metaitem('tjceu:crystal.refined_chaos'))
        .inputs(ore('boltChaosalloy') * 8)
        .inputs(metaitem('gcyl:recursively.folded.negative.space'))
        .fluidInputs(fluid('light_quarks') * 750)
        .outputs(metaitem('tjceu:crystal.infinity'))
        .blastFurnaceTemp(19302)
        .duration(100)
        .EUt(536870900)
        .buildAndRegister()

EBF.recipeBuilder()
        .inputs(metaitem('gcyl:cosmic.fabric') * 4)
        .inputs(metaitem('gcyl:time.dilation.containment.unit'))
        .inputs(metaitem('gcyl:qcd.protective.plating'))
        .fluidInputs(fluid('taranium') * 4032)
        .outputs(metaitem('tjceu:dustEternityPreparation'))
        .blastFurnaceTemp(23000)
        .duration(50)
        .EUt(536870900)
        .buildAndRegister()

STELLAR_FORGE.recipeBuilder()
        .inputs(item('gcyl:gcyl_explosive', 3))
        .inputs(metaitem('tjceu:dustEternityPreparation') * 4)
        .inputs(metaitem('tjceu:crystal.infinity') * 2)
        .fluidInputs(fluid('gluons') * 8000)
        .fluidOutputs(fluid('plasma.eternity') * 1152)
        .duration(20)
        .EUt(536870900)
        .buildAndRegister()

PLASMA_CONDENSER.recipeBuilder()
        .fluidInputs(fluid('plasma.eternity') * 144)
        .fluidInputs(fluid('microcrystallizinghydrogen') * 5000)
        .notConsumable(metaitem('gcyl:ingot.field.shape'))
        .fluidOutputs(fluid('hydrogen') * 5000)
        .outputs(metaitem('tjceu:ingotEternity'))
        .duration(40)
        .EUt(536870900)
        .buildAndRegister()

ASSEMBLER.recipeBuilder()
        .inputs(metaitem('tjceu:blockEternity'))
        .inputs(ore('wireGtHexMaxSuperconductor') * 8)
        .inputs(metaitem('gcyl:highly_insulating_foil') * 32)
        .inputs(metaitem('field.generator.opv'))
        .fluidInputs(fluid('chaosalloy') * 288)
        .outputs(item('gcyl:wire_coil', 7))
        .duration(100)
        .EUt(536870900)
        .buildAndRegister()

EBF.recipeBuilder()
        .inputs(metaitem('gcyl:eigenfolded.kerr.manifold'))
        .inputs(metaitem('gcyl:cosmic.fabric') * 8)
        .inputs(metaitem('tjceu:crystal.infinity'))
        .fluidInputs(fluid('high_energy_qgp') * 288)
        .outputs(metaitem('tjceu:crystal.eternity'))
        .blastFurnaceTemp(51237)
        .duration(10000)
        .EUt(536870900)
        .buildAndRegister()