import static classes.utils.TJUtility.tjceu

ASSEMBLER = recipemap('assembler')
LASER_ENGRAVER = recipemap('laser_engraver')


//red
ASSEMBLER.recipeBuilder()
        .inputs([item('actuallyadditions:block_crystal'), item('minecraft:brick') * 2, item('minecraft:netherbrick') * 2, item('minecraft:redstone_block') * 2])
        .fluidInputs(fluid('plastic') * 288)
        .outputs([item('actuallyadditions:block_crystal_empowered')])
        .duration(160)
        .EUt(120)
        .buildAndRegister()
ASSEMBLER.recipeBuilder()
        .inputs([item('actuallyadditions:item_crystal'), item('minecraft:brick_block') * 2, item('minecraft:nether_brick') * 2, item('minecraft:redstone_block') * 2])
        .fluidInputs(fluid('plastic') * 288)
        .outputs([item('actuallyadditions:item_crystal_empowered')])
        .duration(160)
        .EUt(120)
        .buildAndRegister()
//blue
ASSEMBLER.recipeBuilder()
        .inputs([item('actuallyadditions:block_crystal:1'), item('minecraft:prismarine') * 2, item('minecraft:lapis_block') * 2])
        .fluidInputs(fluid('plastic') * 288)
        .outputs([item('actuallyadditions:block_crystal_empowered:1')])
        .duration(160)
        .EUt(120)
        .buildAndRegister()
ASSEMBLER.recipeBuilder()
        .inputs([item('actuallyadditions:item_crystal:1'), item('minecraft:prismarine') * 2, item('minecraft:lapis_block') * 2])
        .fluidInputs(fluid('plastic') * 288)
        .outputs([item('actuallyadditions:item_crystal_empowered:1')])
        .duration(160)
        .EUt(120)
        .buildAndRegister()
//white
ASSEMBLER.recipeBuilder()
        .inputs([item('actuallyadditions:block_crystal:5'), item('minecraft:snow') * 2, item('minecraft:stone') * 2])
        .fluidInputs(fluid('plastic') * 288)
        .outputs([item('actuallyadditions:block_crystal_empowered:5')])
        .duration(160)
        .EUt(120)
        .buildAndRegister()
ASSEMBLER.recipeBuilder()
        .inputs([item('actuallyadditions:item_crystal:5'), item('minecraft:snow') * 2, item('minecraft:stone') * 2])
        .fluidInputs(fluid('plastic') * 288)
        .outputs([item('actuallyadditions:item_crystal_empowered:5')])
        .duration(160)
        .EUt(120)
        .buildAndRegister()
//black
ASSEMBLER.recipeBuilder()
        .inputs([item('actuallyadditions:block_crystal:3'), ore('blockCharcoal') * 2, ore('blockCoalCoke') * 2])
        .fluidInputs(fluid('plastic') * 288)
        .outputs([item('actuallyadditions:block_crystal_empowered:3')])
        .duration(160)
        .EUt(120)
        .buildAndRegister()
ASSEMBLER.recipeBuilder()
        .inputs([item('actuallyadditions:item_crystal:3'), ore('blockCharcoal') * 2, ore('blockCoalCoke') * 2])
        .fluidInputs(fluid('plastic') * 288)
        .outputs([item('actuallyadditions:item_crystal_empowered:3')])
        .duration(160)
        .EUt(120)
        .buildAndRegister()
//light blue
ASSEMBLER.recipeBuilder()
        .inputs([item('actuallyadditions:block_crystal:2'), item('minecraft:clay') * 4])
        .fluidInputs(fluid('plastic') * 288)
        .outputs([item('actuallyadditions:block_crystal_empowered:2')])
        .duration(160)
        .EUt(120)
        .buildAndRegister()
ASSEMBLER.recipeBuilder()
        .inputs([item('actuallyadditions:item_crystal:2'), item('minecraft:clay') * 4])
        .fluidInputs(fluid('plastic') * 288)
        .outputs([item('actuallyadditions:item_crystal_empowered:2')])
        .duration(160)
        .EUt(120)
        .buildAndRegister()
//green
ASSEMBLER.recipeBuilder()
        .inputs([item('actuallyadditions:block_crystal:4'), ore('blockSlime') * 2, metaitem('plant_ball') * 2])
        .fluidInputs(fluid('plastic') * 288)
        .outputs([item('actuallyadditions:block_crystal_empowered:4')])
        .duration(160)
        .EUt(120)
        .buildAndRegister()
ASSEMBLER.recipeBuilder()
        .inputs([item('actuallyadditions:item_crystal:4'), ore('blockSlime') * 2, metaitem('plant_ball') * 2])
        .fluidInputs(fluid('plastic') * 288)
        .outputs([item('actuallyadditions:item_crystal_empowered:4')])
        .duration(160)
        .EUt(120)
        .buildAndRegister()

crafting.addShaped(tjceu('stainless_steel_casing'), item('actuallyadditions:block_misc:9'), [[null, ore('plateStainlessSteel'), null], [ore('plateStainlessSteel'), item('actuallyadditions:item_misc:5'), ore('plateStainlessSteel')], [null, ore('plateStainlessSteel'), null]])

// TODO: custom lense for AA recipes?

//attomic recipes
LASER_ENGRAVER.recipeBuilder()
        .inputs(item('minecraft:quartz_block', 1))
        .notConsumable(ore('craftingLensGreen'))
        .outputs(item('actuallyadditions:block_testifi_bucks_green_wall'))
        .EUt(8)
        .duration(20)
        .buildAndRegister()

LASER_ENGRAVER.recipeBuilder()
        .inputs(item('minecraft:quartz_block'))
        .notConsumable(ore('craftingLensLightGray'))
        .outputs(item('actuallyadditions:block_testifi_bucks_white_wall'))
        .EUt(8)
        .duration(20)
        .buildAndRegister()

LASER_ENGRAVER.recipeBuilder()
        .inputs(item('minecraft:quartz'))
        .notConsumable(ore('craftingLensCyan'))
        .outputs(item('minecraft:prismarine_shard'))
        .EUt(8)
        .duration(20)
        .buildAndRegister()

LASER_ENGRAVER.recipeBuilder()
        .inputs(item('minecraft:quartz'))
        .notConsumable(ore('craftingLensBlue'))
        .outputs(item('minecraft:prismarine_crystals'))
        .EUt(8)
        .duration(20)
        .buildAndRegister()

LASER_ENGRAVER.recipeBuilder()
        .inputs(item('minecraft:red_mushroom'))
        .notConsumable(ore('craftingLensWhite'))
        .outputs(item('minecraft:nether_wart'))
        .EUt(8)
        .duration(20)
        .buildAndRegister()

LASER_ENGRAVER.recipeBuilder()
        .inputs(item('minecraft:rotten_flesh'))
        .notConsumable(ore('craftingLensWhite'))
        .outputs(item('minecraft:leather'))
        .EUt(8)
        .duration(20)
        .buildAndRegister()

LASER_ENGRAVER.recipeBuilder()
        .inputs(item('minecraft:sand'))
        .notConsumable(ore('craftingLensWhite'))
        .outputs(item('minecraft:soul_sand'))
        .EUt(8)
        .duration(20)
        .buildAndRegister()

LASER_ENGRAVER.recipeBuilder()
        .inputs(item('minecraft:iron_block'))
        .notConsumable(ore('craftingLensWhite'))
        .outputs(item('actuallyadditions:block_crystal:5'))
        .EUt(8)
        .duration(20)
        .buildAndRegister()

LASER_ENGRAVER.recipeBuilder()
        .inputs(item('minecraft:coal_block'))
        .notConsumable(ore('craftingLensWhite'))
        .outputs(item('actuallyadditions:block_crystal:3'))
        .EUt(8)
        .duration(20)
        .buildAndRegister()

LASER_ENGRAVER.recipeBuilder()
        .inputs(item('minecraft:emerald_block'))
        .notConsumable(ore('craftingLensWhite'))
        .outputs(item('actuallyadditions:block_crystal:4'))
        .EUt(8)
        .duration(20)
        .buildAndRegister()

LASER_ENGRAVER.recipeBuilder()
        .inputs(item('minecraft:diamond_block'))
        .notConsumable(ore('craftingLensWhite'))
        .outputs(item('actuallyadditions:block_crystal:2'))
        .EUt(8)
        .duration(20)
        .buildAndRegister()

LASER_ENGRAVER.recipeBuilder()
        .inputs(item('minecraft:lapis_block'))
        .notConsumable(ore('craftingLensWhite'))
        .outputs(item('actuallyadditions:block_crystal:1'))
        .EUt(8)
        .duration(20)
        .buildAndRegister()

LASER_ENGRAVER.recipeBuilder()
        .inputs(item('minecraft:redstone_block'))
        .notConsumable(ore('craftingLensWhite'))
        .outputs(item('actuallyadditions:block_crystal'))
        .EUt(8)
        .duration(20)
        .buildAndRegister()

LASER_ENGRAVER.recipeBuilder()
        .inputs(item('actuallyadditions:item_canola_seed') * 30)
        .notConsumable(ore('craftingLensWhite'))
        .outputs(item('actuallyadditions:item_misc:23') * 30)
        .EUt(8)
        .duration(20)
        .buildAndRegister()

crafting.addShaped(tjceu('block_laser_relay_item'), item('actuallyadditions:block_laser_relay_item') * 4, [
        [item('minecraft:obsidian'), item('minecraft:emerald_block'), item('minecraft:obsidian')],
        [item('actuallyadditions:item_crystal:4'), item('actuallyadditions:item_misc:8'), item('actuallyadditions:item_crystal:4')],
        [item('minecraft:obsidian'), item('minecraft:emerald_block'), item('minecraft:obsidian')]
])
crafting.addShaped(tjceu('block_laser_relay_fluids'), item('actuallyadditions:block_laser_relay_fluids') * 4, [
        [item('minecraft:obsidian'), item('minecraft:lapis_block'), item('minecraft:obsidian')],
        [item('actuallyadditions:item_crystal:1'), item('actuallyadditions:item_misc:8'), item('actuallyadditions:item_crystal:1')],
        [item('minecraft:obsidian'), item('minecraft:lapis_block'), item('minecraft:obsidian')]
])
