import static classes.utils.TJUtility.*

ASSEMBLER = recipemap('assembler')
ASSLINE = recipemap('assembly_line')
CHEMICAL_BATH = recipemap('chemical_bath')
STELLAR_FORGE = recipemap('stellar_forge')
ADV_FUSION = recipemap('adv_fusion')
BIO_REACTOR = recipemap('bio_reactor')
EBF = recipemap('electric_blast_furnace')
PLASMA_CONDENSER = recipemap('plasma_condenser')

// Recipe removals
furnace.removeByOutput(item('draconicevolution:draconium_ingot'))
crafting.removeByOutput(item('draconicevolution:nugget'))
crafting.removeByOutput(item('draconicevolution:draconium_block'))
crafting.removeByOutput(item('draconicevolution:draconium_ingot'))
crafting.removeByOutput(item('draconicevolution:nugget', 1))
crafting.removeByOutput(item('draconicevolution:draconic_ingot'))
crafting.removeByOutput(item('draconicevolution:draconic_block'))
crafting.removeByOutput(item('draconicevolution:wyvern_energy_core'))
crafting.removeByOutput(item('draconicevolution:celestial_manipulator'))

ASSLINE.recipeBuilder()
        .inputs(ore('frameNeutronium'))
        .inputs(ore('plateDraconium') * 10)
        .inputs(ore('plateStarmetalAlloy') * 10)
        .inputs(ore('plateMendelevium') * 10)
        .inputs(metaitem('neutron_reflector') * 2)
        .inputs(metaitem('field.generator.zpm'))
        .inputs(metaitem('emitter.zpm'))
        .inputs(metaitem('sensor.zpm'))
        .inputs(ore('circuitUhv'))
        .fluidInputs(fluid('soldering_alloy') * 50)
        .outputs(item('draconicevolution:draconic_core') * 2)
        .duration(1200)
        .EUt(524288)
        .buildAndRegister()

ASSLINE.recipeBuilder()
        .inputs(ore('frameGtHdcs') * 10)
        .inputs(ore('plateTantalumHafniumSeaborgiumCarbide') * 10)
        .inputs(ore('plateDraconium') * 10)
        .inputs(ore('plateProtoAdamantium') * 10)
        .inputs(ore('plateTitanSteel') * 10)
        .inputs(metaitem('field.generator.uv'))
        .inputs(metaitem('emitter.uv'))
        .inputs(metaitem('sensor.uv'))
        .inputs(ore('circuitUev'))
        .inputs(item('draconicevolution:draconic_core'))
        .fluidInputs(fluid('soldering_alloy') * 50)
        .outputs(item('draconicevolution:wyvern_core') * 2)
        .duration(1200)
        .EUt(2097152)
        .buildAndRegister()

ASSLINE.recipeBuilder()
        .inputs(ore('frameGtTriniumTitanium') * 10)
        .inputs(ore('dustLegendarium') * 10)
        .inputs(ore('plateAwakenDraconium') * 10)
        .inputs(ore('plateSuperheavyLAlloy') * 10)
        .inputs(ore('plateSuperheavyHAlloy') * 10)
        .inputs(metaitem('field.generator.uiv'))
        .inputs(metaitem('emitter.uiv'))
        .inputs(metaitem('sensor.uiv'))
        .inputs(ore('circuitUiv'))
        .inputs(item('draconicevolution:wyvern_core'))
        .fluidInputs(fluid('soldering_alloy') * 50)
        .outputs(item('draconicevolution:awakened_core') * 2)
        .duration(600)
        .EUt(8388608)
        .buildAndRegister()

ASSLINE.recipeBuilder()
        .inputs(ore('frameGtQuantum') * 10)
        .inputs(ore('plateCinobite') * 10)
        .inputs(ore('plateAwakenDraconium') * 10)
        .inputs(ore('plateChaos') * 10)
        .inputs(metaitem('field.generator.uxv'))
        .inputs(metaitem('emitter.uxv'))
        .inputs(metaitem('sensor.uxv'))
        .inputs(ore('circuitUxv'))
        .inputs(metaitem('tjceu:crystal.refined_chaos'))
        .inputs(item('draconicevolution:awakened_core'))
        .fluidInputs(fluid('soldering_alloy') * 50)
        .outputs(item('draconicevolution:chaotic_core') * 2)
        .duration(600)
        .EUt(33554432)
        .buildAndRegister()


CHEMICAL_BATH.recipeBuilder()
        .inputs(item('draconicevolution:chaos_shard'))
        .fluidInputs(fluid('rutherfordium') * 1000)
        .outputs(metaitem('tjceu:crystal.refined_chaos') * 2)
        .duration(600)
        .EUt(8388608)
        .buildAndRegister()

CHEMICAL_BATH.recipeBuilder()
        .inputs(metaitem('tjceu:shard.refined_chaos') * 9)
        .fluidInputs(fluid('rutherfordium') * 500)
        .outputs(metaitem('tjceu:crystal.refined_chaos'))
        .duration(600)
        .EUt(131072)
        .buildAndRegister()

STELLAR_FORGE.recipeBuilder()
        .inputs(item('draconicevolution:awakened_core') * 3)
        .inputs(metaitem('tjceu:crystal.refined_chaos'))
        .inputs(ore('blockAwakenDraconium') * 2)
        .fluidOutputs(fluid('raw_chaos') * 2592)
        .duration(600)
        .EUt(8388608)
        .buildAndRegister()

STELLAR_FORGE.recipeBuilder()
        .inputs(item('draconicevolution:awakened_core'))
        .inputs(item('draconicadditions:chaos_heart'))
        .inputs(ore('blockAwakenDraconium') * 4)
        .fluidOutputs(fluid('raw_chaos') * 5184)
        .outputs(item('draconicevolution:dragon_heart'))
        .duration(600)
        .EUt(8388608)
        .buildAndRegister()


//ADV_FUSION.recipeBuilder()
//     .fluidInputs(fluid('raw_chaos') * 288, fluid('bohrium') * 288)//,fluid('lead_bismuth_eutatic') * 7440)
//     .fluidOutputs(fluid('plasma.chaos') * 576)//, fluid('supercritical_lead_bismuth_eutectic') * 7440)
//     .property("eu_to_start", 2000000000)
//     .property("coilTier", 5)
//     .property("euReturn", 75)
//     .duration(50)
//     .EUt(16000000)
//     .buildAndRegister()

crafting.addShapeless(tjceu('shard.refined_chaos'), metaitem('tjceu:shard.refined_chaos') * 9, [metaitem('tjceu:crystal.refined_chaos')])

//BIO_REACTOR.recipeBuilder()
//     .inputs(item('gregtech:meta_item_1', 709) * 10)
//    .inputs(item('draconicevolution:dragon_heart') * 2)
//     .fluidInputs(fluid('sterilized_growth_medium') * 2000)
//     .fluidOutputs(fluid('draconic_stem_cell_fluid') * 2000)
//     .duration(600)
//     .EUt(2097152)
//     .buildAndRegister()

//STELLAR_FORGE.recipeBuilder()
//     .inputs(item('draconicevolution:wyvern_core') * 2)
//    .inputs(ore('blockDraconium') * 3)
//     .fluidInputs(fluid('draconic_stem_cell_fluid') * 2000)
//     .fluidOutputs(fluid('depleted_growth_medium') * 2000, fluid('plasma.awakened_draconium') * 3888)
//     .duration(100)
//     .EUt(8388608)
//     .buildAndRegister()

// Armor
//ASSLINE.recipeBuilder()
//        .inputs(item('gregtech:machine:2505'))
//        .inputs(item('gregtech:meta_item_1:32655') * 2)
//        .inputs(ore('plateRutherfordium') * 10)
//        .inputs(ore('cableGtSingleNaquadahAlloy') * 10)
//        .inputs(ore('screwStaballoy') * 18)
//        .inputs(ore('plateDraconium') * 5)
//        .fluidInputs(fluid('dubnium') * 1296, fluid('californium') * 2592)
//        .outputs(item('gregtech:machine:1004'))
//        .duration(600)
//        .EUt(7864320)
//        .buildAndRegister()

// EggBoi
//ASSLINE.recipeBuilder()
//        .inputs(item('gregtech:mte', 994))
//        .inputs(ore('plateTantalumHafniumSeaborgiumCarbide') * 10)
//        .inputs(ore('plateDraconium') * 10)
//        .inputs(ore('plateAwakenDraconium') * 10)
//        .inputs(item('gregtech:ga_cable:5855') * 10)
//        .inputs(ore('circuitInfinite'))
//        .inputs(item('gcyl:gcyl_meta_item', 465))
//        .inputs(item('gregtech:meta_item_1', 240))
//        .fluidInputs(fluid('incoloy813') * 1296)
//        .fluidInputs(fluid('einsteinium') * 2592)
//        .outputs(item('gregtech:machine:1006'))
//        .duration(600)
//        .EUt(7864320)
//        .buildAndRegister()

// Chaos
//ASSLINE.recipeBuilder()
//        .inputs(item('gregtech:mte', 995))
//        .inputs(ore('plateLafium') * 10)
//        .inputs(ore('plateHastelloyk243') * 10)
//        .inputs(ore('plateHastelloyx78') * 10)
//        .inputs(ore('plateHdcs') * 5)
//        .inputs(ore('plateAwakenDraconium') * 10)
//        .inputs(item('gregtech:meta_item_1', 196))
//        .inputs(ore('cableGtSinglePikyonium') * 10)
//        .inputs(ore('circuitUev'))
//        .inputs(item('draconicevolution:awakened_core') * 2)
//        .fluidInputs(fluid('titan_steel') * 1296)
//        .fluidInputs(fluid('mendelevium') * 2592)
//        .fluidInputs(fluid('cinobite') * 1296)
//        .outputs(item('gregtech:machine:1005'))
//        .duration(600)
//        .EUt(2097152)
//        .buildAndRegister()

//ASSLINE.recipeBuilder()
//        .inputs(item('draconicevolution:wyvern_energy_core') * 4)
//        .inputs(item('draconicevolution:wyvern_core'))
//        .inputs(ore('gemDiamond'))
//        .inputs(item('draconicevolution:energy_crystal', 1) * 4)
//        .fluidInputs(fluid('mendelevium') * 144)
//        .outputs(item('draconicevolution:energy_crystal', 2) * 4)
//        .duration(300)
//        .EUt(2097152)
//        .buildAndRegister()

//ASSLINE.recipeBuilder()
//        .inputs(ore('enderpearl') * 3)
//        .inputs(ore('pearlEnderEye') * 7)
//        .inputs(item('draconicevolution:dislocator'))
//        .inputs(item('gregtech:meta_item_1:32724'))
//        .fluidInputs(fluid('draconium') * 576)
//        .outputs(item('draconicevolution:dislocator_advanced'))
//        .duration(200)
//        .EUt(32768)
//        .buildAndRegister()

//ASSLINE.recipeBuilder()
//        .inputs(ore('pearlEnderEye') * 7)
//        .inputs(item('draconicevolution:wyvern_core'))
//        .inputs(item('draconicevolution:draconic_core') * 2)
//        .inputs(item('draconicevolution:dislocator'))
//        .inputs(item('draconicadditions:chaotic_energy_core'))
//        .inputs(ore('itemSkull')) // TODO: Check this
//        .fluidInputs(fluid('blaze') * 2304)
//        .outputs(item('draconicevolution:ender_energy_manipulator'))
//        .duration(200)
//        .EUt(2097152)
//        .buildAndRegister()

//ASSLINE.recipeBuilder()
//        .inputs(item('draconicevolution:magnet'))
//        .inputs(item('draconicevolution:dislocator_advanced'))
//        .inputs(ore('plateAwakenDraconium') * 4)
//        .inputs(ore('dustNeodymiumMagnetic') * 2)
//        .outputs(item('draconicevolution:magnet', 1))
//        .duration(200)
//        .EUt(2097152)
//        .buildAndRegister()

//crafting.shapedBuilder()
//        .name(tjceu('celestial_manipulator'))
//        .row('RCR')
//        .row('RCR')
//crafting.addShaped(item('draconicevolution:celestial_manipulator'), [
//        [item('minecraft:redstone_block'), item('minecraft:clock'), item('minecraft:redstone_block')],
//        [item('gregtech:meta_item_1:12524'), item('gregtech:meta_item_1:32675'), item('gregtech:meta_item_1:12524')],
//        [item('gregtech:meta_item_1:12524'), item('gregtech:meta_item_2:26299'), item('gregtech:meta_item_1:12524')]
//])
// TODO: tooltip
//item('draconicevolution:celestial_manipulator').addTooltip(format.darkRed("Will not work on AR planets"))

//crafting.shapedBuilder()
//        .name(tjceu('chaotic_casing'))
//        .row('PHP')
//        .row('PFP')
//        .row('PWP')
//        .key('P', ore('plateEnrichedNaquadahAlloy'))
//        .key('H')
//        .key('W')
//        .key('F')
//        .output()
//        .register()

//crafting.addShaped(item('contenttweaker:chaoticcasing') * 3, [
// [ore('plate'), item('gregtech:meta_tool', 6), ore('plateEnrichedNaquadahAlloy')],
// [ore('plateEnrichedNaquadahAlloy'), ore('frameGtChaos'), ore('plateEnrichedNaquadahAlloy')],
// [ore('plateEnrichedNaquadahAlloy'), ore('GTWrench'), ore('plateEnrichedNaquadahAlloy')]])
//crafting.addShaped(item('contenttweaker:awakenedcasing') * 3, [[item('gregtech:meta_item_1:12855'), item('gregtech:meta_tool', 6), item('gregtech:meta_item_1:12855')], [item('gregtech:meta_item_1:12855'), ore('frameGtAwakenDraconium'), item('gregtech:meta_item_1:12855')], [item('gregtech:meta_item_1:12855'), ore('GTWrench'), item('gregtech:meta_item_1:12855')]])
//crafting.addShaped(item('contenttweaker:draconiccasing') * 3, [[ore('plateDraconium'), item('gregtech:meta_tool', 6), ore('plateDraconium')], [ore('plateDraconium'), ore('frameGtDraconium'), ore('plateDraconium')], [ore('plateDraconium'), ore('GTWrench'), ore('plateDraconium')]])

//ASSEMBLER.recipeBuilder()
//        .inputs(ore('frameGtDraconium'))
//        .inputs(ore('plateDraconium') * 6)
//        .circuitMeta()
//        .outputs(item('contenttweaker:draconiccasing') * 3)
//        .EUt(16)
//        .duration(50)
//        .buildAndRegister()

//ASSEMBLER.recipeBuilder()
//        .inputs(ore('blockAwakenDraconium'))
//        .circuitMeta()
//        .outputs(ore('blockDraconiumAwakened'))
//        .EUt(1)
//        .duration(1)
//        .buildAndRegister()

//ASSEMBLER.recipeBuilder()
//        .inputs(item('gregtech:frame_awaken_draconium'))
//        .inputs(item('gregtech:meta_item_1:12855') * 6)
//        .circuitMeta()
//        .outputs(item('contenttweaker:awakenedcasing') * 3)
//        .EUt(16)
//        .duration(50)
//        .buildAndRegister()

//ASSEMBLER.recipeBuilder()
//        .inputs(item('gregtech:frame_chaos'))
//        .inputs(ore('plateEnrichedNaquadahAlloy') * 6)
//        .circuitMeta()
//        .outputs(item('contenttweaker:chaoticcasing') * 3)
//        .EUt(16)
//        .duration(50)
//        .buildAndRegister()

//ASSLINE.recipeBuilder()
//        .inputs(item('gtadditions:ga_meta_item:1518') * 10)
//        .inputs(item('gregtech:meta_item_1:12524') * 10)
//        .inputs(item('gregtech:meta_item_2:32436'))
//        .inputs(item('gregtech:meta_item_1:32687'))
//        .outputs(item('draconicevolution:crafting_injector', 3))
//        .duration(200)
//        .EUt(524288)
//        .buildAndRegister()


// Energy cores
//ASSLINE.recipeBuilder()
//        .inputs(item('draconicevolution:wyvern_core') * 4)
//        .inputs(ore('plateDraconium') * 10)
//        .inputs(item('gregtech:cable:5518') * 10)
//        .inputs(item('gregtech:meta_item_1:32725'))
//        .fluidInputs(fluid('redstone') * 1440)
//        .outputs(item('draconicevolution:wyvern_energy_core'))
//        .duration(400)
//        .EUt(31457280)
//        .buildAndRegister()

//ASSLINE.recipeBuilder()
//        .inputs(item('draconicevolution:awakened_core') * 4)
//        .inputs(ore('plateAwakenDraconium') * 10)
//        .inputs(item('gregtech:cable:5519') * 10)
//        .inputs(item('gregtech:meta_item_1', 283))
//        .fluidInputs(fluid('redstone') * 1440)
//        .outputs(item('draconicevolution:draconic_energy_core'))
//        .duration(400)
//        .EUt(31457280)
//        .buildAndRegister()

//ASSLINE.recipeBuilder()
//        .inputs(item('draconicevolution:chaotic_core') * 4)
//        .inputs(item('gregtech:meta_item_1:12520') * 10)
//        .inputs(item('gregtech:cable:5520') * 10)
//        .inputs(item('gcyl:gcyl_meta_item', 343))
//        .fluidInputs(fluid('redstone') * 1440)
//        .outputs(item('draconicadditions:chaotic_energy_core'))
//        .duration(100)
//        .EUt(2013265920)
//        .buildAndRegister()


//STELLAR_FORGE.recipeBuilder()
//        .inputs(ore('ingotCosmicNeutronium'))
//        .inputs(item('gcyl:gcyl_meta_item', 568))
//        .inputs(item('gcyl:gcyl_explosive', 3))
//        .fluidInputs(fluid('chaos') * 1008)
//        .fluidOutputs(fluid('plasma.chaosalloy') * 2592)
//        .duration(20)
//        .EUt(31457280)
//        .buildAndRegister()

//ASSLINE.recipeBuilder()
//        .inputs(ore('plateDenseDraconium') * 8)
//        .inputs(ore('plateEnrichedNaquadahAlloy') * 8)
//        .inputs(item('appliedenergistics2:dense_energy_cell') * 64)
//        .inputs(ore('wireGtSingleUvSuperconductor') * 32)
//        .inputs(ore('circuitSuperconductor') * 2)
//        .fluidInputs(fluid('tritanium') * 720)
//        .fluidInputs(fluid('soldering_alloy') * 1296)
//        .outputs(item('appliedenergistics2:creative_energy_cell'))
//        .duration(1000)
//        .EUt(524288)
//        .buildAndRegister()

//ASSLINE.recipeBuilder()
//        .inputs(item('draconicevolution:chaotic_core') * 4, item('draconicadditions:chaotic_energy_core') * 4, ore('plateQuantum') * 64, ore('plateZylon') * 64, item('thermalfoundation:upgrade'), item('thermalfoundation:upgrade', 1), item('draconicevolution:draconium_capacitor', 1), item('gtadditions:ga_cell_casing', 11), item('gcyl:gcyl_meta_item', 377) * 2)
//        .fluidInputs(fluid('soldering_alloy') * 1440)
//        .fluidInputs(fluid('chaosalloy') * 1440)
//        .outputs(item('draconicevolution:draconium_capacitor', 2))
//        .duration(100)
//        .EUt(2013265920)
//        .buildAndRegister()

//ASSLINE.recipeBuilder()
//        .inputs(item('nae2:material', 4) * 2, ore('plateSuperheavyLAlloy') * 64, ore('plateSuperheavyHAlloy') * 64, item('thermalfoundation:upgrade', 2), item('thermalfoundation:upgrade', 3), item('draconicevolution:chaotic_core') * 2, item('gcyl:gcyl_meta_item', 395) * 2)
//        .fluidInputs(fluid('soldering_alloy') * 1440, fluid('chaosalloy') * 1440, fluid('heavy_quark_degenerate_matter') * 1440)
//        .outputs(item('storagedrawers:upgrade_creative'))
//        .duration(100)
//        .EUt(2013265920)
//        .buildAndRegister()

// Hardened upgrade
//ASSLINE.recipeBuilder()
//        .inputs(item('draconicevolution:draconic_core') * 10, item('gregtech:meta_item_1:12524') * 64, ore('wireGtSingleUvSuperconductor') * 64, ore('plateTitanSteel') * 64)
//        .fluidInputs(fluid('soldering_alloy') * 1440, fluid('draconium') * 1440)
//        .outputs(item('thermalfoundation:upgrade'))
//        .duration(100)
//        .EUt(2013265920)
//        .buildAndRegister()

//ASSLINE.recipeBuilder()
//        .inputs(item('draconicevolution:wyvern_core') * 10, ore('plateProtoAdamantium') * 64, ore('wireGtSingleUhvSuperconductor') * 64, ore('platePikyonium') * 64)
//        .fluidInputs(fluid('soldering_alloy') * 1440, fluid('draconium') * 1440, fluid('naquadah_alloy') * 1440)
//        .outputs(item('thermalfoundation:upgrade', 1))
//        .duration(100)
//        .EUt(2013265920)
//        .buildAndRegister()

//ASSLINE.recipeBuilder()
//        .inputs(item('draconicevolution:awakened_core') * 10, ore('plateSeaborgium') * 64, ore('wireGtSingleUevSuperconductor') * 64, ore('plateBlackTitanium') * 64)
//        .fluidInputs(fluid('soldering_alloy') * 1440, fluid('awaken_draconium') * 1440, fluid('enriched_naquadah_alloy') * 1440)
//        .outputs(item('thermalfoundation:upgrade', 2))
//        .duration(100)
//        .EUt(2013265920)
//        .buildAndRegister()

//ASSLINE.recipeBuilder()
//        .inputs(item('draconicevolution:chaotic_core') * 10, ore('plateBohrium') * 64, ore('wireGtSingleUivSuperconductor') * 64, ore('plateHdcs') * 64)
//        .fluidInputs(fluid('soldering_alloy') * 1440, fluid('chaos') * 1440, fluid('naquadriatic_taranium') * 1440)
//        .outputs(item('thermalfoundation:upgrade', 3))
//        .duration(100)
//        .EUt(2013265920)
//        .buildAndRegister()
////creative conversion kit

//ASSLINE.recipeBuilder()
//        .inputs(item('thermalfoundation:upgrade') * 1, item('thermalfoundation:upgrade', 1) * 1, item('thermalfoundation:upgrade', 2) * 1, item('thermalfoundation:upgrade', 3) * 1)
//        .fluidInputs(fluid('naquadriatic_taranium') * 1440, fluid('cosmic_neutronium') * 1440, fluid('enriched_naquadah_alloy') * 1440, fluid('naquadah_alloy') * 1440)
//        .outputs(item('thermalfoundation:upgrade', 256))
//        .duration(100)
//        .EUt(2013265920)
//        .buildAndRegister()

//ASSLINE.recipeBuilder()
//        .inputs(item('thermalfoundation:upgrade', 256) * 1, item('storagedrawers:upgrade_creative') * 1, item('draconicevolution:draconium_capacitor', 2), metaitem('tjceu:crystal.refined_chaos') * 64, metaitem('tjceu:crystal.refined_chaos') * 64, item('contenttweaker:certificate_of_being_a_noob'), ore('circuitMax'), item('gcyl:gcyl_meta_item', 383) * 4, metaitem('tjceu:crystal.eternity') * 4)
//        .inputs(item('draconicadditions:chaos_stabilizer_core'), item('gregtech:meta_item_2:32715'), item('gtadditions:ga_cell_casing', 11) * 64, item('gtadditions:ga_cell_casing', 11) * 64, item('gtadditions:ga_cell_casing', 11) * 14, item('gtadditions:ga_multiblock_casing', 12), item('nae2:material', 4) * 64)
//        .fluidInputs(fluid('chaosalloy') * 11520)
//        .outputs(item('appliedenergistics2:creative_storage_cell'))
//        .duration(2147483647)
//        .EUt(1)
//        .buildAndRegister()

//crafting.addShaped(item('draconicadditions:chaos_stabilizer_core'), [[item('draconicadditions:chaotic_helm'), item('draconicadditions:chaotic_staff_of_power'), item('draconicadditions:chaotic_chest')], [item('draconicevolution:draconic_energy_core'), item('draconicadditions:chaotic_energy_core'), item('draconicevolution:draconic_energy_core')], [item('draconicadditions:chaotic_legs'), item('draconicadditions:chaotic_bow'), item('draconicadditions:chaotic_boots')]])

//Utils.removeRecipeByOutput(bioreactor, [item('gregtech:meta_item_1', 709) * 2], [], true)

//BIO_REACTOR.recipeBuilder()
//        .inputs(item('gregtech:meta_item_1', 709))
//        .fluidInputs(fluid('sterilized_growth_medium') * 1000)
//        .outputs(item('gregtech:meta_item_1', 709) * 2)
//        .notConsumable(item('gregtech:meta_item_1:32766').withTag({ Configuration: 1 }))
//        .duration(250)
//        .EUt(480)
//        .buildAndRegister()

//ASSEMBLER.recipeBuilder()
//        .inputs(ore('wireGtDoubleChaosalloy') * 8, item('gcyl:gcyl_meta_item', 506) * 16)
//        .fluidInputs(fluid('cosmic_neutronium') * 144)
//        .outputs(item('gcyl:wire_coil', 5))
//        .duration(250)
//        .EUt(536870900)
//        .buildAndRegister()

//EBF.recipeBuilder()
//        .inputs(metaitem('tjceu:crystal.refined_chaos') * 1, ore('boltChaosalloy') * 8, item('gcyl:gcyl_meta_item', 561) * 1)
//        .fluidInputs(fluid('light_quarks') * 750)
//        .outputs(item('contenttweaker:infintycrystal'))
//        .property("temperature", 19302)
//        .duration(100)
//        .EUt(536870900)
//        .buildAndRegister()

//EBF.recipeBuilder()
//        .inputs(item('gcyl:gcyl_meta_item', 569) * 4, item('gcyl:gcyl_meta_item', 515), item('gcyl:gcyl_meta_item', 556))
//        .fluidInputs(fluid('taranium') * 4032)
//        .outputs(item('gtadditions:ga_dust', 529))
//        .property("temperature", 23000)
//        .duration(50)
//        .EUt(536870900)
//        .buildAndRegister()

//Stellar.recipeBuilder()
//        .inputs(item('gcyl:gcyl_explosive', 3), item('gtadditions:ga_dust', 529) * 4, item('contenttweaker:infintycrystal') * 2)
//        .fluidInputs(fluid('gluons') * 8000)
//        .fluidOutputs(fluid('eternity') * 1152)
//        .duration(20)
//        .EUt(536870900)
//        .buildAndRegister()

//PLASMA_CONDENSER.recipeBuilder()
//        .fluidInputs(fluid('eternity') * 144, fluid('microcrystallizinghydrogen') * 5000)
//        .notConsumable(item('gcyl:gcyl_meta_item', 450))
//        .fluidOutputs(fluid('hydrogen') * 5000)
//        .outputs(item('contenttweaker:eternityingot'))
//        .duration(40)
//        .EUt(536870900)
//        .buildAndRegister()

//ASSEMBLER.recipeBuilder()
//        .fluidInputs(fluid('chaosalloy') * 288)
//        .inputs(item('contenttweaker:eternityblock'), item('gregtech:cable:4354') * 8, item('gcyl:gcyl_meta_item', 506) * 32, item('gregtech:meta_item_1', 213))
//        .outputs(item('gcyl:wire_coil', 6))
//        .duration(100)
//        .EUt(536870900)
//        .buildAndRegister()

//EBF.recipeBuilder()
//        .inputs(item('gcyl:gcyl_meta_item', 559), item('gcyl:gcyl_meta_item', 569) * 8, item('contenttweaker:infintycrystal'))
//        .fluidInputs(fluid('high_energy_qgp') * 288)
//        .outputs(metaitem('tjceu:crystal.eternity'))
//        .property("temperature", 51237)
//        .duration(10000)
//        .EUt(536870900)
//        .buildAndRegister()