//TODO: from OtherRecipes

// //MOB stuff
// crafting.removeByOutput(item('mob_grinding_utils:fan'))
// crafting.addShaped(item('mob_grinding_utils:fan'), [[ore('plateAluminium'), ore('dustRedstone'), ore('cableGtSingleTin')], [ore('dustRedstone'), item('gregtech:mte', 986), ore('rotorSteel')], [ore('plateAluminium'), ore('dustRedstone'), ore('cableGtSingleTin')]])
// crafting.removeByOutput(item('mob_grinding_utils:spikes'))
// crafting.addShaped(item('mob_grinding_utils:spikes'), [[null, item('gregtech:meta_item_2', 33), null], [item('gregtech:meta_item_2', 33), item('gregtech:mte', 986), item('gregtech:meta_item_2', 33)], [item('gtadditions:ga_meta_item:1033'), item('gtadditions:ga_meta_item:1033'), item('gtadditions:ga_meta_item:1033')]])
// crafting.removeByOutput(item('mob_grinding_utils:saw'))
// crafting.addShaped(item('mob_grinding_utils:saw'), [[ore('plateStainlessSteel'), item('gregtech:meta_item_2', 183), ore('plateStainlessSteel')], [ore('gemExquisiteDiamond'), item('mob_grinding_utils:spikes'), ore('gemExquisiteDiamond')], [ore('plateStainlessSteel'), ore('plateStainlessSteel'), ore('plateStainlessSteel')]])
// crafting.removeByOutput(item('mob_grinding_utils:fan_upgrade', 1))
// crafting.removeByOutput(item('mob_grinding_utils:fan_upgrade'))
// crafting.addShaped(item('mob_grinding_utils:fan_upgrade', 1), [[ore('plateIron'), ore('craftingFeather,feather'), ore('plateIron')], [null, ore('rotorSteel'), null], [ore('plateIron'), ore('craftingFeather,feather'), ore('plateIron')]])
// crafting.addShaped(item('mob_grinding_utils:fan_upgrade'), [[ore('plateIron'), null, ore('plateIron')], [ore('craftingFeather,feather'), ore('rotorSteel'), ore('craftingFeather,feather')], [ore('plateIron'), null, ore('plateIron')]])
// crafting.addShaped(item('mob_grinding_utils:fan_upgrade', 2), [[ore('plateIron'), ore('craftingFeather,feather'), ore('plateIron')], [ore('craftingFeather,feather'), ore('rotorSteel'), ore('craftingFeather,feather')], [ore('plateIron'), ore('craftingFeather,feather'), ore('plateIron')]])
// crafting.removeByOutput(item('mob_grinding_utils:saw_upgrade', 4))
// crafting.removeByOutput(item('mob_grinding_utils:saw_upgrade', 3))
// crafting.removeByOutput(item('mob_grinding_utils:saw_upgrade'))
// crafting.removeByOutput(item('mob_grinding_utils:fan_upgrade', 2))
// crafting.removeByOutput(item('mob_grinding_utils:saw_upgrade', 2))
// crafting.addShaped(item('mob_grinding_utils:saw_upgrade', 4), [[ore('plateGold'), item('minecraft:spider_eye'), ore('plateGold')], [item('minecraft:spider_eye'), ore('plateRedstone'), item('minecraft:spider_eye')], [ore('plateGold'), item('minecraft:spider_eye'), ore('plateGold')]])
// crafting.addShaped(item('mob_grinding_utils:saw_upgrade', 3), [[ore('plateGold'), item('minecraft:rotten_flesh'), ore('plateGold')], [item('minecraft:rotten_flesh'), ore('plateRedstone'), item('minecraft:rotten_flesh')], [ore('plateGold'), item('minecraft:rotten_flesh'), ore('plateGold')]])
// crafting.addShaped(item('mob_grinding_utils:saw_upgrade', 2), [[ore('plateGold'), ore('dustBlaze,itemBlazePowder'), ore('plateGold')], [ore('dustBlaze,itemBlazePowder'), ore('plateRedstone'), ore('dustBlaze,itemBlazePowder')], [ore('plateGold'), ore('dustBlaze,itemBlazePowder'), ore('plateGold')]])
// crafting.addShaped(item('mob_grinding_utils:saw_upgrade'), [[ore('plateGold'), item('gregtech:meta_item_2', 33), ore('plateGold')], [item('gregtech:meta_item_2', 33), ore('plateRedstone'), item('gregtech:meta_item_2', 33)], [ore('plateGold'), item('gregtech:meta_item_2', 33), ore('plateGold')]])
