//TODO: from OtherRecipes
// crafting.addShaped(item('snad:snad', 1), [[ore('sand'), ore('sand'), ore('sand')], [ore('sand'), ore('sand'), ore('sand')], [ore('sand'), ore('sand'), ore('sand')]])
// crafting.addShaped(item('snad:snad'), [[ore('sand'), ore('sand'), ore('sand')], [ore('sand'), ore('sand'), ore('sand')], [ore('sand'), ore('sand'), ore('sand')]])

// CHEMICAL_REACTOR.recipeBuilder()
//         .inputs(item('snad:snad') * 8)
//         .inputs(item('minecraft:obsidian') * 2)
//         .fluidInputs(fluid('lava') * 10000)
//         .outputs(ore('endstone,oc:stoneEndstone,stoneEndstone'))
//         .duration(600)
//         .EUt(2040)
//         .buildAndRegister()

// CHEMICAL_REACTOR.recipeBuilder()
//         .inputs(ore('sand') * 64)
//         .inputs(item('minecraft:obsidian') * 2)
//         .fluidInputs(fluid('lava') * 1000)
//         .outputs(ore('endstone,oc:stoneEndstone,stoneEndstone') * 2)
//         .duration(300)
//         .EUt(30252)
//         .buildAndRegister()

// LCR.recipeBuilder()
//         .inputs(ore('sand') * 64)
//         .inputs(item('minecraft:obsidian') * 2)
//         .fluidInputs(fluid('lava') * 1000)
//         .outputs(ore('endstone,oc:stoneEndstone,stoneEndstone') * 2)
//         .duration(300)
//         .EUt(30252)
//         .buildAndRegister()

// LCR.recipeBuilder()
//         .inputs(item('snad:snad') * 8)
//         .inputs(item('minecraft:obsidian') * 2)
//         .fluidInputs(fluid('lava') * 10000)
//         .outputs(ore('endstone,oc:stoneEndstone,stoneEndstone'))
//         .duration(600)
//         .EUt(2040)
//         .buildAndRegister()

// MIXER.recipeBuilder()
//         .inputs(ore('sand') * 4)
//         .fluidInputs([fluid('biomass') * 250])
//         .outputs(item('minecraft:dirt') * 4)
//         .duration(20)
//         .EUt(30)
//         .buildAndRegister()