import static classes.utils.TJUtility.*

// Recipe removals
crafting.removeByOutput(item('thermalfoundation:upgrade'))
crafting.removeByOutput(item('thermalfoundation:upgrade', 1))
crafting.removeByOutput(item('thermalfoundation:upgrade', 2))
crafting.removeByOutput(item('thermalfoundation:upgrade', 3))
crafting.removeByOutput(item('thermalfoundation:upgrade', 33))
crafting.removeByOutput(item('thermalfoundation:upgrade', 34))
crafting.removeByOutput(item('thermalfoundation:upgrade', 35))

// Hardened upgrade
ASSLINE.recipeBuilder()
       .inputs(item('draconicevolution:draconic_core') * 10,)
       .inputs(ore('plateStarmetalAlloy') * 64)
       .inputs( ore('wireGtSingleUvSuperconductor') * 64,)
       .inputs( ore('plateTitanSteel') * 64)
       .fluidInputs(fluid('soldering_alloy') * 1440)
       .fluidInputs(fluid('draconium') * 1440)
       .outputs(item('thermalfoundation:upgrade'))
       .duration(100)
       .EUt(2013265920)
       .buildAndRegister()

// Reinforced upgrade
ASSLINE.recipeBuilder()
       .inputs(item('draconicevolution:wyvern_core') * 10)
       .inputs(ore('plateProtoAdamantium') * 64)
       .inputs(ore('wireGtSingleUhvSuperconductor') * 64)
       .inputs(ore('platePikyonium') * 64)
       .fluidInputs(fluid('soldering_alloy') * 1440)
       .fluidInputs(fluid('draconium') * 1440)
       .fluidInputs(fluid('naquadah_alloy') * 1440)
       .outputs(item('thermalfoundation:upgrade', 1))
       .duration(100)
       .EUt(2013265920)
       .buildAndRegister()

// Signalum upgrade
ASSLINE.recipeBuilder()
       .inputs(item('draconicevolution:awakened_core') * 10)
       .inputs(ore('plateSeaborgium') * 64,)
       .inputs(ore('wireGtSingleUevSuperconductor') * 64)
       .inputs(ore('plateBlackTitanium') * 64)
       .fluidInputs(fluid('soldering_alloy') * 1440)
       .fluidInputs(fluid('awaken_draconium') * 14400)
       .fluidInputs(fluid('enriched_naquadah_alloy') * 1440)
       .outputs(item('thermalfoundation:upgrade', 2))
       .duration(100)
       .EUt(2013265920)
       .buildAndRegister()

// Resonant upgrade
ASSLINE.recipeBuilder()
       .inputs(item('draconicevolution:chaotic_core') * 10)
       .inputs(ore('plateBohrium') * 64)
       .inputs(ore('wireGtSingleUivSuperconductor') * 64)
       .inputs(ore('plateHdcs') * 64)
       .fluidInputs(fluid('soldering_alloy') * 1440)
       .fluidInputs(fluid('chaos') * 1440)
       .fluidInputs(fluid('naquadriatic_taranium') * 1440)
       .outputs(item('thermalfoundation:upgrade', 3))
       .duration(100)
       .EUt(2013265920)
       .buildAndRegister()

// Creative conversion kit
ASSLINE.recipeBuilder()
       .inputs(item('thermalfoundation:upgrade'))
       .inputs(item('thermalfoundation:upgrade', 1))
       .inputs(item('thermalfoundation:upgrade', 2))
       .inputs(item('thermalfoundation:upgrade', 3))
       .fluidInputs(fluid('naquadriatic_taranium') * 1440)
       .fluidInputs(fluid('cosmic_neutronium') * 1440)
       .fluidInputs(fluid('enriched_naquadah_alloy') * 1440)
       .fluidInputs(fluid('naquadah_alloy') * 1440)
       .outputs(item('thermalfoundation:upgrade', 256))
       .duration(100)
       .EUt(2013265920)
       .buildAndRegister()
