//TODO: from OtherRecipes
// Utils.removeRecipeByOutput(chemplant, [], [fluid('fermentation_base') * 10000], false)
// Utils.removeRecipeByOutput(pyro, [], [fluid('fermented_biomass') * 10000], false)

// PYROLYSE_OVEN.recipeBuilder()
//         .inputs(metaitem('plant_ball') * 5)
//         .fluidInputs([fluid('water') * 1000])
//         .circuitMeta(0)
//         .chancedOutput(metaitem('plant_ball') * 1, 45, 100)
//         .fluidOutputs([fluid('fermentation_base') * 1000])
//         .duration(600)
//         .EUt(110)
//         .buildAndRegister()

// CHEMICAL_PLANT.recipeBuilder()
//         .inputs(metaitem('plant_ball') * 5)
//         .fluidInputs(fluid('fermentation_base') * 1000, fluid('biomass') * 1000)
//         .fluidOutputs(fluid('fermented_biomass') * 2000)
//         .duration(1200)
//         .EUt(110)
//         .buildAndRegister()

// Utils.removeRecipeByOutput(fermenter, [], [fluid('fermented_biomass')], false)


// FERMENTER.recipeBuilder()
//         .fluidInputs(fluid('biomass') * 144)
//         .fluidOutputs(fluid('fermented_biomass') * 50)
//         .duration(4000)
//         .EUt(2)
//         .buildAndRegister()

// TOOD: juice (GTFO?)

// EXTRACTOR.recipeBuilder()
//         .inputs(item('minecraft:melon'))
//         .fluidOutputs(fluid('juice') * 50)
//         .duration(100)
//         .EUt(30)
//         .buildAndRegister()
// EXTRACTOR.recipeBuilder()
//         .inputs(item('minecraft:apple'))
//         .fluidOutputs(fluid('juice') * 144)
//         .duration(100)
//         .EUt(30)
//         .buildAndRegister()
// EXTRACTOR.recipeBuilder()
//         .inputs(ore('cropSweetBerry,seedSweetBerry'))
//         .fluidOutputs(fluid('juice') * 50)
//         .duration(100)
//         .EUt(30)
//         .buildAndRegister()
// EXTRACTOR.recipeBuilder()
//         .inputs(ore('sugarcane'))
//         .fluidOutputs(fluid('juice') * 144)
//         .duration(100)
//         .EUt(30)
//         .buildAndRegister()
// EXTRACTOR.recipeBuilder()
//         .inputs(ore('blockCactus'))
//         .fluidOutputs(fluid('juice') * 512)
//         .duration(100)
//         .EUt(30)
//         .buildAndRegister()
// EXTRACTOR.recipeBuilder()
//         .inputs(ore('cropPumpkin'))
//         .fluidOutputs(fluid('juice') * 512)
//         .duration(100)
//         .EUt(30)
//         .buildAndRegister()


// distillery.findRecipe(100, [item('gregtech:meta_item_1:32766').withNbt({ Configuration: 0 })], [fluid('biomass') * 2000]).remove()

// DISTILLERY.recipeBuilder()
//         .fluidInputs(fluid('biomass') * 1000)
//         .fluidOutputs(fluid('ethanol') * 600)
//         .circuitMeta(0)
//         .EUt(16)
//         .duration(80)
//         .buildAndRegister()