//TODO: from OtherRecipes


//  TODO: Nuclear stuff
// //naq

// nuclear_reactor.recipeBuilder()
//         .inputs(ore('stickNaquadah') * 2)
//         .blastFurnaceTemp(1000)
//         .circuitMeta(0)
//         .outputs(ore('stickPlatinum') * 2)
//         .outputs(item('gtadditions:ga_meta_item:32312') * 16)
//         .duration(500)
//         .EUt(30)
//         .buildAndRegister()

// nuclear_breeder.recipeBuilder()
//         .inputs(ore('stickNaquadah') * 2)
//         .inputs(item('gtadditions:ga_meta_item:17075') * 10)
//         .blastFurnaceTemp(1000)
//         .circuitMeta(0)
//         .outputs(ore('stickPlatinum') * 2)
//         .outputs(item('gtadditions:ga_meta_item:32312') * 8)
//         .outputs(item('gtadditions:ga_meta_item:9815') * 10)
//         .outputs(item('gtadditions:ga_meta_item:9819') * 10)
//         .duration(500)
//         .EUt(30)
//         .buildAndRegister()

// //enriched naq

// nuclear_reactor.recipeBuilder()
//         .inputs(ore('stickNaquadahEnriched') * 2)
//         .blastFurnaceTemp(1000)
//         .circuitMeta(0)
//         .outputs(ore('stickNaquadah') * 2)
//         .outputs(item('gtadditions:ga_meta_item:32312') * 16)
//         .duration(500)
//         .EUt(30)
//         .buildAndRegister()

// nuclear_breeder.recipeBuilder()
//         .inputs(ore('stickNaquadahEnriched') * 2)
//         .inputs(item('gtadditions:ga_meta_item:16053') * 10)
//         .blastFurnaceTemp(1000)
//         .circuitMeta(0)
//         .outputs(ore('stickNaquadah') * 2)
//         .outputs(item('gtadditions:ga_meta_item:32312') * 8)
//         .outputs(item('gtadditions:ga_meta_item:11809') * 10)
//         .outputs(item('gtadditions:ga_meta_item:11053') * 10)
//         .duration(500)
//         .EUt(30)
//         .buildAndRegister()

// //naqudria

// nuclear_reactor.recipeBuilder()
//         .inputs(ore('stickNaquadria') * 2)
//         .blastFurnaceTemp(1000)
//         .circuitMeta(0)
//         .outputs(ore('stickNaquadahEnriched') * 2)
//         .outputs(item('gtadditions:ga_meta_item:32312') * 16)
//         .duration(500)
//         .EUt(30)
//         .buildAndRegister()

// nuclear_breeder.recipeBuilder()
//         .inputs(ore('stickNaquadria') * 2)
//         .inputs(item('gtadditions:ga_meta_item:16809') * 10)
//         .blastFurnaceTemp(1000)
//         .circuitMeta(0)
//         .outputs(ore('stickNaquadahEnriched') * 2)
//         .outputs(item('gtadditions:ga_meta_item:32312') * 8)
//         .outputs(item('gtadditions:ga_meta_item:11799') * 10)
//         .outputs(item('gtadditions:ga_meta_item:9804') * 10)
//         .duration(500)
//         .EUt(30)
//         .buildAndRegister()

// //awaken draconium

// nuclear_reactor.recipeBuilder()
//         .inputs(ore('stickAwakenDraconium') * 2)
//         .blastFurnaceTemp(1000)
//         .circuitMeta(0)
//         .outputs(ore('stickDraconium') * 2)
//         .outputs(item('gtadditions:ga_meta_item:32312') * 30)
//         .duration(500)
//         .EUt(30)
//         .buildAndRegister()

// nuclear_breeder.recipeBuilder()
//         .inputs(ore('stickAwakenDraconium') * 2)
//         .inputs(item('gtadditions:ga_meta_item:17795') * 10)
//         .blastFurnaceTemp(1000)
//         .circuitMeta(0)
//         .outputs(ore('stickDraconium') * 2)
//         .outputs(item('gtadditions:ga_meta_item:32312') * 16)
//         .outputs(item('gtadditions:ga_meta_item:11789') * 10)
//         .outputs(item('gtadditions:ga_meta_item:9793') * 10)
//         .duration(500)
//         .EUt(30)
//         .buildAndRegister()

// //refined chaos

// nuclear_reactor.recipeBuilder()
//         .inputs(item('gregtech:meta_item_1:14520') * 2)
//         .blastFurnaceTemp(1000)
//         .circuitMeta(0)
//         .outputs(ore('stickAwakenDraconium') * 2)
//         .outputs(item('gtadditions:ga_meta_item:32312') * 32)
//         .duration(500)
//         .EUt(30)
//         .buildAndRegister()

// nuclear_breeder.recipeBuilder()
//         .inputs(item('gregtech:meta_item_1:14520') * 2)
//         .inputs(item('gtadditions:ga_meta_item:17784') * 10)
//         .blastFurnaceTemp(1000)
//         .circuitMeta(0)
//         .outputs(ore('stickAwakenDraconium') * 2)
//         .outputs(item('gtadditions:ga_meta_item:32312') * 16)
//         .outputs(item('gtadditions:ga_meta_item:11778') * 10)
//         .outputs(item('gtadditions:ga_meta_item:11783') * 10)
//         .duration(500)
//         .EUt(30)
//         .buildAndRegister()