//TODO: from OtherRecipes
// Utils.removeRecipeByOutput(tower, [], [fluid('sulfuric_heavy_fuel')], false) //triple all values-
// DISTILLATION_TOWER.recipeBuilder()
//         .fluidInputs(fluid('oil_heavy') * 4500)
//         .fluidOutputs(fluid('sulfuric_heavy_fuel') * 7500, fluid('sulfuric_light_fuel') * 1350, fluid('sulfuric_naphtha') * 450, fluid('sulfuric_gas') * 18000)
//         .duration(400)
//         .EUt(10)
//         .buildAndRegister()
// DISTILLATION_TOWER.recipeBuilder()
//         .fluidInputs(fluid('oil_medium') * 3000)
//         .fluidOutputs(fluid('sulfuric_heavy_fuel') * 450, fluid('sulfuric_light_fuel') * 1500, fluid('sulfuric_naphtha') * 600, fluid('sulfuric_gas') * 1800)
//         .duration(400)
//         .EUt(10)
//         .buildAndRegister()
// DISTILLATION_TOWER.recipeBuilder()
//         .fluidInputs(fluid('oil_light') * 450)
//         .fluidOutputs(fluid('sulfuric_heavy_fuel') * 300, fluid('sulfuric_light_fuel') * 600, fluid('sulfuric_naphtha') * 900, fluid('sulfuric_gas') * 7500)
//         .duration(400)
//         .EUt(10)
//         .buildAndRegister()
// DISTILLATION_TOWER.recipeBuilder()
//         .fluidInputs(fluid('oil') * 1500)
//         .fluidOutputs(fluid('sulfuric_heavy_fuel') * 450, fluid('sulfuric_light_fuel') * 1500, fluid('sulfuric_naphtha') * 600, fluid('sulfuric_gas') * 1800)
//         .duration(400)
//         .EUt(10)
//         .buildAndRegister()