name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "TJ-CEu" branch
  push:
    branches: [ "TJ-CEu" ]
  pull_request:
    branches: [ "TJ-CEu" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world!
      
      - name: Setup Go environment
        uses: actions/setup-go@v5.4.0

      - name: Install Packwiz
        run: |
          go install github.com/packwiz/packwiz@latest
      
      - name: Build Curseforge modpack
        run: |
          mkdir build
          packwiz curseforge export --output build/output.zip
      
      - name: Unzip output.zip
        run: |
          unzip build/output.zip -d build/output
      
      - name: Upload modpack
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Technological-Journey-CEu-$(git rev-parse --short ${{ github.sha }})
          # A file, directory or wildcard pattern that describes what to upload
          path: build/output
      
      - name: Download Cleanroom
        uses: robinraju/release-downloader@v1.12
        with:
          repository: 'CleanroomMC/Cleanroom'
          latest: true
          fileName: 'Cleanroom-MMC-instance-*.zip'
          out-file-path: 'build/Cleanroom'
          extract: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Add Cleanroom for modpack
        run: |
          cd build/Cleanroom
          mv libraries patches mmc-pack.json -t ../output

      - name: Upload Cleanroom version
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Technological-Journey-CEu-Cleanroom-$(git rev-parse --short ${{ github.sha }})
          # A file, directory or wildcard pattern that describes what to upload
          path: build/output
