name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "TJ-CEu" branch
  push:
    branches: [ "TJ-CEu" ]
  pull_request:
    branches: [ "TJ-CEu" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install Packwiz
        run: |
          wget -O packwiz.zip https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip
          unzip packwiz.zip

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
    
      - name: Build Curseforge modpack
        run: |
          mkdir build
          ./packwiz curseforge export --output build/output.zip
      
      - name: Unzip output.zip
        run: |
          unzip build/output.zip -d build/output
          mv output.zip Technological-Journey-CEu-$COMMIT_SHORT_SHA.zip
      
      - name: Download Cleanroom
        uses: robinraju/release-downloader@v1.12
        with:
          repository: 'CleanroomMC/Cleanroom'
          latest: true
          fileName: 'Cleanroom-MMC-instance-*.zip'
          out-file-path: 'build/Cleanroom'
          extract: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Add Cleanroom for modpack
        run: |
          cd build/Cleanroom
          mv libraries patches mmc-pack.json -t ../output
          cd ../iutput
          zip -r ../Technological-Journey-CEu-Cleanroom-$COMMIT_SHORT_SHA.zip ./*

      - name: Publish to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: "build/*.zip"
          fail_on_unmatched_files: true
          prerelease: true
          tag_name: "testing"
          name: "Beta Release Testing ${{ env.COMMIT_SHORT_SHA }}"
          body: "Testing Pre-release for TJ-CEu package"
